/**
 * Runs the MessageShell prototype and converts its ANSI output to a single
 * HTML file the user can open in any browser. Side-steps the chat surface
 * stripping ANSI codes.
 *
 *   cd packages/coding-agent
 *   npx tsx test/prototype-to-html.mts
 *
 * Writes to: packages/coding-agent/prototype-message-shell.html (gitignored
 * via the repo's existing .pi/ and build-output ignores; if you don't want it
 * tracked, delete after viewing).
 */

import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { ansiLinesToHtml } from "../src/core/export-html/ansi-to-html.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Run the prototype with truecolor + minimal env so the output is stable.
const result = spawnSync(process.execPath, [
	"--import",
	"tsx",
	join(__dirname, "prototype-message-shell.mts"),
], {
	cwd: join(__dirname, ".."),
	env: { ...process.env, COLORTERM: "truecolor", FORCE_COLOR: "3", NO_COLOR: undefined as never },
	encoding: "utf8",
	maxBuffer: 32 * 1024 * 1024,
});

if (result.status !== 0) {
	console.error(result.stderr);
	process.exit(result.status ?? 1);
}

const lines = result.stdout.replace(/\r\n/g, "\n").split("\n");
const body = ansiLinesToHtml(lines);

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>MessageShell prototype — BEFORE vs AFTER</title>
<style>
  :root { color-scheme: dark; }
  body {
    margin: 0;
    padding: 24px 32px;
    background: #18181e;
    color: #d4d4d4;
    font-family: ui-monospace, "JetBrains Mono", Consolas, Menlo, monospace;
    font-size: 13px;
    line-height: 1.5;
  }
  .wrap {
    max-width: 1100px;
    margin: 0 auto;
    background: #1e1e24;
    padding: 24px 28px;
    border-radius: 8px;
    box-shadow: 0 8px 40px rgba(0,0,0,0.5);
  }
  h1 {
    font-size: 14px;
    color: #f0c674;
    margin: 0 0 16px 0;
    letter-spacing: 0.04em;
  }
  .ansi-line {
    white-space: pre;
    /* preserve trailing/embedded spaces from terminal output */
    font-variant-ligatures: none;
    tab-size: 4;
  }
  /* Empty lines render as &nbsp; from the converter; keep them visible. */
  .ansi-line:empty::before { content: " "; }
  .note {
    color: #808080;
    font-size: 12px;
    margin-top: 16px;
    border-top: 1px solid #2a2a32;
    padding-top: 12px;
  }
</style>
</head>
<body>
<div class="wrap">
<h1>PIT — MessageShell prototype (Leva 2)</h1>
${body}
<p class="note">Generated by <code>test/prototype-to-html.mts</code>. ANSI → HTML via <code>ansi-to-html.ts</code> (same converter used by <code>/export</code>).</p>
</div>
</body>
</html>
`;

const outPath = join(__dirname, "..", "prototype-message-shell.html");
writeFileSync(outPath, html, "utf8");
console.log(`wrote ${outPath}`);
