/**
 * Context compaction for long sessions.
 *
 * Pure functions for compaction logic. The session manager handles I/O,
 * and after compaction the session is reloaded.
 */

import { readFile, stat } from "node:fs/promises";
import { isAbsolute, relative, resolve } from "node:path";
import type { AgentMessage, StreamFn, ThinkingLevel } from "@pit/agent-core";
import type { AssistantMessage, Context, Message, Model, SimpleStreamOptions, Usage } from "@pit/ai";
import { completeSimple } from "@pit/ai";
import { isTruthyEnvFlag } from "../../utils/env-flags.ts";
import { getCurrentDeferredOutputStore } from "../deferred-output-store.ts";
import { lspSupersededResourceKey } from "../lsp/supersede.ts";
import { convertToLlm } from "../messages.ts";
import { MESSAGE_RELAY_CUSTOM_TYPE } from "../messaging/types.ts";
import { getLivingRepoMap, livingRepoMapToDigests } from "../repo-map/living-index.ts";
import { buildSessionContext, type CompactionEntry, type SessionEntry } from "../session-manager.ts";
import { MUTATING_TOOL_NAMES } from "../stagnation.ts";
import { crushJson } from "../tools/json-crush.ts";
import { buildFileDigests, formatFileDigests, MAX_DIGEST_BYTES } from "./file-digests.ts";
import { groundSummaryPaths } from "./summary-grounding.ts";
import {
	capThinkingForContext,
	computeOperationLists,
	createFileOps,
	extractFileOpsFromMessage,
	type FileOperations,
	formatFileOperations,
	getMessageFromEntry as getMessageFromEntryShared,
	headTailExcerpt as headTailExcerptShared,
	mergeSummaryDetailsIntoFileOps,
	normalizeStructuredSummaryOutput,
	SUMMARIZATION_SYSTEM_PROMPT,
	type SummaryDetails,
	serializeConversation,
	serializeConversationDelta,
	trimSummaryProseAgainstOperations,
} from "./utils.ts";

// ============================================================================
// File Operation Tracking
// ============================================================================

/** Details stored in CompactionEntry.details for structured summary frame.
 *
 * Older sessions only carry `readFiles` and `modifiedFiles`. The remaining
 * fields are populated by the structured summary frame and are loaded
 * defensively when present. Extends the shared {@link SummaryDetails} (the same
 * operation lists branch summarization persists) with compaction-only digests.
 */
export interface CompactionDetails extends SummaryDetails {
	/** path -> top symbols, derived at compaction time. Lossy guide; re-read for current content. */
	fileDigests?: Record<string, string>;
}

/**
 * Extract file operations from messages and previous compaction entries.
 */
function extractFileOperations(
	messages: AgentMessage[],
	entries: SessionEntry[],
	prevCompactionIndex: number,
): FileOperations {
	const fileOps = createFileOps();

	// Collect from previous compaction's details (if pi-generated)
	if (prevCompactionIndex >= 0) {
		const prevCompaction = entries[prevCompactionIndex] as CompactionEntry;
		if (!prevCompaction.fromHook && prevCompaction.details) {
			// fromHook field kept for session file compatibility
			mergeSummaryDetailsIntoFileOps(prevCompaction.details as CompactionDetails, fileOps);
		}
	}

	// Extract from tool calls in messages
	for (const msg of messages) {
		extractFileOpsFromMessage(msg, fileOps);
	}

	return fileOps;
}

// ============================================================================
// Message Extraction
// ============================================================================

/**
 * Extract AgentMessage from an entry, skipping `compaction` entries (their
 * summary is regenerated by the in-progress compaction, so it must not be
 * re-summarized). Delegates to the shared {@link getMessageFromEntryShared}.
 *
 * NOTE: for `type === "message"` this returns `entry.message` BY REFERENCE — see
 * the shared function's docs; callers that mutate must clone first (see
 * `cloneToolResultMessagesForPrune`).
 */
function getMessageFromEntryForCompaction(entry: SessionEntry): AgentMessage | undefined {
	return getMessageFromEntryShared(entry, { skipCompaction: true });
}

/** Result from compact() - SessionManager adds uuid/parentUuid when saving */
export interface CompactionResult<T = unknown> {
	summary: string;
	firstKeptEntryId: string;
	tokensBefore: number;
	/** Extension-specific data (e.g., ArtifactIndex, version markers for structured compaction) */
	details?: T;
}

// ============================================================================
// Types
// ============================================================================

export interface CompactionSettings {
	enabled: boolean;
	reserveTokens: number;
	keepRecentTokens: number;
	/** Enable self-correction verification pass after summarization. Default: true */
	selfCorrection?: boolean;
}

export const DEFAULT_COMPACTION_SETTINGS: CompactionSettings = {
	enabled: true,
	reserveTokens: 16384,
	keepRecentTokens: 20000,
	selfCorrection: true,
};

// ============================================================================
// Token calculation
// ============================================================================

/**
 * Calculate total context tokens from usage.
 * Uses the native totalTokens field when available, falls back to computing from components.
 */
export function calculateContextTokens(usage: Usage): number {
	return usage.totalTokens || usage.input + usage.output + usage.cacheRead + usage.cacheWrite;
}

/**
 * Get usage from an assistant message if available.
 * Skips aborted and error messages as they don't have valid usage data.
 */
function getAssistantUsage(msg: AgentMessage): Usage | undefined {
	if (msg.role === "assistant" && "usage" in msg) {
		const assistantMsg = msg as AssistantMessage;
		if (assistantMsg.stopReason !== "aborted" && assistantMsg.stopReason !== "error" && assistantMsg.usage) {
			return assistantMsg.usage;
		}
	}
	return undefined;
}

/**
 * Find the last non-aborted assistant message usage from session entries.
 */
export function getLastAssistantUsage(entries: SessionEntry[]): Usage | undefined {
	for (let i = entries.length - 1; i >= 0; i--) {
		const entry = entries[i];
		if (entry.type === "message") {
			const usage = getAssistantUsage(entry.message);
			if (usage) return usage;
		}
	}
	return undefined;
}

export interface ContextUsageEstimate {
	tokens: number;
	usageTokens: number;
	trailingTokens: number;
	lastUsageIndex: number | null;
}

/** Minimal tool surface for wire-size estimation (name + API schema). */
export interface WireToolSurface {
	name: string;
	description: string;
	parameters: unknown;
}

export interface WireEstimateInput {
	systemPromptChars: number;
	tools: WireToolSurface[];
	/** Messages not yet appended to session state (e.g. pending user turn). */
	pendingMessages?: AgentMessage[];
}

export interface WireUsageEstimate extends ContextUsageEstimate {
	/** Message-only portion (same as {@link ContextUsageEstimate.tokens}). */
	messageTokens: number;
	systemTokens: number;
	toolTokens: number;
	pendingTokens: number;
}

/**
 * Estimate of a tool-surface array, memoized by ARRAY reference. Tool schemas
 * are static per session, yet this ran a JSON.stringify over every schema on
 * every presend estimate. Callers that reuse the same surfaces array (see
 * `_wireToolsForEstimate`) pay the stringify once; throwaway arrays miss and
 * are GC'd with their entry.
 */
const toolSurfaceTokensCache = new WeakMap<object, number>();

/** Estimate serialized tool-definition payload on the wire. */
export function estimateToolSurfaceTokens(tools: WireToolSurface[]): number {
	const cached = toolSurfaceTokensCache.get(tools);
	if (cached !== undefined) return cached;
	let denseChars = 0;
	for (const tool of tools) {
		denseChars += tool.name.length + tool.description.length + JSON.stringify(tool.parameters).length;
	}
	const estimate = Math.ceil(denseChars / CHARS_PER_TOKEN_DENSE);
	toolSurfaceTokensCache.set(tools, estimate);
	return estimate;
}

/**
 * Estimate full provider wire size: session messages + system prompt + tool
 * schemas + any pending (not-yet-appended) messages.
 */
export function estimateWireTokens(messages: AgentMessage[], input: WireEstimateInput): WireUsageEstimate {
	const messageEstimate = estimateContextTokens(messages);
	let pendingTokens = 0;
	if (input.pendingMessages) {
		for (const message of input.pendingMessages) {
			pendingTokens += estimateTokens(message);
		}
	}
	const systemTokens = Math.ceil(input.systemPromptChars / CHARS_PER_TOKEN_PROSE);
	const toolTokens = estimateToolSurfaceTokens(input.tools);
	const tokens = messageEstimate.tokens + pendingTokens + systemTokens + toolTokens;
	return {
		...messageEstimate,
		messageTokens: messageEstimate.tokens,
		systemTokens,
		toolTokens,
		pendingTokens,
		tokens,
	};
}

function getLastAssistantUsageInfo(messages: AgentMessage[]): { usage: Usage; index: number } | undefined {
	for (let i = messages.length - 1; i >= 0; i--) {
		const usage = getAssistantUsage(messages[i]);
		if (usage) return { usage, index: i };
	}
	return undefined;
}

/**
 * Estimate context tokens from messages, using the last assistant usage when available.
 * If there are messages after the last usage, estimate their tokens with estimateTokens.
 */
export function estimateContextTokens(messages: AgentMessage[]): ContextUsageEstimate {
	const usageInfo = getLastAssistantUsageInfo(messages);

	if (!usageInfo) {
		let estimated = 0;
		for (const message of messages) {
			estimated += estimateTokens(message);
		}
		return {
			tokens: estimated,
			usageTokens: 0,
			trailingTokens: estimated,
			lastUsageIndex: null,
		};
	}

	const usageTokens = calculateContextTokens(usageInfo.usage);
	let trailingTokens = 0;
	for (let i = usageInfo.index + 1; i < messages.length; i++) {
		trailingTokens += estimateTokens(messages[i]);
	}

	return {
		tokens: usageTokens + trailingTokens,
		usageTokens,
		trailingTokens,
		lastUsageIndex: usageInfo.index,
	};
}

/**
 * Compute a dynamic reserve that scales with context window size.
 * - Small windows (≤200k): 10% of window, or the configured reserve.
 * - Large windows (>200k): the configured reserve, a 20k floor, AND a 2.5%
 *   floor. The percentage floor matters for very large windows: a flat 20k on a
 *   1M window is only 2% (trigger at ~98%, dangerously close to the hard limit
 *   if the token estimate runs low); 2.5% keeps ~25k headroom (~97.5%), leaving
 *   slack for estimation error before the model rejects on overflow.
 */
export function computeDynamicReserve(contextWindow: number, configuredReserve: number): number {
	if (!Number.isFinite(contextWindow) || contextWindow <= 0) return 0;
	const rawReserve =
		contextWindow > 200_000
			? Math.max(configuredReserve, 20_000, Math.ceil(contextWindow * 0.025))
			: Math.max(configuredReserve, Math.floor(contextWindow * 0.1));
	const maxUsableReserve = Math.max(1, Math.floor(contextWindow * 0.5));
	return Math.min(rawReserve, maxUsableReserve);
}

/**
 * Effective verbatim-retention budget for findCutPoint.
 *
 * The configured `keepRecentTokens` (default 20k) is a flat floor. On a large
 * window the trigger scales (computeDynamicReserve) but a flat 20k retention
 * would discard ~950k of raw recent messages in favor of a lossy summary. Scale
 * retention to 10% of the window above 200k (same threshold/percentage as the
 * reserve), keeping the configured value as a floor. Windows ≤200k are byte-
 * identical (10% of 200k == the 20k default floor).
 */
export function effectiveKeepRecentTokens(configured: number, contextWindow?: number): number {
	if (!contextWindow || contextWindow <= 200_000) {
		return configured;
	}
	return Math.max(configured, Math.floor(contextWindow * 0.1));
}

/** Tokens assumed for the summary + structural frame a compaction inserts. */
const COMPACTION_SUMMARY_TOKEN_BUDGET = 8_000;
/** Never retain less verbatim recent context than this, whatever the pressure. */
const ADAPTIVE_KEEP_MIN_FLOOR = 8_000;

/**
 * Adaptive verbatim-retention budget for a SINGLE compaction pass.
 *
 * The post-compaction context is ≈ kept-recent + summary. When that lands back
 * above the re-check threshold (the soft threshold, or the hard one on windows
 * too small for a positive soft band), runAutoCompaction used to run a SECOND
 * full pipeline — 1-2 extra LLM calls. On small windows the default keep alone
 * exceeds the target, so the second pass was structural, not incidental. This
 * shrinks the keep so one pass suffices: keep ≤ target − summary budget,
 * floored at max(8k, keepRecentTokens/2) so quality never collapses (the
 * second pass remains as fallback when the floor wins). Returns undefined when
 * no shrink is needed — normal windows are byte-identical to the legacy path.
 */
export function adaptiveKeepRecentTokens(contextWindow: number, settings: CompactionSettings): number | undefined {
	if (!Number.isFinite(contextWindow) || contextWindow <= 0) return undefined;
	const reserve = computeDynamicReserve(contextWindow, settings.reserveTokens);
	const effectiveKeep = effectiveKeepRecentTokens(settings.keepRecentTokens, contextWindow);
	const hardThreshold = contextWindow - reserve;
	const softThreshold = hardThreshold - effectiveKeep;
	// Mirror the post-compaction re-check: shouldCompactSoft only fires with a
	// positive soft threshold; otherwise the hard threshold is the bar.
	const target = softThreshold > 0 ? softThreshold : hardThreshold;
	const keepMax = target - COMPACTION_SUMMARY_TOKEN_BUDGET;
	if (keepMax >= effectiveKeep) return undefined;
	const floor = Math.max(ADAPTIVE_KEEP_MIN_FLOOR, Math.floor(settings.keepRecentTokens / 2));
	const adapted = Math.min(effectiveKeep, Math.max(floor, keepMax));
	return adapted < effectiveKeep ? adapted : undefined;
}

/** Absolute minimum floor for the proactive prune; below this the cache cost is not worth it. */
const PROACTIVE_PRUNE_MIN_FLOOR = 64_000;

/**
 * Context size (tokens) below which the proactive stale-tool-output prune is NOT
 * worth running. The prune rewrites old messages, which busts the provider
 * prompt cache — only pay that when there is real pressure.
 *
 * A flat floor over-prunes on very large windows: at 64k a 1M-window session is
 * ~6% full, so pruning there churns the cache while ~94% of room remains. Scale
 * the floor to 25% of the window, keeping 64k as an absolute minimum (windows up
 * to 256k stay at 64k, byte-identical to the old behaviour). A positive explicit
 * `override` (PIT_PROACTIVE_PRUNE_FLOOR) always wins.
 */
export function proactivePruneFloor(contextWindow: number, override?: number): number {
	if (override !== undefined && Number.isFinite(override) && override > 0) return override;
	const scaled = Number.isFinite(contextWindow) && contextWindow > 0 ? Math.floor(contextWindow * 0.25) : 0;
	return Math.max(PROACTIVE_PRUNE_MIN_FLOOR, scaled);
}

/** Hysteresis threshold: only re-compact if deficit grew by this many tokens since last compaction. */
const COALESCING_THRESHOLD_TOKENS = 8192;

/**
 * Check if compaction should trigger based on context usage.
 * Uses adaptive reserve scaling and hysteresis to avoid compaction churn.
 *
 * @param lastCompactionDeficit - deficit at last compaction trigger (0 if none). Callers
 *   should persist this value and pass it back on subsequent checks.
 */
export function shouldCompact(
	contextTokens: number,
	contextWindow: number,
	settings: CompactionSettings,
	lastCompactionDeficit = 0,
): boolean {
	if (!settings.enabled) return false;
	if (!Number.isFinite(contextWindow) || contextWindow <= 0) return false;
	const reserve = computeDynamicReserve(contextWindow, settings.reserveTokens);
	const threshold = contextWindow - reserve;
	if (contextTokens <= threshold) return false;
	const deficit = contextTokens - threshold;
	if (lastCompactionDeficit === 0) return true;
	return deficit > lastCompactionDeficit + COALESCING_THRESHOLD_TOKENS;
}

/**
 * Soft (predictive) trigger: fire compaction ~one `keepRecentTokens` window
 * BEFORE the hard threshold. Run in the background while the user reads the
 * just-finished turn, so the summary is ready before they send the next prompt
 * (no visible compaction wait). The hard `shouldCompact` stays as the
 * synchronous fallback for turns that jump straight past it.
 *
 * Returns false once at/over the hard threshold — there the caller must compact
 * synchronously, not defer.
 */
export function shouldCompactSoft(contextTokens: number, contextWindow: number, settings: CompactionSettings): boolean {
	if (!settings.enabled) return false;
	if (!Number.isFinite(contextWindow) || contextWindow <= 0) return false;
	const reserve = computeDynamicReserve(contextWindow, settings.reserveTokens);
	const hardThreshold = contextWindow - reserve;
	if (contextTokens > hardThreshold) return false; // hard path owns this
	// Scale the predictive band with the window (same 10%-above-200k rule as retention) so a
	// large window gets a real head-start instead of a flat 20k sliver below the hard threshold
	// that a single big turn would jump straight past into the synchronous path. Windows ≤200k
	// are byte-identical (effectiveKeepRecentTokens returns the raw keepRecentTokens).
	const softThreshold = hardThreshold - effectiveKeepRecentTokens(settings.keepRecentTokens, contextWindow);
	return softThreshold > 0 && contextTokens > softThreshold;
}

// ============================================================================
// Cut point detection
// ============================================================================

/** Chars-per-token ratios for content classification. */
const CHARS_PER_TOKEN_PROSE = 4;
const CHARS_PER_TOKEN_DENSE = 3.3;
/**
 * Non-latin scripts (CJK, Cyrillic, emoji, …) cost far more BPE tokens per
 * char than ASCII — roughly 0.5–2 tok/char. When the non-ASCII code-point
 * fraction exceeds this threshold, fall back to a denser divisor so the
 * estimate isn't wildly low (which would mislead findCutPoint / pruning).
 */
const CHARS_PER_TOKEN_NONLATIN = 2;
const NONLATIN_FRACTION_THRESHOLD = 0.3;
/** Token cost for an image block (kept as constant). */
const IMAGE_TOKENS = 1200;

/** Classified char counts for a message — imutável, logo cacheável. */
interface MessageCharCounts {
	dense: number;
	prose: number;
	images: number; // already in tokens (IMAGE_TOKENS per image)
}

const charCountCache = new WeakMap<AgentMessage, MessageCharCounts>();
const argsLengthCache = new WeakMap<object, number>();

function cachedArgsLength(args: unknown): number {
	if (typeof args === "object" && args !== null) {
		const cached = argsLengthCache.get(args);
		if (cached !== undefined) return cached;
		const len = JSON.stringify(args).length;
		argsLengthCache.set(args, len);
		return len;
	}
	return JSON.stringify(args).length;
}

/** Min length for a tool-call arg STRING value to be worth eliding (keeps paths/flags intact). */
const TOOLCALL_ARG_VALUE_MARK_THRESHOLD = 200;

/**
 * Returns a deep copy of a mutation tool-call's arguments with long string
 * values (file bodies, edit oldText/newText) replaced by a short marker, plus
 * the number of chars elided. Short values (paths, flags) pass through. Returns
 * undefined when nothing was large enough to prune. The original object is never
 * mutated — callers reassign the returned copy onto a cloned tool-call block.
 */
function pruneToolCallArguments(args: unknown): { pruned: unknown; saved: number } | undefined {
	if (typeof args !== "object" || args === null) return undefined;
	let saved = 0;
	const walk = (value: unknown): unknown => {
		if (typeof value === "string") {
			if (value.length <= TOOLCALL_ARG_VALUE_MARK_THRESHOLD) return value;
			saved += value.length;
			return `[${value.length} chars elided — applied to disk; the file is the source of truth]`;
		}
		if (Array.isArray(value)) return value.map(walk);
		if (typeof value === "object" && value !== null) {
			const out: Record<string, unknown> = {};
			for (const [k, v] of Object.entries(value)) out[k] = walk(v);
			return out;
		}
		return value;
	};
	const pruned = walk(args);
	if (saved === 0) return undefined;
	return { pruned, saved };
}

/**
 * Classify text as dense (code/JSON/tool-output) or prose.
 * Dense: non-alphanumeric non-space char fraction > 0.20,
 * OR structural symbol density > 0.05.
 */
// Structural symbols counted by isDenseText, as char codes (precomputed once
// instead of an indexOf-scan over the 14-char string per character).
const STRUCTURAL_CODES = new Set<number>('{}[]()<>;:,="'.split("").map((c) => c.charCodeAt(0)));

function isDenseText(text: string): boolean {
	if (text.length === 0) return false;
	let nonAlphaNum = 0;
	let structural = 0;
	for (let i = 0; i < text.length; i++) {
		const cc = text.charCodeAt(i);
		// not whitespace: space(32) tab(9) lf(10) cr(13)
		if (cc !== 32 && cc !== 9 && cc !== 10 && cc !== 13) {
			const isAlnum = (cc >= 48 && cc <= 57) || (cc >= 65 && cc <= 90) || (cc >= 97 && cc <= 122);
			if (!isAlnum) nonAlphaNum++;
		}
		if (STRUCTURAL_CODES.has(cc)) structural++;
	}
	return nonAlphaNum / text.length > 0.2 || structural / text.length > 0.05;
}

/**
 * Estimate tokens for a raw text string, classifying it as dense or prose.
 * Exported for use in pruneOldToolOutputs and tests.
 */
export function estimateTextTokens(text: string, forceDense = false): number {
	if (text.length === 0) return 0;
	// Count non-ASCII code points (surrogate pairs counted once, so emoji = 1).
	let nonAscii = 0;
	let codePoints = 0;
	for (const ch of text) {
		codePoints++;
		const cp = ch.codePointAt(0);
		if (cp !== undefined && cp > 127) nonAscii++;
	}
	// Non-latin heavy text underestimates badly with the ASCII divisors; use a
	// denser ratio so the estimate stays close to real BPE token cost.
	if (codePoints > 0 && nonAscii / codePoints > NONLATIN_FRACTION_THRESHOLD) {
		return Math.ceil(text.length / CHARS_PER_TOKEN_NONLATIN);
	}
	const dense = forceDense || isDenseText(text);
	return Math.ceil(text.length / (dense ? CHARS_PER_TOKEN_DENSE : CHARS_PER_TOKEN_PROSE));
}

/** Count chars in a message, separated by density. Images stored as token count. */
function countMessageChars(message: AgentMessage): MessageCharCounts {
	const cached = charCountCache.get(message);
	if (cached !== undefined) return cached;

	const counts: MessageCharCounts = { dense: 0, prose: 0, images: 0 };

	switch (message.role) {
		case "user": {
			const content = (message as { content: string | Array<{ type: string; text?: string }> }).content;
			if (typeof content === "string") {
				if (isDenseText(content)) counts.dense += content.length;
				else counts.prose += content.length;
			} else if (Array.isArray(content)) {
				for (const block of content) {
					if (block.type === "text" && block.text) {
						if (isDenseText(block.text)) counts.dense += block.text.length;
						else counts.prose += block.text.length;
					}
				}
			}
			break;
		}
		case "assistant": {
			const assistant = message as AssistantMessage;
			for (const block of assistant.content) {
				if (block.type === "text") {
					if (isDenseText(block.text)) counts.dense += block.text.length;
					else counts.prose += block.text.length;
				} else if (block.type === "thinking") {
					// thinking is usually prose
					if (isDenseText(block.thinking)) counts.dense += block.thinking.length;
					else counts.prose += block.thinking.length;
				} else if (block.type === "toolCall") {
					// tool name + JSON args — always dense
					counts.dense += block.name.length + cachedArgsLength(block.arguments);
				}
			}
			break;
		}
		case "custom":
		case "toolResult": {
			if (typeof message.content === "string") {
				// tool result text — always dense
				counts.dense += message.content.length;
			} else {
				for (const block of message.content) {
					if (block.type === "text" && block.text) {
						// tool result text — always dense
						counts.dense += block.text.length;
					}
					if (block.type === "image") {
						counts.images += IMAGE_TOKENS;
					}
				}
			}
			break;
		}
		case "bashExecution": {
			// command + output — always dense
			counts.dense += message.command.length + message.output.length;
			break;
		}
		case "branchSummary":
		case "compactionSummary": {
			if (isDenseText(message.summary)) counts.dense += message.summary.length;
			else counts.prose += message.summary.length;
			break;
		}
	}

	charCountCache.set(message, counts);
	return counts;
}

/**
 * Estimate token count for a message using content-sensitive heuristics.
 * Dense content (code/JSON/tool output) uses ~3.3 chars/token;
 * prose uses ~4 chars/token. Images count as IMAGE_TOKENS each.
 * Results are cached per message object (messages are immutable once created).
 */
export function estimateTokens(message: AgentMessage): number {
	const counts = countMessageChars(message);
	return (
		Math.ceil(counts.prose / CHARS_PER_TOKEN_PROSE) + Math.ceil(counts.dense / CHARS_PER_TOKEN_DENSE) + counts.images
	);
}

/**
 * Find valid cut points: indices of user, assistant, custom, or bashExecution messages.
 * Never cut at tool results (they must follow their tool call).
 * When we cut at an assistant message with tool calls, its tool results follow it
 * and will be kept.
 * BashExecutionMessage is treated like a user message (user-initiated context).
 */
function findValidCutPoints(entries: SessionEntry[], startIndex: number, endIndex: number): number[] {
	const cutPoints: number[] = [];
	for (let i = startIndex; i < endIndex; i++) {
		const entry = entries[i];
		switch (entry.type) {
			case "message": {
				const role = entry.message.role;
				switch (role) {
					case "bashExecution":
					case "custom":
					case "branchSummary":
					case "compactionSummary":
					case "user":
					case "assistant":
						cutPoints.push(i);
						break;
					case "toolResult":
						break;
				}
				break;
			}
			// branch_summary and custom_message are user-role messages, valid cut points
			case "branch_summary":
			case "custom_message":
				cutPoints.push(i);
				break;
			case "thinking_level_change":
			case "model_change":
			case "compaction":
			case "custom":
			case "label":
			case "session_info":
				break;
		}
	}
	return cutPoints;
}

/**
 * Find the user message (or bashExecution) that starts the turn containing the given entry index.
 * Returns -1 if no turn start found before the index.
 * BashExecutionMessage is treated like a user message for turn boundaries.
 */
export function findTurnStartIndex(entries: SessionEntry[], entryIndex: number, startIndex: number): number {
	for (let i = entryIndex; i >= startIndex; i--) {
		const entry = entries[i];
		// branch_summary and custom_message are user-role messages, can start a turn
		if (entry.type === "branch_summary" || entry.type === "custom_message") {
			return i;
		}
		if (entry.type === "message") {
			const role = entry.message.role;
			if (role === "user" || role === "bashExecution") {
				return i;
			}
		}
	}
	return -1;
}

export interface CutPointResult {
	/** Index of first entry to keep */
	firstKeptEntryIndex: number;
	/** Index of user message that starts the turn being split, or -1 if not splitting */
	turnStartIndex: number;
	/** Whether this cut splits a turn (cut point is not a user message) */
	isSplitTurn: boolean;
}

/**
 * Find the cut point in session entries that keeps approximately `keepRecentTokens`.
 *
 * Algorithm: Walk backwards from newest, accumulating estimated message sizes.
 * Stop when we've accumulated >= keepRecentTokens. Cut at that point.
 *
 * Can cut at user OR assistant messages (never tool results). When cutting at an
 * assistant message with tool calls, its tool results come after and will be kept.
 *
 * Returns CutPointResult with:
 * - firstKeptEntryIndex: the entry index to start keeping from
 * - turnStartIndex: if cutting mid-turn, the user message that started that turn
 * - isSplitTurn: whether we're cutting in the middle of a turn
 *
 * Only considers entries between `startIndex` and `endIndex` (exclusive).
 */
export function findCutPoint(
	entries: SessionEntry[],
	startIndex: number,
	endIndex: number,
	keepRecentTokens: number,
): CutPointResult {
	const cutPoints = findValidCutPoints(entries, startIndex, endIndex);

	if (cutPoints.length === 0) {
		return { firstKeptEntryIndex: startIndex, turnStartIndex: -1, isSplitTurn: false };
	}

	// Walk backwards from newest, accumulating estimated message sizes
	let accumulatedTokens = 0;
	let cutIndex = cutPoints[0]; // Default: keep from first message (not header)

	for (let i = endIndex - 1; i >= startIndex; i--) {
		const entry = entries[i];
		if (entry.type !== "message") continue;

		// Estimate this message's size
		const messageTokens = estimateTokens(entry.message);
		accumulatedTokens += messageTokens;

		// Check if we've exceeded the budget
		if (accumulatedTokens >= keepRecentTokens) {
			// Find the closest valid cut point at or after this entry
			for (let c = 0; c < cutPoints.length; c++) {
				if (cutPoints[c] >= i) {
					cutIndex = cutPoints[c];
					break;
				}
			}
			break;
		}
	}

	// Scan backwards from cutIndex to include any non-message entries (bash, settings, etc.)
	while (cutIndex > startIndex) {
		const prevEntry = entries[cutIndex - 1];
		// Stop at session header or compaction boundaries
		if (prevEntry.type === "compaction") {
			break;
		}
		if (prevEntry.type === "message") {
			// Stop if we hit any message
			break;
		}
		// Include this non-message entry (bash, settings change, etc.)
		cutIndex--;
	}

	// Determine if this is a split turn
	const cutEntry = entries[cutIndex];
	const isUserMessage = cutEntry.type === "message" && cutEntry.message.role === "user";
	const turnStartIndex = isUserMessage ? -1 : findTurnStartIndex(entries, cutIndex, startIndex);

	return {
		firstKeptEntryIndex: cutIndex,
		turnStartIndex,
		isSplitTurn: !isUserMessage && turnStartIndex !== -1,
	};
}

// ============================================================================
// Pre-pruning of old tool outputs
// ============================================================================

/** Token threshold above which old tool outputs are pruned before summarization. */
const PRUNE_TOKEN_THRESHOLD = 20_000;
/** Number of recent turns (user→assistant pairs) protected from pruning. */
const PRUNE_PROTECT_TURNS = 2;
/** Chars of the head/tail kept when shrinking a large tool output (see headTailExcerpt). */
const PRUNE_HEAD_CHARS = 1500;
const PRUNE_TAIL_CHARS = 800;
/** Text shorter than this cannot shrink via head+tail excerpt alone. */
const PRUNE_MIN_SHRINK_CHARS = PRUNE_HEAD_CHARS + PRUNE_TAIL_CHARS + 64;

/** Precomputed supersede scan shared across would* / apply* on the same turn. */
export interface ContextPrunePlan {
	protectFromIndex: number;
	supersededIndices: Set<number>;
}

/** One O(n) walk producing protect window + supersede index for reuse. */
export function planContextPrune(messages: AgentMessage[], protectTurns = PRUNE_PROTECT_TURNS): ContextPrunePlan {
	const protectFromIndex = computePruneProtectFromIndex(messages, protectTurns);
	return {
		protectFromIndex,
		supersededIndices: buildSupersededToolResultIndices(messages, protectFromIndex),
	};
}

function resolveContextPrunePlan(
	messages: AgentMessage[],
	protectTurns: number,
	plan: ContextPrunePlan | undefined,
): ContextPrunePlan {
	return plan ?? planContextPrune(messages, protectTurns);
}

function wouldShrinkViaHeadTail(text: string): boolean {
	if (text.length <= PRUNE_MIN_SHRINK_CHARS) return false;
	const excerpt = headTailExcerpt(text);
	return excerpt.length < text.length;
}

/** Floor the adaptive per-output prune threshold approaches as the window fills. */
const ADAPTIVE_PRUNE_MIN_THRESHOLD = 4_000;
/** Occupancy at which the per-output threshold starts tightening below PRUNE_TOKEN_THRESHOLD. */
const ADAPTIVE_PRUNE_START_OCCUPANCY = 0.5;
/** Occupancy at/above which the threshold reaches ADAPTIVE_PRUNE_MIN_THRESHOLD. */
const ADAPTIVE_PRUNE_FULL_OCCUPANCY = 0.9;
const PRESSURE_PRUNE_SMALL_WINDOW = 200_000;
const PRESSURE_PRUNE_ONE_TURN_OCCUPANCY = 0.65;
const PRESSURE_PRUNE_CURRENT_TURN_OCCUPANCY = 0.8;
const PRESSURE_PRUNE_LARGE_WINDOW_OCCUPANCY = 0.9;

/**
 * Number of recent turns protected from live-context pruning under pressure.
 * Small-window models (DeepSeek/OpenRouter/GPT chat class) have little room for a
 * two-turn grace period once they pass ~65%; above ~80%, huge current-turn tool
 * outputs are still recoverable via recall_tool_output, so they can be excerpted.
 */
export function pressurePruneProtectTurns(contextTokens: number, contextWindow: number): number {
	if (!Number.isFinite(contextWindow) || contextWindow <= 0) return PRUNE_PROTECT_TURNS;
	const occupancy = contextTokens / contextWindow;
	if (contextWindow <= PRESSURE_PRUNE_SMALL_WINDOW) {
		if (occupancy >= PRESSURE_PRUNE_CURRENT_TURN_OCCUPANCY) return 0;
		if (occupancy >= PRESSURE_PRUNE_ONE_TURN_OCCUPANCY) return 1;
		return PRUNE_PROTECT_TURNS;
	}
	return occupancy >= PRESSURE_PRUNE_LARGE_WINDOW_OCCUPANCY ? 1 : PRUNE_PROTECT_TURNS;
}

/**
 * Per-output prune threshold that tightens as the context window fills.
 *
 * The flat PRUNE_TOKEN_THRESHOLD (20k) is evaluated per output block, but read
 * caps at ~15k tokens and bash at ~7k — so a *medium* tool output never crosses
 * it on its own. A long session that accumulates dozens of medium reads/greps
 * ("death by a thousand cuts") therefore reclaims nothing even as the window
 * approaches full. This scales the threshold DOWN from 20k toward 4k between 50%
 * and 90% occupancy, so medium outputs become prunable exactly when there is real
 * pressure. At or below 50% occupancy it returns the flat 20k (byte-identical to
 * the previous behaviour — no early over-pruning, no extra cache churn). The
 * excerpt still keeps each output's head+tail shape and the on-disk file remains
 * the source of truth, so this only ever upgrades a reclaim that respects the
 * existing prune contract.
 */
export function adaptivePruneThreshold(contextTokens: number, contextWindow: number): number {
	if (!Number.isFinite(contextWindow) || contextWindow <= 0) return PRUNE_TOKEN_THRESHOLD;
	const occupancy = contextTokens / contextWindow;
	if (occupancy <= ADAPTIVE_PRUNE_START_OCCUPANCY) return PRUNE_TOKEN_THRESHOLD;
	if (occupancy >= ADAPTIVE_PRUNE_FULL_OCCUPANCY) return ADAPTIVE_PRUNE_MIN_THRESHOLD;
	const span = ADAPTIVE_PRUNE_FULL_OCCUPANCY - ADAPTIVE_PRUNE_START_OCCUPANCY;
	const t = (occupancy - ADAPTIVE_PRUNE_START_OCCUPANCY) / span;
	return Math.round(PRUNE_TOKEN_THRESHOLD - t * (PRUNE_TOKEN_THRESHOLD - ADAPTIVE_PRUNE_MIN_THRESHOLD));
}

/**
 * Shrink a large tool output to its head + tail, eliding the middle. Keeps the
 * output's *shape* for the summarizer — first/last grep matches, a file's header
 * + footer, an error message + the tail of its stack — instead of a bare
 * "[pruned]" marker that tells the summarizer nothing. Cuts snap to line breaks
 * so excerpts stay readable.
 */
function headTailExcerpt(text: string): string {
	return headTailExcerptShared(text, {
		headBudget: PRUNE_HEAD_CHARS,
		tailBudget: PRUNE_TAIL_CHARS,
		snapWindow: 400,
		// Prefer a structural crush when the output is JSON/NDJSON: it keeps the
		// schema + head/tail samples + omitted counts at far fewer tokens than a
		// blind byte cut. Returns undefined (→ head+tail fallback) when not
		// applicable (not JSON, or won't fit even when fully collapsed).
		crush: (t) => crushJson(t, { targetChars: PRUNE_HEAD_CHARS + PRUNE_TAIL_CHARS }),
		marker: (_elidedChars, middle) => `[… ~${estimateTextTokens(middle, true)} tokens elided …]`,
	});
}

/**
 * Prune large tool result content from old messages before sending to the
 * summarizer. This reduces the input to the summarization LLM and produces
 * more focused summaries.
 *
 * Only tool results older than the last `protectTurns` user messages are
 * eligible. Tool results above `tokenThreshold` (estimated) are shrunk to a
 * head+tail excerpt (so the reader still sees the output's shape). When `defer`
 * is set (the live-context prune) AND a deferred-output store is open, the full
 * text is ALSO persisted to disk and a `recall_tool_output` id is appended to the
 * excerpt — a hybrid that keeps the shape inline while leaving the elided middle
 * recoverable in full. Compaction-prep callers pass `defer=false` (the summarizer
 * discards these messages, so a recall id would dangle).
 *
 * Mutates the passed messages and their text blocks in place. `getMessageFromEntry`
 * returns `entry.message` BY REFERENCE for `type === "message"` entries (the same
 * object the live session context holds), so callers that prune before a fallible
 * summarization (e.g. compact()) MUST pass cloned toolResult messages — see
 * `cloneToolResultMessagesForPrune` — otherwise an aborted compaction leaves the
 * live context with elided tool results and no restore path.
 */
// Memoize the (stringify + token-estimate) of a mutation tool-call's arguments by
// reference. The same large write/edit body is re-checked every turn above the 64k
// floor; the cost number only changes when `block.arguments` is reassigned (which
// yields a fresh reference on prune), so a WeakMap keyed by the object naturally
// recomputes exactly once for the new (small) value.
const beforeTokensCache = new WeakMap<object, number>();

// Memoize the dense-token estimate of a toolResult text block BY BLOCK OBJECT.
// The would*/apply scans above the prune floor re-estimate the same old blocks
// every turn — an O(chars of history) scan per turn without this. Block text
// only changes via the in-place rewrites in pruneOldToolOutputs and
// applySupersedeOnly, and BOTH update the entry with the post-rewrite estimate,
// so a mutated block never serves a stale value. Cloned blocks (fresh objects
// from cloneToolResultMessagesForPrune) simply miss and recompute.
const denseTextTokensCache = new WeakMap<object, number>();

function cachedDenseTextTokens(block: object, text: string): number {
	const cached = denseTextTokensCache.get(block);
	if (cached !== undefined) return cached;
	const est = estimateTextTokens(text, true);
	denseTextTokensCache.set(block, est);
	return est;
}

const SUPERSEDED_TOOL_RESULT_NAMES = new Set(["read", "grep", "find", "ls", "symbol", "find_symbol", "lsp", "bash"]);

function stableStringify(value: unknown): string {
	if (Array.isArray(value)) return `[${value.map(stableStringify).join(",")}]`;
	if (typeof value === "object" && value !== null) {
		return `{${Object.keys(value as Record<string, unknown>)
			.sort()
			.map((key) => `${JSON.stringify(key)}:${stableStringify((value as Record<string, unknown>)[key])}`)
			.join(",")}}`;
	}
	return JSON.stringify(value) ?? "undefined";
}

/**
 * Resource key for a tool call whose later identical result supersedes the old
 * copy. `read` keeps its path/range aliases for persisted pre-normalization args;
 * other deterministic navigation/search tools use a sorted argument fingerprint.
 */
function supersededResourceKey(toolName: string, args: unknown): string | undefined {
	if (!SUPERSEDED_TOOL_RESULT_NAMES.has(toolName)) return undefined;
	if (toolName === "lsp") return lspSupersededResourceKey(args);
	if (toolName !== "read") return `${toolName}\u0000${stableStringify(args)}`;
	if (typeof args !== "object" || args === null) return undefined;
	const a = args as Record<string, unknown>;
	let path: string | undefined;
	for (const key of ["path", "file", "file_path", "filename"]) {
		const v = a[key];
		if (typeof v === "string" && v.length > 0) {
			path = v;
			break;
		}
	}
	if (!path) return undefined;
	const offset = typeof a.offset === "number" ? a.offset : "";
	const limit = typeof a.limit === "number" ? a.limit : "";
	return `${toolName}\u0000${path}\u0000${offset}\u0000${limit}`;
}

/**
 * Incremental supersede-scan state, keyed by the message ARRAY reference. The
 * live-prune hook plans over `agent.state.messages` after every successful tool
 * call; that array's reference is stable across a turn (the agent appends via
 * `push`; the state setter only swaps the reference on reassignment, which is a
 * rare prune/compaction event). Rebuilding the maps from scratch each call made
 * the per-tool-call cost O(session) → O(session²) over a long session. Caching
 * the scan and extending it over just the appended suffix makes it O(new
 * messages) per call, with a full rebuild only on reference change.
 *
 * Staleness safety: prune mutations (pruneOldToolOutputs / applySupersedeOnly /
 * elideMutatingToolCallArguments) operate on CLONED arrays that are then
 * reassigned — the cached array is never mutated in place. And even if it were,
 * they rewrite toolResult `block.text` and MUTATING tool-call `arguments`
 * (write/edit — outside SUPERSEDED_TOOL_RESULT_NAMES), neither of which feeds
 * `supersededResourceKey`. Same invariant family as `beforeTokensCache`.
 */
interface SupersedeScanState {
	/** Messages [0, scannedLength) have been ingested into the maps below. */
	scannedLength: number;
	/**
	 * toolCall id -> resource key. Calls of superseded-eligible tools whose key
	 * is underivable (e.g. read without a path) store "" so their results are
	 * skipped permanently instead of retried forever via `unkeyedResults`.
	 */
	keyByCallId: Map<string, string>;
	keyByIndex: Map<number, string>;
	lastIndexByKey: Map<string, number>;
	/** Results whose toolCall was not yet seen — retried on each extension. */
	unkeyedResults: Array<{ index: number; toolCallId: string }>;
}

const supersedeScanCache = new WeakMap<AgentMessage[], SupersedeScanState>();

function createSupersedeScanState(): SupersedeScanState {
	return {
		scannedLength: 0,
		keyByCallId: new Map(),
		keyByIndex: new Map(),
		lastIndexByKey: new Map(),
		unkeyedResults: [],
	};
}

function recordKeyedResult(state: SupersedeScanState, index: number, key: string): void {
	state.keyByIndex.set(index, key);
	const prev = state.lastIndexByKey.get(key);
	if (prev === undefined || index > prev) state.lastIndexByKey.set(key, index);
}

/** Ingest messages[state.scannedLength ..] into the scan maps (one suffix pass). */
function extendSupersedeScanState(state: SupersedeScanState, messages: AgentMessage[]): void {
	// (1) Tool calls in the suffix — must land before the suffix's results are
	// resolved, mirroring the full algorithm's call-pass-then-result-pass order.
	for (let i = state.scannedLength; i < messages.length; i++) {
		const msg = messages[i];
		if (msg.role !== "assistant" || !Array.isArray(msg.content)) continue;
		for (const block of msg.content) {
			if (block.type !== "toolCall") continue;
			const key = supersededResourceKey(block.name, block.arguments);
			if (key) state.keyByCallId.set(block.id, key);
			else if (SUPERSEDED_TOOL_RESULT_NAMES.has(block.name)) state.keyByCallId.set(block.id, "");
		}
	}
	// (2) Tool results in the suffix.
	for (let i = state.scannedLength; i < messages.length; i++) {
		const msg = messages[i];
		if (msg.role !== "toolResult" || !SUPERSEDED_TOOL_RESULT_NAMES.has(msg.toolName ?? "")) continue;
		const key = state.keyByCallId.get(msg.toolCallId);
		if (key === undefined) {
			state.unkeyedResults.push({ index: i, toolCallId: msg.toolCallId });
			continue;
		}
		if (key === "") continue; // known keyless call — never supersedes
		recordKeyedResult(state, i, key);
	}
	// (3) Retry results whose call may have arrived in this (or any later)
	// suffix. Keeps exact equivalence with the two full passes even when a
	// result precedes its call in the array.
	if (state.unkeyedResults.length > 0) {
		const stillUnkeyed: SupersedeScanState["unkeyedResults"] = [];
		for (const entry of state.unkeyedResults) {
			const key = state.keyByCallId.get(entry.toolCallId);
			if (key === undefined) stillUnkeyed.push(entry);
			else if (key !== "") recordKeyedResult(state, entry.index, key);
		}
		state.unkeyedResults = stillUnkeyed;
	}
	state.scannedLength = messages.length;
}

/**
 * Derivation over the scan state — recomputed on EVERY call (protectFromIndex
 * varies per call, so the final Set must never be cached). Filter identical to
 * the previous full algorithm; always returns a fresh Set.
 */
function deriveSupersededIndices(state: SupersedeScanState, protectFromIndex: number): Set<number> {
	const superseded = new Set<number>();
	for (const [i, key] of state.keyByIndex) {
		if (i >= protectFromIndex) continue;
		const last = state.lastIndexByKey.get(key);
		if (last !== undefined && last > i) superseded.add(i);
	}
	return superseded;
}

/**
 * Indices (in the prunable region, i.e. `< protectFromIndex`) of deterministic
 * tool results that a later identical call supersedes. The newer result carries
 * the current view, so the older copy is a stale duplicate safe to collapse to
 * head+tail even when it is below the size threshold. The newest result (and any
 * result inside the protected recent turns) is never marked.
 *
 * The scan is incremental per array reference (see {@link SupersedeScanState}):
 * a cache hit only ingests the appended suffix; a new/shrunk array rebuilds.
 */
function buildSupersededToolResultIndices(messages: AgentMessage[], protectFromIndex: number): Set<number> {
	let state = supersedeScanCache.get(messages);
	if (!state || messages.length < state.scannedLength) {
		state = createSupersedeScanState();
		supersedeScanCache.set(messages, state);
	}
	if (messages.length > state.scannedLength) {
		extendSupersedeScanState(state, messages);
	}
	return deriveSupersededIndices(state, protectFromIndex);
}

function computePruneProtectFromIndex(messages: AgentMessage[], protectTurns: number): number {
	let userCount = 0;
	let protectFromIndex = protectTurns <= 0 ? messages.length : 0;
	if (protectTurns > 0) {
		for (let i = messages.length - 1; i >= 0; i--) {
			if (messages[i].role === "user") {
				userCount++;
				if (userCount >= protectTurns) {
					protectFromIndex = i;
					break;
				}
			}
		}
	}
	return protectFromIndex;
}

/** Read-only pre-check: would pruneOldToolOutputs reclaim anything? */
export function wouldPruneOldToolOutputs(
	messages: AgentMessage[],
	tokenThreshold = PRUNE_TOKEN_THRESHOLD,
	protectTurns = PRUNE_PROTECT_TURNS,
	plan?: ContextPrunePlan,
): boolean {
	const { protectFromIndex, supersededIndices: supersededReadIndices } = resolveContextPrunePlan(
		messages,
		protectTurns,
		plan,
	);
	for (let i = 0; i < protectFromIndex; i++) {
		const msg = messages[i];
		if (msg.role === "assistant" && Array.isArray(msg.content)) {
			for (const block of msg.content) {
				if (block.type !== "toolCall" || !MUTATING_TOOL_NAMES.has(block.name)) continue;
				const argsRef =
					typeof block.arguments === "object" && block.arguments !== null ? block.arguments : undefined;
				let before = argsRef ? beforeTokensCache.get(argsRef) : undefined;
				if (before === undefined) {
					before = estimateTextTokens(JSON.stringify(block.arguments), true);
					// Populate the cache on the read-only path too — this check runs every
					// turn, and the stringify cost repeats until an apply happens otherwise.
					if (argsRef) beforeTokensCache.set(argsRef, before);
				}
				if (before > tokenThreshold && pruneToolCallArguments(block.arguments)) return true;
			}
			continue;
		}
		if (msg.role !== "toolResult" || !Array.isArray(msg.content)) continue;
		const superseded = supersededReadIndices.has(i);
		for (const block of msg.content) {
			if (block.type !== "text" || !block.text) continue;
			const est = cachedDenseTextTokens(block, block.text);
			if (est > tokenThreshold) return true;
			if (superseded && wouldShrinkViaHeadTail(block.text)) return true;
		}
	}
	return false;
}

export function pruneOldToolOutputs(
	messages: AgentMessage[],
	tokenThreshold = PRUNE_TOKEN_THRESHOLD,
	protectTurns = PRUNE_PROTECT_TURNS,
	defer = false,
	plan?: ContextPrunePlan,
): number {
	const { protectFromIndex, supersededIndices: supersededReadIndices } = resolveContextPrunePlan(
		messages,
		protectTurns,
		plan,
	);

	let prunedTokens = 0;

	const store = defer ? getCurrentDeferredOutputStore() : undefined;

	for (let i = 0; i < protectFromIndex; i++) {
		const msg = messages[i];
		// Assistant tool-call args for mutation tools (write/edit) carry the full
		// file body / edit text. Once old, that body is redundant — the result
		// already landed on disk — yet it stays in context at full cost every turn
		// until summarization. Elide the heavy string values, keep paths/flags.
		if (msg.role === "assistant" && Array.isArray(msg.content)) {
			for (let b = 0; b < msg.content.length; b++) {
				const block = msg.content[b];
				if (block.type !== "toolCall" || !MUTATING_TOOL_NAMES.has(block.name)) continue;
				const argsRef =
					typeof block.arguments === "object" && block.arguments !== null ? block.arguments : undefined;
				let before = argsRef ? beforeTokensCache.get(argsRef) : undefined;
				if (before === undefined) {
					before = estimateTextTokens(JSON.stringify(block.arguments), true);
					if (argsRef) beforeTokensCache.set(argsRef, before);
				}
				if (before <= tokenThreshold) continue;
				const result = pruneToolCallArguments(block.arguments);
				if (result) {
					(block as { arguments: unknown }).arguments = result.pruned;
					const after = estimateTextTokens(JSON.stringify(result.pruned), true);
					prunedTokens += Math.max(0, before - after);
				}
			}
			continue;
		}
		if (msg.role !== "toolResult") continue;
		if (!Array.isArray(msg.content)) continue;

		const superseded = supersededReadIndices.has(i);
		for (let b = 0; b < msg.content.length; b++) {
			const block = msg.content[b];
			if (block.type === "text" && block.text) {
				// Tool outputs are dense (JSON/code), use dense divisor
				const est = cachedDenseTextTokens(block, block.text);
				if (est > tokenThreshold) {
					// store.put writes to disk (writeFileSync). A disk-full/permission error
					// must degrade to the in-message head+tail excerpt rather than abort the
					// turn that awaits this prune.
					let id: string | undefined;
					if (store) {
						try {
							id = store.put(block.text);
						} catch {
							id = undefined;
						}
					}
					// Hybrid: always keep the head+tail excerpt inline (so the reader still
					// sees the output's shape) and, when the full text was stored, append the
					// recall id so the elided middle is recoverable in full. Strictly better
					// than a bare excerpt (adds a recovery path) and than a bare placeholder
					// (keeps shape). Degrades to the plain excerpt when there is no store
					// (compaction-prep / opt-out) or the deferred write failed.
					const excerpt = headTailExcerpt(block.text);
					const replacement =
						id !== undefined
							? `${excerpt}\n[Full output (~${est} tokens) deferred — recall_tool_output({ id: "${id}" }) returns it in full.]`
							: excerpt;
					(msg.content[b] as any).text = replacement;
					const after = estimateTextTokens(replacement, true);
					denseTextTokensCache.set(block, after);
					prunedTokens += Math.max(0, est - after);
				} else if (superseded) {
					// A stale duplicate of a deterministic navigation/search result repeated
					// later (below the size threshold). Collapse it to head+tail — the newer
					// result carries the current view. Never deferred (a recall id for stale
					// content is pointless); headTailExcerpt no-ops when already small.
					const excerpt = headTailExcerpt(block.text);
					if (excerpt.length < block.text.length) {
						(msg.content[b] as any).text = excerpt;
						const after = estimateTextTokens(excerpt, true);
						denseTextTokensCache.set(block, after);
						prunedTokens += Math.max(0, est - after);
					}
				}
			}
		}
	}

	return prunedTokens;
}

/**
 * Collapse superseded deterministic tool results to head+tail excerpts only.
 * No large-output defer, no mutation-arg elision — minimal cache churn (A1′).
 */
export function applySupersedeOnly(
	messages: AgentMessage[],
	protectTurns = PRUNE_PROTECT_TURNS,
	plan?: ContextPrunePlan,
): number {
	const { protectFromIndex, supersededIndices: supersededReadIndices } = resolveContextPrunePlan(
		messages,
		protectTurns,
		plan,
	);
	let prunedTokens = 0;

	for (let i = 0; i < protectFromIndex; i++) {
		if (!supersededReadIndices.has(i)) continue;
		const msg = messages[i];
		if (msg.role !== "toolResult" || !Array.isArray(msg.content)) continue;
		for (let b = 0; b < msg.content.length; b++) {
			const block = msg.content[b];
			if (block.type !== "text" || !block.text) continue;
			const est = cachedDenseTextTokens(block, block.text);
			const excerpt = headTailExcerpt(block.text);
			if (excerpt.length < block.text.length) {
				(msg.content[b] as { text: string }).text = excerpt;
				const after = estimateTextTokens(excerpt, true);
				denseTextTokensCache.set(block, after);
				prunedTokens += Math.max(0, est - after);
			}
		}
	}

	return prunedTokens;
}

/** Read-only: would {@link applySupersedeOnly} collapse any superseded result? */
export function wouldApplySupersedeOnly(
	messages: AgentMessage[],
	protectTurns = PRUNE_PROTECT_TURNS,
	plan?: ContextPrunePlan,
): boolean {
	const { supersededIndices: supersededReadIndices } = resolveContextPrunePlan(messages, protectTurns, plan);
	for (const i of supersededReadIndices) {
		const msg = messages[i];
		if (msg.role !== "toolResult" || !Array.isArray(msg.content)) continue;
		for (const block of msg.content) {
			if (block.type !== "text" || !block.text) continue;
			if (wouldShrinkViaHeadTail(block.text)) return true;
		}
	}
	return false;
}

/**
 * Elide heavy mutation-tool arguments on the assistant toolCall block for
 * `toolCallId` after a successful apply (A3). No occupancy threshold.
 */
/**
 * Cap assistant thinking blocks older than `protectTurns` user turns (A4).
 * Recent-turn reasoning stays intact for the model; stale blocks shrink on wire.
 */
export function applyOldThinkingCap(messages: AgentMessage[], protectTurns = PRUNE_PROTECT_TURNS): number {
	const protectFromIndex = computePruneProtectFromIndex(messages, protectTurns);
	let prunedTokens = 0;

	for (let i = 0; i < protectFromIndex; i++) {
		const msg = messages[i];
		if (msg.role !== "assistant" || !Array.isArray(msg.content)) continue;
		for (let b = 0; b < msg.content.length; b++) {
			const block = msg.content[b];
			if (block.type !== "thinking" || !block.thinking) continue;
			const capped = capThinkingForContext(block.thinking);
			if (capped.length >= block.thinking.length) continue;
			const before = estimateTextTokens(block.thinking, true);
			(msg.content[b] as { thinking: string }).thinking = capped;
			const after = estimateTextTokens(capped, true);
			prunedTokens += Math.max(0, before - after);
		}
	}

	return prunedTokens;
}

/** Read-only: would {@link applyOldThinkingCap} shrink any thinking block? */
export function wouldApplyOldThinkingCap(messages: AgentMessage[], protectTurns = PRUNE_PROTECT_TURNS): boolean {
	const protectFromIndex = computePruneProtectFromIndex(messages, protectTurns);
	for (let i = 0; i < protectFromIndex; i++) {
		const msg = messages[i];
		if (msg.role !== "assistant" || !Array.isArray(msg.content)) continue;
		for (const block of msg.content) {
			if (block.type !== "thinking" || !block.thinking) continue;
			const capped = capThinkingForContext(block.thinking);
			if (capped.length < block.thinking.length) return true;
		}
	}
	return false;
}

export function elideMutatingToolCallArguments(messages: AgentMessage[], toolCallId: string): number {
	for (const msg of messages) {
		if (msg.role !== "assistant" || !Array.isArray(msg.content)) continue;
		for (let b = 0; b < msg.content.length; b++) {
			const block = msg.content[b];
			if (block.type !== "toolCall" || block.id !== toolCallId) continue;
			if (!MUTATING_TOOL_NAMES.has(block.name)) return 0;
			const argsRef = typeof block.arguments === "object" && block.arguments !== null ? block.arguments : undefined;
			let before = argsRef ? beforeTokensCache.get(argsRef) : undefined;
			if (before === undefined) {
				before = estimateTextTokens(JSON.stringify(block.arguments), true);
				if (argsRef) beforeTokensCache.set(argsRef, before);
			}
			const result = pruneToolCallArguments(block.arguments);
			if (!result) return 0;
			(block as { arguments: unknown }).arguments = result.pruned;
			const after = estimateTextTokens(JSON.stringify(result.pruned), true);
			return Math.max(0, before - after);
		}
	}
	return 0;
}

/**
 * Return a new message array where every `toolResult` message — and the
 * text-bearing content blocks inside it — is shallow-cloned, while all other
 * messages pass through by reference.
 *
 * `pruneOldToolOutputs` rewrites `block.text` in place. For `type === "message"`
 * entries, `getMessageFromEntry` hands back `entry.message` BY REFERENCE, so the
 * toolResult objects (and their content blocks) are the very ones the live
 * session context still points at. Cloning just the toolResult layer here means
 * the prune mutates throw-away copies: if summarization aborts after pruning, the
 * live context is untouched and no re-read/re-edit is needed. On the happy path
 * the produced summary is byte-identical — the clones carry the same text the
 * uncloned objects would have, the originals are simply discarded with the prep.
 *
 * Cloning also sidesteps the per-object `charCountCache` WeakMap: a fresh block
 * object cannot carry a stale cached char count from the pre-prune text.
 */
export function cloneToolResultMessagesForPrune(messages: AgentMessage[]): AgentMessage[] {
	return messages.map((msg) => {
		if (msg.role === "toolResult" && Array.isArray(msg.content)) {
			return {
				...msg,
				content: msg.content.map((block) => (block.type === "text" ? { ...block } : block)),
			};
		}
		// Assistant tool-call blocks are reassigned a pruned `arguments` object by
		// pruneOldToolOutputs; shallow-clone the block so the live context's
		// arguments object is never swapped out under it.
		if (msg.role === "assistant" && Array.isArray(msg.content)) {
			return {
				...msg,
				content: msg.content.map((block) =>
					block.type === "toolCall" || block.type === "thinking" ? { ...block } : block,
				),
			};
		}
		return msg;
	});
}

// ============================================================================
// Summarization
// ============================================================================

const SUMMARIZATION_PROMPT = `The messages above are a conversation to summarize. Create a structured context checkpoint summary that another LLM will use to continue the work.

Use this EXACT format:

## Goal
[What is the user trying to accomplish? Can be multiple items if the session covers different tasks.]

## Constraints & Preferences
- [Any constraints, preferences, or requirements mentioned by user]
- [Or "(none)" if none were mentioned]

## Progress
### Done
- [x] [Completed tasks/changes]

### In Progress
- [ ] [Current work]

### Blocked
- [Issues preventing progress, if any]

## Key Decisions
- **[Decision]**: [Brief rationale]

## Next Steps
1. [Ordered list of what should happen next]

## Critical Context
- [Any data, examples, or references needed to continue]
- [Or "(none)" if not applicable]

Keep each section concise. Preserve exact file paths, function names, and error messages.

STRUCTURED-PRIMARY (output economy): File paths, searches, shell commands, and MCP calls are appended automatically as structured XML tags after your summary. Do NOT list them in prose — focus prose on intent, decisions, blockers, and next steps only. Keep each section to 1–3 bullets max.`;

const SUMMARIZATION_JSON_PROMPT = `The messages above are a conversation to summarize. Produce a JSON context checkpoint another LLM will use to continue the work.

Your final assistant message MUST be a single fenced \`\`\`json\`\`\` block matching this schema (no markdown sections, no prose outside the fence):
{
  "goal": ["string"],
  "constraints": ["string"],
  "done": ["completed items — omit [x] prefix"],
  "inProgress": ["current work — omit [ ] prefix"],
  "blocked": ["blockers or empty array"],
  "keyDecisions": ["Decision: rationale"],
  "nextSteps": ["ordered strings"],
  "criticalContext": ["data/refs needed to continue or empty array"]
}

Keep each array to 1–3 items max. Do NOT list file paths, searches, shell commands, or MCP calls — they are appended as structured XML after parsing.`;

const UPDATE_SUMMARIZATION_PROMPT = `The messages above are NEW conversation messages to incorporate into the existing summary provided in <previous-summary> tags.

When the new messages are inside <conversation-delta>, they are a compact JSON array of events:
[{"k":"u","t":"user text"},{"k":"a","t":"assistant text"},{"k":"c","n":"toolName","a":{args}},{"k":"r","n":"toolName","t":"result excerpt","e":1}]
Keys: u=user, a=assistant, c=tool call, r=tool result (e=1 only on error). Thinking is omitted — use <previous-summary> for prior reasoning.

Update the existing structured summary with new information. RULES:
- PRESERVE all existing information from the previous summary
- ADD new progress, decisions, and context from the new messages
- UPDATE the Progress section: move items from "In Progress" to "Done" when completed
- UPDATE "Next Steps" based on what was accomplished
- PRESERVE exact file paths, function names, and error messages
- If something is no longer relevant, you may remove it

Use this EXACT format:

## Goal
[Preserve existing goals, add new ones if the task expanded]

## Constraints & Preferences
- [Preserve existing, add new ones discovered]

## Progress
### Done
- [x] [Include previously done items AND newly completed items]

### In Progress
- [ ] [Current work - update based on progress]

### Blocked
- [Current blockers - remove if resolved]

## Key Decisions
- **[Decision]**: [Brief rationale] (preserve all previous, add new)

## Next Steps
1. [Update based on current state]

## Critical Context
- [Preserve important context, add new if needed]

Keep each section concise. Preserve exact file paths, function names, and error messages.

STRUCTURED-PRIMARY (output economy): Do NOT duplicate file paths, searches, or shell commands in prose — they are appended as structured XML. Update intent/decisions/blockers only; 1–3 bullets per section.`;

const UPDATE_SUMMARIZATION_JSON_PROMPT = `The messages above are NEW conversation messages to incorporate into the existing summary provided in <previous-summary> tags.

When the new messages are inside <conversation-delta>, they are a compact JSON array of events:
[{"k":"u","t":"user text"},{"k":"a","t":"assistant text"},{"k":"c","n":"toolName","a":{args}},{"k":"r","n":"toolName","t":"result excerpt","e":1}]
Keys: u=user, a=assistant, c=tool call, r=tool result (e=1 only on error). Thinking is omitted — use <previous-summary> for prior reasoning.

Merge new information into the checkpoint. PRESERVE prior goals/decisions unless obsolete; UPDATE progress and next steps.

Your final assistant message MUST be a single fenced \`\`\`json\`\`\` block matching this schema (no markdown, no prose outside the fence):
{
  "goal": ["string"],
  "constraints": ["string"],
  "done": ["completed items"],
  "inProgress": ["current work"],
  "blocked": ["blockers"],
  "keyDecisions": ["Decision: rationale"],
  "nextSteps": ["ordered strings"],
  "criticalContext": ["refs needed"]
}

Keep each array to 1–3 items. Do NOT list file paths, searches, or shell commands — appended as structured XML after parsing.`;

function summarizationUsesJsonOutput(): boolean {
	return !isTruthyEnvFlag(process.env.PIT_NO_STRUCTURED_SUMMARY_OUTPUT);
}

/**
 * Lazy memo of the two serialized views of an immutable message window:
 * `llm` (convertToLlm) and `delta` (serializeConversationDelta over `llm`).
 * generateSummary and buildVerificationSource both consume the SAME window;
 * without the memo each recomputes convertToLlm + delta over identical
 * messages. Getters are lazy so the structural-only path pays nothing.
 *
 * The window messages MUST be immutable for the object's lifetime — in
 * compact() that means creating it AFTER pruneOldToolOutputs (which rewrites
 * block.text in place).
 */
export interface SerializedWindow {
	readonly llm: Message[];
	readonly delta: string;
}

export function createSerializedWindow(messages: AgentMessage[]): SerializedWindow {
	let llm: Message[] | undefined;
	let delta: string | undefined;
	return {
		get llm(): Message[] {
			llm ??= convertToLlm(messages);
			return llm;
		},
		get delta(): string {
			delta ??= serializeConversationDelta(this.llm);
			return delta;
		},
	};
}

function createSummarizationOptions(
	model: Model<any>,
	maxTokens: number,
	apiKey: string | undefined,
	headers: Record<string, string> | undefined,
	signal: AbortSignal | undefined,
	thinkingLevel: ThinkingLevel | undefined,
): SimpleStreamOptions {
	const options: SimpleStreamOptions = { maxTokens, signal, apiKey, headers };
	if (model.reasoning && thinkingLevel && thinkingLevel !== "off") {
		options.reasoning = thinkingLevel;
	}
	return options;
}

async function completeSummarization(
	model: Model<any>,
	context: Context,
	options: SimpleStreamOptions,
	streamFn?: StreamFn,
): Promise<AssistantMessage> {
	if (!streamFn) {
		return completeSimple(model, context, options);
	}
	const stream = await streamFn(model, context, options);
	return stream.result();
}

/**
 * Token ceiling for a summarization LLM call: a fraction of the reserve, clamped
 * to the model's own output limit (unbounded when the model reports none).
 */
function summarizationMaxTokens(model: Model<any>, reserveTokens: number, fraction: number): number {
	return Math.min(
		Math.floor(fraction * reserveTokens),
		model.maxTokens > 0 ? model.maxTokens : Number.POSITIVE_INFINITY,
	);
}

/**
 * Generate a summary of the conversation using the LLM.
 * If previousSummary is provided, uses the update prompt to merge.
 */
export async function generateSummary(
	currentMessages: AgentMessage[],
	model: Model<any>,
	reserveTokens: number,
	apiKey: string | undefined,
	headers?: Record<string, string>,
	signal?: AbortSignal,
	customInstructions?: string,
	previousSummary?: string,
	thinkingLevel?: ThinkingLevel,
	streamFn?: StreamFn,
	serialized?: SerializedWindow,
): Promise<string> {
	const maxTokens = summarizationMaxTokens(model, reserveTokens, 0.8);

	// Use update prompt if we have a previous summary, otherwise initial prompt
	const useJson = summarizationUsesJsonOutput();
	let basePrompt = previousSummary
		? useJson
			? UPDATE_SUMMARIZATION_JSON_PROMPT
			: UPDATE_SUMMARIZATION_PROMPT
		: useJson
			? SUMMARIZATION_JSON_PROMPT
			: SUMMARIZATION_PROMPT;
	if (customInstructions) {
		basePrompt = `${basePrompt}\n\nAdditional focus: ${customInstructions}`;
	}

	// Serialize conversation so the model doesn't try to continue it.
	// Convert to LLM messages first (handles custom types like bashExecution, custom, etc.)
	// A precomputed SerializedWindow (from compact()) shares this work with the
	// verification pass; the full-prose serialization is not memoized (no reuser).
	const useDeltaSerialization =
		previousSummary !== undefined &&
		previousSummary.length > 0 &&
		!isTruthyEnvFlag(process.env.PIT_NO_DELTA_SUMMARIZATION);
	const conversationText = useDeltaSerialization
		? (serialized?.delta ?? serializeConversationDelta(convertToLlm(currentMessages)))
		: serializeConversation(serialized?.llm ?? convertToLlm(currentMessages));
	const conversationTag = useDeltaSerialization ? "conversation-delta" : "conversation";

	// Build the prompt with conversation wrapped in tags
	let promptText = `<${conversationTag}>\n${conversationText}\n</${conversationTag}>\n\n`;
	if (previousSummary) {
		promptText += `<previous-summary>\n${previousSummary}\n</previous-summary>\n\n`;
	}
	promptText += basePrompt;

	return runSummarization(
		model,
		promptText,
		maxTokens,
		apiKey,
		headers,
		signal,
		thinkingLevel,
		streamFn,
		"Summarization failed",
	);
}

function extractTextFromResponse(response: AssistantMessage): string {
	return response.content
		.filter((c): c is { type: "text"; text: string } => c.type === "text")
		.map((c) => c.text)
		.join("\n");
}

/**
 * Discriminated outcome of a summarization pass: 'aborted' and 'error' are kept
 * distinct for callers (e.g. branch summarization) that report them differently.
 * The 'aborted' variant still carries any partial `text` the model emitted before
 * cancellation, so compaction's throw-on-error wrapper can return it unchanged
 * (the previous code path extracted text regardless of an aborted stopReason).
 */
export type SummarizationOutcome =
	| { status: "ok"; text: string }
	| { status: "aborted"; text: string }
	| { status: "error"; errorMessage: string | undefined };

/**
 * Run an LLM summarization pass: wrap the prompt in a single user message,
 * complete it (stream-aware when a streamFn is given, reasoning-aware when the
 * model supports it and a thinkingLevel is set), and return a discriminated
 * outcome. Shared by compaction (`runSummarization`, which throws on error and
 * ignores the aborted/ok distinction) and branch summarization (which maps each
 * status to a distinct result field).
 */
export async function runSummarizationWithStatus(
	model: Model<any>,
	promptText: string,
	maxTokens: number,
	apiKey: string | undefined,
	headers: Record<string, string> | undefined,
	signal: AbortSignal | undefined,
	thinkingLevel: ThinkingLevel | undefined,
	streamFn: StreamFn | undefined,
): Promise<SummarizationOutcome> {
	const summarizationMessages = [
		{
			role: "user" as const,
			content: [{ type: "text" as const, text: promptText }],
			timestamp: Date.now(),
		},
	];

	const response = await completeSummarization(
		model,
		{ systemPrompt: SUMMARIZATION_SYSTEM_PROMPT, messages: summarizationMessages },
		createSummarizationOptions(model, maxTokens, apiKey, headers, signal, thinkingLevel),
		streamFn,
	);

	if (response.stopReason === "aborted") {
		return { status: "aborted", text: extractTextFromResponse(response) };
	}
	if (response.stopReason === "error") {
		// Raw message (may be empty); each caller applies its own fallback label.
		return { status: "error", errorMessage: response.errorMessage };
	}
	return { status: "ok", text: extractTextFromResponse(response) };
}

/**
 * Run an LLM summarization pass and return the text, throwing on error with the
 * given label. Thin wrapper over {@link runSummarizationWithStatus} preserving
 * the original behavior: aborted responses fall through to text extraction
 * (stopReason 'aborted' yields no text blocks → empty string), only 'error'
 * throws.
 */
async function runSummarization(
	model: Model<any>,
	promptText: string,
	maxTokens: number,
	apiKey: string | undefined,
	headers: Record<string, string> | undefined,
	signal: AbortSignal | undefined,
	thinkingLevel: ThinkingLevel | undefined,
	streamFn: StreamFn | undefined,
	errorLabel: string,
): Promise<string> {
	const outcome = await runSummarizationWithStatus(
		model,
		promptText,
		maxTokens,
		apiKey,
		headers,
		signal,
		thinkingLevel,
		streamFn,
	);
	if (outcome.status === "error") {
		throw new Error(`${errorLabel}: ${outcome.errorMessage || "Unknown error"}`);
	}
	// Both 'ok' and 'aborted' carry text; the original extracted text regardless of an aborted stopReason.
	const raw = outcome.text;
	return summarizationUsesJsonOutput() ? normalizeStructuredSummaryOutput(raw) : raw;
}

// ============================================================================
// Self-correction verification
// ============================================================================

const VERIFICATION_PROMPT = `Critically evaluate the context summary below against the source conversation provided in <conversation-delta> above this prompt. Did you omit any of the following from that source?
- Exact file paths or line numbers
- Error messages or exception types
- Function/variable names
- User constraints or preferences
- Key decisions and their rationale

The <conversation-delta> block is a compact JSON array of events:
[{"k":"u","t":"user text"},{"k":"a","t":"assistant text"},{"k":"c","n":"toolName","a":{args}},{"k":"r","n":"toolName","t":"result excerpt","e":1}]
Keys: u=user, a=assistant, c=tool call, r=tool result (e=1 only on error). Thinking is omitted.

Compare the summary against that source. If anything material is missing or imprecise, produce a FINAL improved summary using the same format.

STRICT ANTI-FABRICATION RULE: only add facts that appear VERBATIM (or as a clear paraphrase) in the <conversation-delta> source. NEVER add file paths, function names, error messages, or claims that are not present in the source — that is fabrication, not correction. If nothing is missing, repeat the summary exactly as-is.

<summary>
{SUMMARY}
</summary>`;

/**
 * Head/tail char budgets for the verification source excerpt. Large windows
 * would otherwise blow the verifier request; the head keeps the earliest
 * turns (goal, constraints, first decisions) and the tail keeps the most
 * recent (current work, latest errors) — the two regions most likely to be
 * silently dropped from a summary.
 */
const VERIFY_SOURCE_HEAD_BUDGET = 24_000;
const VERIFY_SOURCE_TAIL_BUDGET = 8_000;

/**
 * Build a bounded, compact serialization of the compacted window for the
 * self-correction verification pass. The verifier MUST see the source it is
 * checking the summary against — without it the pass can only fabricate
 * plausible additions, never detect real omissions (the prior prompt carried
 * the summary alone).
 *
 * Uses {@link serializeConversationDelta} (compact JSON, thinking omitted) over
 * the convertToLlm form of the (already pruned) messages, then bounds the
 * result with a head+tail excerpt so a huge window cannot blow the verifier
 * request. Turn-prefix messages (split-turn) are prepended to the main window
 * so the verifier sees the full compacted span in source order.
 */
export function buildVerificationSource(
	messagesToSummarize: AgentMessage[],
	turnPrefixMessages: AgentMessage[],
	mainWindow?: SerializedWindow,
	prefixWindow?: SerializedWindow,
): string {
	const main = (mainWindow ?? createSerializedWindow(messagesToSummarize)).delta;
	const prefix =
		turnPrefixMessages.length > 0 ? (prefixWindow ?? createSerializedWindow(turnPrefixMessages)).delta : "";
	const combined = prefix ? `${prefix}\n${main}` : main;
	if (combined.length <= VERIFY_SOURCE_HEAD_BUDGET + VERIFY_SOURCE_TAIL_BUDGET) {
		return combined;
	}
	return headTailExcerptShared(combined, {
		headBudget: VERIFY_SOURCE_HEAD_BUDGET,
		tailBudget: VERIFY_SOURCE_TAIL_BUDGET,
		snapWindow: 400,
		marker: (elidedChars) => `[… ${elidedChars} characters elided …]`,
	});
}

/**
 * Below this many summarized-input tokens, skip the self-correction pass. The
 * verification is a SECOND full LLM call per compaction; on small or incremental
 * compactions there is little content to omit, so the omission risk it guards
 * against is low and the cost is not justified. Large first-time compactions
 * (where dropping a file path / error / decision is likely) still verify.
 */
const VERIFY_MIN_INPUT_TOKENS = 25_000;

/**
 * Sum content-aware token estimates across a message list — a PURE estimate
 * that never consults assistant `usage`. After a compaction the kept assistant
 * messages still carry their pre-compaction usage, so the usage-based
 * estimateContextTokens reads as if nothing was compacted; callers re-checking
 * post-compaction pressure must use this instead.
 */
export function sumMessageTokens(messages: AgentMessage[]): number {
	let total = 0;
	for (const message of messages) total += estimateTokens(message);
	return total;
}

/**
 * Run a self-correction pass on a generated summary. A second LLM call
 * evaluates the summary for omissions against the source conversation and
 * produces a corrected version. The {@link source} argument MUST be a
 * serialization of the compacted window (see {@link buildVerificationSource});
 * without it the pass can only fabricate additions, never detect omissions.
 * Falls back to the original if the corrected version inflates token count
 * by more than 10%.
 */
async function verifySummary(
	summary: string,
	source: string,
	model: Model<any>,
	maxTokens: number,
	apiKey: string | undefined,
	headers: Record<string, string> | undefined,
	signal: AbortSignal | undefined,
	thinkingLevel: ThinkingLevel | undefined,
	streamFn?: StreamFn,
): Promise<string> {
	const promptText = `<conversation-delta>\n${source}\n</conversation-delta>\n\n${VERIFICATION_PROMPT.replace(
		"{SUMMARY}",
		summary,
	)}`;
	const messages = [
		{
			role: "user" as const,
			content: [{ type: "text" as const, text: promptText }],
			timestamp: Date.now(),
		},
	];

	try {
		const response = await completeSummarization(
			model,
			{ systemPrompt: SUMMARIZATION_SYSTEM_PROMPT, messages },
			createSummarizationOptions(model, maxTokens, apiKey, headers, signal, thinkingLevel),
			streamFn,
		);

		if (response.stopReason === "error") {
			return summary;
		}

		const corrected = extractTextFromResponse(response);
		if (!corrected.trim()) return summary;

		const originalTokens = Math.ceil(summary.length / 4);
		const correctedTokens = Math.ceil(corrected.length / 4);
		if (correctedTokens > originalTokens * 1.1) {
			return summary;
		}

		return corrected;
	} catch {
		return summary;
	}
}

// ============================================================================
// Compaction Preparation (for extensions)
// ============================================================================

export interface CompactionPreparation {
	/** UUID of first entry to keep */
	firstKeptEntryId: string;
	/** Messages that will be summarized and discarded */
	messagesToSummarize: AgentMessage[];
	/** Messages that will be turned into turn prefix summary (if splitting) */
	turnPrefixMessages: AgentMessage[];
	/** Whether this is a split turn (cut point in middle of turn) */
	isSplitTurn: boolean;
	tokensBefore: number;
	/** Summary from previous compaction, for iterative update */
	previousSummary?: string;
	/** File operations extracted from messagesToSummarize */
	fileOps: FileOperations;
	/** Compaction settions from settings.jsonl	*/
	settings: CompactionSettings;
	/** Working directory — used to strip path prefixes in summaries, saving tokens. */
	cwd?: string;
}

export function prepareCompaction(
	pathEntries: SessionEntry[],
	settings: CompactionSettings,
	contextWindow?: number,
	allowLatestCompaction = false,
	knownContextTokens?: number,
	keepRecentTokensOverride?: number,
): CompactionPreparation | undefined {
	if (!allowLatestCompaction && pathEntries.length > 0 && pathEntries[pathEntries.length - 1].type === "compaction") {
		return undefined;
	}

	let prevCompactionIndex = -1;
	for (let i = pathEntries.length - 1; i >= 0; i--) {
		if (pathEntries[i].type === "compaction") {
			prevCompactionIndex = i;
			break;
		}
	}

	let previousSummary: string | undefined;
	let boundaryStart = 0;
	if (prevCompactionIndex >= 0) {
		const prevCompaction = pathEntries[prevCompactionIndex] as CompactionEntry;
		previousSummary = prevCompaction.summary;
		const firstKeptEntryIndex = pathEntries.findIndex((entry) => entry.id === prevCompaction.firstKeptEntryId);
		boundaryStart = firstKeptEntryIndex >= 0 ? firstKeptEntryIndex : prevCompactionIndex + 1;
	}
	const boundaryEnd = pathEntries.length;

	// tokensBefore is telemetry (CompactionEntry/compaction summary metadata).
	// When the caller already holds a live-context estimate, reuse it instead of
	// rebuilding the whole session context (an O(n) message materialization) just
	// to re-derive the same number. The live estimate can run slightly lower than
	// a rebuild when live pruning already elided old outputs — that is the more
	// accurate wire-side figure anyway.
	const tokensBefore = knownContextTokens ?? estimateContextTokens(buildSessionContext(pathEntries).messages).tokens;

	// An explicit override (adaptiveKeepRecentTokens under pressure) wins over the
	// window-scaled default so a single pass can cut deep enough on small windows.
	const keepRecentTokens =
		keepRecentTokensOverride ?? effectiveKeepRecentTokens(settings.keepRecentTokens, contextWindow);
	const cutPoint = findCutPoint(pathEntries, boundaryStart, boundaryEnd, keepRecentTokens);

	// Get UUID of first kept entry
	const firstKeptEntry = pathEntries[cutPoint.firstKeptEntryIndex];
	if (!firstKeptEntry?.id) {
		return undefined; // Session needs migration
	}
	const firstKeptEntryId = firstKeptEntry.id;

	const historyEnd = cutPoint.isSplitTurn ? cutPoint.turnStartIndex : cutPoint.firstKeptEntryIndex;

	// Messages to summarize (will be discarded after summary)
	const messagesToSummarize: AgentMessage[] = [];
	for (let i = boundaryStart; i < historyEnd; i++) {
		const msg = getMessageFromEntryForCompaction(pathEntries[i]);
		if (msg) messagesToSummarize.push(msg);
	}

	// Messages for turn prefix summary (if splitting a turn)
	const turnPrefixMessages: AgentMessage[] = [];
	if (cutPoint.isSplitTurn) {
		for (let i = cutPoint.turnStartIndex; i < cutPoint.firstKeptEntryIndex; i++) {
			const msg = getMessageFromEntryForCompaction(pathEntries[i]);
			if (msg) turnPrefixMessages.push(msg);
		}
	}

	// Extract file operations from messages and previous compaction
	const fileOps = extractFileOperations(messagesToSummarize, pathEntries, prevCompactionIndex);

	// Also extract file ops from turn prefix if splitting
	if (cutPoint.isSplitTurn) {
		for (const msg of turnPrefixMessages) {
			extractFileOpsFromMessage(msg, fileOps);
		}
	}

	return {
		firstKeptEntryId,
		messagesToSummarize,
		turnPrefixMessages,
		isSplitTurn: cutPoint.isSplitTurn,
		tokensBefore,
		previousSummary,
		fileOps,
		settings,
	};
}

// ============================================================================
// Main compaction function
// ============================================================================

const TURN_PREFIX_SUMMARIZATION_PROMPT = `This is the PREFIX of a turn that was too large to keep. The SUFFIX (recent work) is retained.

Summarize the prefix to provide context for the retained suffix:

## Original Request
[What did the user ask for in this turn?]

## Early Progress
- [Key decisions and work done in the prefix]

## Context for Suffix
- [Information needed to understand the retained recent work]

Be concise. Focus on what's needed to understand the kept suffix.`;

/**
 * Below this many chars of explanatory prose in the compacted window, skip the
 * summarization LLM entirely and emit only the deterministic structural frame
 * (file operations + digests). A window that is a pure burst of tool I/O —
 * back-to-back reads/greps/edits with no assistant narration and no user prose —
 * has nothing for the summarizer to add over the structural lists, so the LLM
 * call (and its self-correction pass) is wasted latency and tokens. The bar is
 * deliberately small: ANY non-trivial prose tips the window back to the LLM path
 * so context quality is never degraded. Forced always-LLM via
 * PIT_NO_STRUCTURAL_COMPACTION=1.
 */
const STRUCTURAL_ONLY_PROSE_THRESHOLD = 200;

/**
 * Count chars of explanatory prose in the compacted window: assistant `text`
 * blocks, user free-text, and non-relay `custom` (extension-injected) text —
 * each as string content or `text`-type content blocks. Custom text IS counted
 * because convertToLlm relays it to the summarizer as a user message (a relay
 * custom — customType === MESSAGE_RELAY_CUSTOM_TYPE — is excluded, since
 * convertToLlm drops it, so it never reaches the model). Deliberately EXCLUDES
 * tool calls, tool results, thinking, bash output and the structured fields of
 * system/branch/compaction messages — those are mechanical and already captured
 * deterministically by the structural frame. This measures only what a
 * summarizer could add over the structural lists.
 */
function measureProseChars(messages: AgentMessage[]): number {
	let prose = 0;
	for (const message of messages) {
		if (message.role === "assistant") {
			for (const block of message.content) {
				if (block.type === "text") prose += block.text.length;
			}
			continue;
		}
		if (message.role === "user") {
			const content = (message as { content: string | Array<{ type: string; text?: string }> }).content;
			if (typeof content === "string") {
				prose += content.length;
			} else if (Array.isArray(content)) {
				for (const block of content) {
					if (block.type === "text" && block.text) prose += block.text.length;
				}
			}
			continue;
		}
		if (message.role === "custom") {
			// Relay custom messages are display-only — convertToLlm drops them, so
			// they carry no prose the summarizer would ever see.
			if (message.customType === MESSAGE_RELAY_CUSTOM_TYPE) continue;
			const content = message.content;
			if (typeof content === "string") {
				prose += content.length;
			} else if (Array.isArray(content)) {
				for (const block of content) {
					if (block.type === "text" && block.text) prose += block.text.length;
				}
			}
		}
	}
	return prose;
}

/**
 * True when the window has so little explanatory prose that the structural frame
 * already captures everything a summary could. Gated off by
 * PIT_NO_STRUCTURAL_COMPACTION=1 (forces the always-LLM path). A previousSummary
 * present means this is an INCREMENTAL compaction whose prose lives in the prior
 * summary, not the window — never collapse to structural-only there, or that
 * prose would be silently dropped.
 */
function shouldUseStructuralOnly(
	messagesToSummarize: AgentMessage[],
	turnPrefixMessages: AgentMessage[],
	previousSummary: string | undefined,
): boolean {
	if (isTruthyEnvFlag(process.env.PIT_NO_STRUCTURAL_COMPACTION)) return false;
	if (previousSummary) return false;
	const prose = measureProseChars(messagesToSummarize) + measureProseChars(turnPrefixMessages);
	return prose < STRUCTURAL_ONLY_PROSE_THRESHOLD;
}

/** Deterministic header emitted in place of an LLM summary for tool-only windows. */
const STRUCTURAL_ONLY_HEADER = `## Goal
(No explanatory prose in this window — mechanical tool activity only. See operations below.)

## Progress
- Tool operations on the listed files/searches/commands were applied. The retained recent context continues the work.`;

/**
 * Living-repo-map preseed + buildFileDigests over the touched files. Never
 * called with an empty `digestPaths`. Extracted from compact() so the digest
 * I/O (disk reads + symbol parse) can run CONCURRENTLY with the summarization
 * LLM calls — the inputs depend only on the preparation's fileOps, not on the
 * summary text.
 */
async function collectFileDigests(
	digestPaths: string[],
	cwd: string | undefined,
	signal: AbortSignal | undefined,
): Promise<Record<string, string>> {
	// Living repo map: a git-anchored incremental symbol index. Project it onto the
	// touched files and pass as a pre-seed so anything it already indexed is NOT
	// re-read/re-parsed here — the digest becomes a cache READ. Fail-open: any
	// failure leaves preSeed undefined and buildFileDigests rebuilds from disk
	// (output is identical; only the cost differs).
	let preSeed: Record<string, string> | undefined;
	try {
		const { map } = await getLivingRepoMap(cwd ?? ".");
		const seed: Record<string, string> = {};
		const relKeys = digestPaths.map((p) =>
			relative(cwd ?? ".", isAbsolute(p) ? p : resolve(cwd ?? ".", p))
				.split("\\")
				.join("/"),
		);
		// Filter the living-repo-map projection to just the touched files so we don't
		// materialize a digest string for every indexed file in the repo. The lookup
		// keys (and resulting seed) are identical; only the intermediate dict shrinks.
		const mapDigests = livingRepoMapToDigests(map, relKeys);
		for (let i = 0; i < digestPaths.length; i++) {
			const symbols = mapDigests[relKeys[i]];
			if (symbols !== undefined) seed[digestPaths[i]] = symbols;
		}
		preSeed = seed;
	} catch {
		preSeed = undefined;
	}
	return buildFileDigests(
		digestPaths,
		async (p) => {
			try {
				const fullPath = isAbsolute(p) ? p : resolve(cwd ?? ".", p);
				const st = await stat(fullPath);
				if (st.size > MAX_DIGEST_BYTES) return null;
				return await readFile(fullPath, { encoding: "utf8", signal });
			} catch {
				return null;
			}
		},
		signal,
		preSeed,
	);
}

/**
 * Generate summaries for compaction using prepared data.
 * Returns CompactionResult - SessionManager adds uuid/parentUuid when saving.
 *
 * @param preparation - Pre-calculated preparation from prepareCompaction()
 * @param customInstructions - Optional custom focus for the summary
 */
export async function compact(
	preparation: CompactionPreparation,
	model: Model<any>,
	apiKey: string | undefined,
	headers?: Record<string, string>,
	customInstructions?: string,
	signal?: AbortSignal,
	thinkingLevel?: ThinkingLevel,
	streamFn?: StreamFn,
): Promise<CompactionResult> {
	const {
		firstKeptEntryId,
		messagesToSummarize: messagesToSummarizeRaw,
		turnPrefixMessages: turnPrefixMessagesRaw,
		isSplitTurn,
		tokensBefore,
		previousSummary,
		fileOps,
		settings,
		cwd,
	} = preparation;

	// Clone toolResult messages BEFORE pruning. getMessageFromEntry returns
	// entry.message by reference for 'message' entries, so without this the prune
	// would elide tool results inside the LIVE session context; an aborted
	// summarization would then leave them elided with no restore. Cloning makes the
	// prune operate on throw-away copies — happy-path output is unchanged.
	const messagesToSummarize = cloneToolResultMessagesForPrune(messagesToSummarizeRaw);
	const turnPrefixMessages = isSplitTurn
		? cloneToolResultMessagesForPrune(turnPrefixMessagesRaw)
		: turnPrefixMessagesRaw;

	// Pre-prune large tool outputs before sending to summarizer. Scale the
	// threshold to the window: tighter windows prune more aggressively (capped at
	// the default so large windows are unchanged).
	const pruneThreshold = Math.min(
		PRUNE_TOKEN_THRESHOLD,
		Math.max(4_000, Math.floor((model.contextWindow || 200_000) * 0.1)),
	);
	pruneOldToolOutputs(messagesToSummarize, pruneThreshold);
	if (isSplitTurn) {
		pruneOldToolOutputs(turnPrefixMessages, pruneThreshold);
	}

	// Serialized views shared by the summarizer and the verification pass.
	// Created AFTER the prune above — the prune rewrites block.text in place, and
	// the memo must capture the pruned (final) window. One window per message
	// list; never share across main/prefix.
	const mainWindow = createSerializedWindow(messagesToSummarize);
	const prefixWindow = isSplitTurn ? createSerializedWindow(turnPrefixMessages) : undefined;

	// File digests kick off NOW so the disk reads + symbol parsing overlap the
	// summarization LLM calls below; the result is awaited only after the verify
	// pass. Reading at compaction start instead of after the LLM round-trips is
	// equivalent: the session is disconnected/idle during compaction, so no tool
	// writes land in between.
	const lists = computeOperationLists(fileOps, cwd);
	// Modified files are the artifact trail that summary prose silently drops, so
	// they get digests by default; read-only files stay behind PIT_FILE_DIGESTS to
	// bound prefix growth. The lists are disjoint (read AND modified surfaces only
	// in modifiedFiles), so concatenating needs no dedup.
	const digestPaths = isTruthyEnvFlag(process.env.PIT_FILE_DIGESTS)
		? [...lists.modifiedFiles, ...lists.readFiles]
		: lists.modifiedFiles;
	const digestsPromise = digestPaths.length > 0 ? collectFileDigests(digestPaths, cwd, signal) : undefined;
	// No-op branch so a summarization failure below cannot surface an unhandled
	// rejection from the in-flight digests; the real `await digestsPromise` after
	// the verify pass still observes (and rethrows) any digest error.
	digestsPromise?.catch(() => {});

	// Generate summaries (can be parallel if both needed) and merge into one
	let summary: string;

	// Structural-only fast path: when the compacted window is a pure burst of tool
	// I/O with no explanatory prose, the deterministic operation lists + digests
	// (appended below) already capture everything a summary could. Skip the
	// summarizer LLM and its self-correction pass. Disabled by
	// PIT_NO_STRUCTURAL_COMPACTION=1 and never taken for incremental compactions
	// (see shouldUseStructuralOnly).
	const structuralOnly = shouldUseStructuralOnly(messagesToSummarize, turnPrefixMessages, previousSummary);
	if (structuralOnly) {
		summary = STRUCTURAL_ONLY_HEADER;
	} else if (isSplitTurn && turnPrefixMessages.length > 0) {
		const [historyResult, turnPrefixResult] = await Promise.all([
			messagesToSummarize.length > 0
				? generateSummary(
						messagesToSummarize,
						model,
						settings.reserveTokens,
						apiKey,
						headers,
						signal,
						customInstructions,
						previousSummary,
						thinkingLevel,
						streamFn,
						mainWindow,
					)
				: Promise.resolve("No prior history."),
			generateTurnPrefixSummary(
				turnPrefixMessages,
				model,
				settings.reserveTokens,
				apiKey,
				headers,
				signal,
				thinkingLevel,
				streamFn,
				prefixWindow,
			),
		]);
		summary = `${historyResult}\n\n---\n\n**Turn Context (split turn):**\n\n${turnPrefixResult}`;
	} else {
		summary = await generateSummary(
			messagesToSummarize,
			model,
			settings.reserveTokens,
			apiKey,
			headers,
			signal,
			customInstructions,
			previousSummary,
			thinkingLevel,
			streamFn,
			mainWindow,
		);
	}

	// Self-correction: verify summary for omitted details. Gated by input size —
	// small/incremental compactions skip the second LLM call (low omission risk).
	const verifyInputTokens =
		sumMessageTokens(messagesToSummarize) + (isSplitTurn ? sumMessageTokens(turnPrefixMessages) : 0);
	if (!structuralOnly && settings.selfCorrection !== false && verifyInputTokens >= VERIFY_MIN_INPUT_TOKENS) {
		const maxTokens = summarizationMaxTokens(model, settings.reserveTokens, 0.8);
		const verifySource = buildVerificationSource(
			messagesToSummarize,
			isSplitTurn ? turnPrefixMessages : [],
			mainWindow,
			isSplitTurn ? prefixWindow : undefined,
		);
		summary = await verifySummary(
			summary,
			verifySource,
			model,
			maxTokens,
			apiKey,
			headers,
			signal,
			thinkingLevel,
			streamFn,
		);
	}

	if (!structuralOnly && !isTruthyEnvFlag(process.env.PIT_NO_COMPACT_SUMMARY_OUTPUT)) {
		summary = trimSummaryProseAgainstOperations(summary, lists);
	}
	// Deterministic grounding: annotate path tokens in the prose that are neither
	// in the operation lists nor on disk with `(unverified)`. Runs before the
	// structural frame (correct by construction) is appended, and is skipped for
	// the structural-only header (no prose to ground). Zero-LLM, every provider.
	if (!structuralOnly && !isTruthyEnvFlag(process.env.PIT_NO_SUMMARY_GROUNDING)) {
		summary = groundSummaryPaths(summary, lists, cwd).summary;
	}
	summary += formatFileOperations(lists);

	if (!firstKeptEntryId) {
		throw new Error("First kept entry has no UUID - session may need migration");
	}

	const details: CompactionDetails = {
		readFiles: lists.readFiles,
		modifiedFiles: lists.modifiedFiles,
	};
	if (lists.searches.length > 0) details.searches = lists.searches;
	if (lists.shellCmds.length > 0) details.shellCmds = lists.shellCmds;
	if (lists.mcpCalls.length > 0) details.mcpCalls = lists.mcpCalls;

	// File digests: a symbol outline of touched files at compaction time, so the
	// post-compaction model recalls the CURRENT shape of what it worked on without a
	// re-read. The collection was kicked off before the summarization LLM calls
	// (see digestsPromise above); only the await lands here.
	if (digestsPromise) {
		const digests = await digestsPromise;
		if (Object.keys(digests).length > 0) {
			details.fileDigests = digests;
			summary += `\n${formatFileDigests(digests)}`;
		}
	}

	// recall_history footer: announce that the summarized window is recoverable
	// on demand. The tool answers gracefully when there is no compacted history,
	// so the footer is unconditional (per default-native policy). Skipped for the
	// structural-only header (no prose window was summarized) and on opt-out.
	if (!structuralOnly && !isTruthyEnvFlag(process.env.PIT_NO_RECALL_HISTORY)) {
		summary += "\n[Details from the summarized window are retrievable via recall_history({ query }).]";
	}

	return {
		summary,
		firstKeptEntryId,
		tokensBefore,
		details,
	};
}

/**
 * Generate a summary for a turn prefix (when splitting a turn).
 */
async function generateTurnPrefixSummary(
	messages: AgentMessage[],
	model: Model<any>,
	reserveTokens: number,
	apiKey: string | undefined,
	headers?: Record<string, string>,
	signal?: AbortSignal,
	thinkingLevel?: ThinkingLevel,
	streamFn?: StreamFn,
	serialized?: SerializedWindow,
): Promise<string> {
	const maxTokens = summarizationMaxTokens(model, reserveTokens, 0.5); // Smaller budget for turn prefix
	const llmMessages = serialized?.llm ?? convertToLlm(messages);
	const conversationText = serializeConversation(llmMessages);
	const promptText = `<conversation>\n${conversationText}\n</conversation>\n\n${TURN_PREFIX_SUMMARIZATION_PROMPT}`;

	return runSummarization(
		model,
		promptText,
		maxTokens,
		apiKey,
		headers,
		signal,
		thinkingLevel,
		streamFn,
		"Turn prefix summarization failed",
	);
}
