/**
 * Context compaction for long sessions.
 *
 * Pure functions for compaction logic. The session manager handles I/O,
 * and after compaction the session is reloaded.
 */

import { readFile, stat } from "node:fs/promises";
import { isAbsolute, relative, resolve } from "node:path";
import type { AgentMessage, StreamFn, ThinkingLevel } from "@pit/agent-core";
import type { AssistantMessage, Model, Usage } from "@pit/ai";
import { CHARS_PER_TOKEN_DENSE, CHARS_PER_TOKEN_PROSE, recordTokenEstimateSample, tokenEstimateFactor } from "@pit/ai";
import { isTruthyEnvFlag } from "../../utils/env-flags.ts";
import { convertToLlm } from "../messages.ts";
import { MESSAGE_RELAY_CUSTOM_TYPE } from "../messaging/types.ts";
import { getLivingRepoMap, livingRepoMapToDigests } from "../repo-map/living-index.ts";
import { buildSessionContext, type CompactionEntry, type SessionEntry } from "../session-manager.ts";
import type { CacheAwareGeneration } from "./cache-aware.ts";
import { buildFileDigests, formatFileDigests, MAX_DIGEST_BYTES } from "./file-digests.ts";
import { estimateTextTokens, estimateTokens } from "./message-tokens.ts";
import { cloneToolResultMessagesForPrune, PRUNE_TOKEN_THRESHOLD, pruneOldToolOutputs } from "./prune.ts";
import {
	buildVerificationSource,
	createSerializedWindow,
	generateSummary,
	runSummarization,
	type SerializedWindow,
	sumMessageTokens,
	summarizationMaxTokens,
	VERIFY_MIN_INPUT_TOKENS,
	verifySummary,
} from "./summarize.ts";
import { groundSummaryPaths } from "./summary-grounding.ts";
import {
	computeOperationLists,
	createFileOps,
	extractFileOpsFromMessage,
	type FileOperations,
	formatFileOperations,
	getMessageFromEntry as getMessageFromEntryShared,
	mergeSummaryDetailsIntoFileOps,
	type SummaryDetails,
	serializeConversation,
	trimSummaryProseAgainstOperations,
} from "./utils.ts";

export * from "./message-tokens.ts";
export * from "./prune.ts";
export * from "./summarize.ts";

// ============================================================================
// File Operation Tracking
// ============================================================================

/** Details stored in CompactionEntry.details for structured summary frame.
 *
 * Older sessions only carry `readFiles` and `modifiedFiles`. The remaining
 * fields are populated by the structured summary frame and are loaded
 * defensively when present. Extends the shared {@link SummaryDetails} (the same
 * operation lists branch summarization persists) with compaction-only digests.
 */
export interface CompactionDetails extends SummaryDetails {
	/** path -> top symbols, derived at compaction time. Lossy guide; re-read for current content. */
	fileDigests?: Record<string, string>;
}

/**
 * Extract file operations from messages and previous compaction entries.
 */
function extractFileOperations(
	messages: AgentMessage[],
	entries: SessionEntry[],
	prevCompactionIndex: number,
): FileOperations {
	const fileOps = createFileOps();

	// Collect from previous compaction's details (if pi-generated)
	if (prevCompactionIndex >= 0) {
		const prevCompaction = entries[prevCompactionIndex] as CompactionEntry;
		if (!prevCompaction.fromHook && prevCompaction.details) {
			// fromHook field kept for session file compatibility
			mergeSummaryDetailsIntoFileOps(prevCompaction.details as CompactionDetails, fileOps);
		}
	}

	// Extract from tool calls in messages
	for (const msg of messages) {
		extractFileOpsFromMessage(msg, fileOps);
	}

	return fileOps;
}

// ============================================================================
// Message Extraction
// ============================================================================

/**
 * Extract AgentMessage from an entry, skipping `compaction` entries (their
 * summary is regenerated by the in-progress compaction, so it must not be
 * re-summarized). Delegates to the shared {@link getMessageFromEntryShared}.
 *
 * NOTE: for `type === "message"` this returns `entry.message` BY REFERENCE — see
 * the shared function's docs; callers that mutate must clone first (see
 * `cloneToolResultMessagesForPrune`).
 */
function getMessageFromEntryForCompaction(entry: SessionEntry): AgentMessage | undefined {
	return getMessageFromEntryShared(entry, { skipCompaction: true });
}

/** Result from compact() - SessionManager adds uuid/parentUuid when saving */
export interface CompactionResult<T = unknown> {
	summary: string;
	firstKeptEntryId: string;
	tokensBefore: number;
	/**
	 * Live context size once the summary replaced the folded span — the OTHER half
	 * of the only number that says whether a compaction did its job. Runtime-only
	 * (deliberately NOT persisted on the CompactionEntry, which would be a session
	 * file-format change): a freshly-run compaction reports the delta, and a
	 * transcript reloaded from disk degrades to the tokensBefore-only headline.
	 */
	tokensAfter?: number;
	/** Extension-specific data (e.g., ArtifactIndex, version markers for structured compaction) */
	details?: T;
}

// ============================================================================
// Types
// ============================================================================

export interface CompactionSettings {
	enabled: boolean;
	reserveTokens: number;
	keepRecentTokens: number;
	/** Enable self-correction verification pass after summarization. Default: true */
	selfCorrection?: boolean;
}

export const DEFAULT_COMPACTION_SETTINGS: CompactionSettings = {
	enabled: true,
	reserveTokens: 16384,
	keepRecentTokens: 20000,
	selfCorrection: true,
};

// ============================================================================
// Token calculation
// ============================================================================

/**
 * Calculate total context tokens from usage.
 * Uses the native totalTokens field when available, falls back to computing from components.
 */
export function calculateContextTokens(usage: Usage): number {
	return usage.totalTokens || usage.input + usage.output + usage.cacheRead + usage.cacheWrite;
}

/**
 * Get usage from an assistant message if available.
 * Skips aborted and error messages as they don't have valid usage data.
 */
function getAssistantUsage(msg: AgentMessage): Usage | undefined {
	if (msg.role === "assistant" && "usage" in msg) {
		const assistantMsg = msg as AssistantMessage;
		if (assistantMsg.stopReason !== "aborted" && assistantMsg.stopReason !== "error" && assistantMsg.usage) {
			return assistantMsg.usage;
		}
	}
	return undefined;
}

/**
 * Find the last non-aborted assistant message usage from session entries.
 */
export function getLastAssistantUsage(entries: SessionEntry[]): Usage | undefined {
	for (let i = entries.length - 1; i >= 0; i--) {
		const entry = entries[i];
		if (entry.type === "message") {
			const usage = getAssistantUsage(entry.message);
			if (usage) return usage;
		}
	}
	return undefined;
}

export interface ContextUsageEstimate {
	tokens: number;
	usageTokens: number;
	trailingTokens: number;
	lastUsageIndex: number | null;
}

/** Minimal tool surface for wire-size estimation (name + API schema). */
export interface WireToolSurface {
	name: string;
	description: string;
	parameters: unknown;
	/**
	 * Hand-written one-sentence summary of the tool, when it has one. Carried
	 * alongside `description` only so `compactWireToolSurface` can prefer it over
	 * a mechanically truncated first line (T01); it is folded INTO `description`
	 * on the compacted surface and never counted twice by
	 * {@link estimateToolSurfaceTokens}.
	 */
	promptSnippet?: string;
}

export interface WireEstimateInput {
	systemPromptChars: number;
	/**
	 * Full system prompt text. When provided, the system portion is
	 * density-classified (skills XML / project_context / tool guidelines are
	 * dense, not prose) instead of assumed prose at /4 — M7. Callers that only
	 * know the char count keep the legacy prose divisor.
	 */
	systemPromptText?: string;
	tools: WireToolSurface[];
	/** Active model calibration to use for structural-only estimates. */
	modelId?: string;
	/** Ignore provider usage anchors and estimate the current wire structure only. */
	structuralOnly?: boolean;
	/** Messages not yet appended to session state (e.g. pending user turn). */
	pendingMessages?: AgentMessage[];
}

export interface WireUsageEstimate extends ContextUsageEstimate {
	/** Message-only portion (same as {@link ContextUsageEstimate.tokens}). */
	messageTokens: number;
	systemTokens: number;
	toolTokens: number;
	pendingTokens: number;
}

/**
 * Estimate of a tool-surface array, memoized by ARRAY reference. Tool schemas
 * are static per session, yet this ran a JSON.stringify over every schema on
 * every presend estimate. Callers that reuse the same surfaces array (see
 * `_wireToolsForEstimate`) pay the stringify once; throwaway arrays miss and
 * are GC'd with their entry.
 */
const toolSurfaceTokensCache = new WeakMap<object, number>();

/** Estimate serialized tool-definition payload on the wire. */
export function estimateToolSurfaceTokens(tools: WireToolSurface[]): number {
	const cached = toolSurfaceTokensCache.get(tools);
	if (cached !== undefined) return cached;
	let denseChars = 0;
	for (const tool of tools) {
		denseChars += tool.name.length + tool.description.length + JSON.stringify(tool.parameters).length;
	}
	const estimate = Math.ceil(denseChars / CHARS_PER_TOKEN_DENSE);
	toolSurfaceTokensCache.set(tools, estimate);
	return estimate;
}

/**
 * One-slot memo for the system prompt token estimate. The prompt text is large
 * (tens of kB) and stable across a turn; classifying it per presend would be an
 * O(chars) rescan for the same answer. Reference/value equality on the string
 * picks the slot; any change recomputes.
 */
let systemPromptTokensMemo: { text: string; tokens: number } | undefined;

function systemPromptTokensFor(text: string): number {
	const memo = systemPromptTokensMemo;
	if (memo && memo.text === text) return memo.tokens;
	const tokens = estimateTextTokens(text);
	systemPromptTokensMemo = { text, tokens };
	return tokens;
}

/**
 * Usage anchors already fed to the calibration (M5), by assistant message
 * object. The same anchor is re-estimated every presend/TUI frame; recording
 * it once keeps the EMA from over-weighting a single (estimate, usage) pair.
 */
const calibrationRecordedAnchors = new WeakSet<AgentMessage>();

/**
 * Estimate full provider wire size: session messages + system prompt + tool
 * schemas + any pending (not-yet-appended) messages.
 *
 * M5 — this is also where the online calibration LEARNS: when the estimate
 * anchors on an assistant with real usage, the char-based estimate of the very
 * span that usage bills (messages up to and including the anchor, plus system
 * prompt and tool schemas) and `usage.totalTokens` are both known here. The
 * pair feeds an EMA per model id; the resulting factor corrects ONLY the
 * char-based portions (trailing, pending, unanchored spans) — never the real
 * usage numbers. With no recorded pairs the factor is neutral 1.0 and every
 * number below is byte-identical to the uncalibrated estimate.
 */
export function estimateWireTokens(messages: AgentMessage[], input: WireEstimateInput): WireUsageEstimate {
	let messageEstimate: ContextUsageEstimate;
	if (input.structuralOnly) {
		let tokens = 0;
		for (const message of messages) tokens += estimateTokens(message);
		tokens = Math.round(tokens * tokenEstimateFactor(input.modelId));
		messageEstimate = { tokens, usageTokens: 0, trailingTokens: tokens, lastUsageIndex: null };
	} else {
		messageEstimate = estimateContextTokens(messages);
	}
	const anchoredOnUsage = messageEstimate.lastUsageIndex !== null;
	const anchorModel = anchoredOnUsage
		? (messages[messageEstimate.lastUsageIndex as number] as AssistantMessage).model
		: undefined;
	const factor = tokenEstimateFactor(input.structuralOnly ? input.modelId : anchorModel);
	let pendingTokens = 0;
	if (input.pendingMessages) {
		for (const message of input.pendingMessages) {
			pendingTokens += estimateTokens(message);
		}
	}
	pendingTokens = Math.round(pendingTokens * factor);
	// M7: classify the system prompt's real density when the text is available —
	// skills XML, project_context, and tool guidelines are dense, not /4 prose.
	const systemTokens =
		input.systemPromptText !== undefined
			? systemPromptTokensFor(input.systemPromptText)
			: Math.ceil(input.systemPromptChars / CHARS_PER_TOKEN_PROSE);
	const toolTokens = estimateToolSurfaceTokens(input.tools);
	// M5 learning: record the (raw char estimate, real usage) pair for the span
	// the anchor's usage bills — full request: prefix + messages[0..anchor].
	// Raw (uncalibrated) estimates only, so the factor never feeds back into
	// its own training signal. Once per anchor object (WeakSet dedupe).
	if (anchoredOnUsage && anchorModel) {
		const anchorIndex = messageEstimate.lastUsageIndex as number;
		const anchor = messages[anchorIndex];
		if (!calibrationRecordedAnchors.has(anchor)) {
			calibrationRecordedAnchors.add(anchor);
			let spanEstimate = systemTokens + toolTokens;
			for (let i = 0; i <= anchorIndex; i++) {
				spanEstimate += estimateTokens(messages[i]);
			}
			recordTokenEstimateSample(anchorModel, spanEstimate, messageEstimate.usageTokens);
		}
	}
	// When the message estimate anchored on real provider usage, that usage already
	// bills the WHOLE request — system prompt and tool schemas included — so adding
	// them again would double-count ~5-30k tokens and fire the presend overflow
	// guard early. Only the estimate-only path (no usage yet, e.g. first turn)
	// still needs the explicit prefix sum (calibrated: it is char-based). The
	// fields stay populated either way so callers can inspect the prefix surface.
	const tokens =
		messageEstimate.tokens + pendingTokens + (anchoredOnUsage ? 0 : Math.round((systemTokens + toolTokens) * factor));
	return {
		...messageEstimate,
		messageTokens: messageEstimate.tokens,
		systemTokens,
		toolTokens,
		pendingTokens,
		tokens,
	};
}

function getLastAssistantUsageInfo(messages: AgentMessage[]): { usage: Usage; index: number } | undefined {
	for (let i = messages.length - 1; i >= 0; i--) {
		const usage = getAssistantUsage(messages[i]);
		if (usage) return { usage, index: i };
	}
	return undefined;
}

/**
 * Estimate context tokens from messages, using the last assistant usage when available.
 * If there are messages after the last usage, estimate their tokens with estimateTokens.
 *
 * M5 — char-based portions (the trailing span after the anchor, or the whole
 * span when no usage anchors it) are multiplied by the per-model calibration
 * factor learned from real usage (see estimateWireTokens). The anchored usage
 * itself is NEVER scaled. Neutral 1.0 factor (no recorded pairs) reproduces
 * the uncalibrated numbers exactly.
 */
export function estimateContextTokens(messages: AgentMessage[]): ContextUsageEstimate {
	const usageInfo = getLastAssistantUsageInfo(messages);

	if (!usageInfo) {
		let estimated = 0;
		for (const message of messages) {
			estimated += estimateTokens(message);
		}
		estimated = Math.round(estimated * tokenEstimateFactor());
		return {
			tokens: estimated,
			usageTokens: 0,
			trailingTokens: estimated,
			lastUsageIndex: null,
		};
	}

	const usageTokens = calculateContextTokens(usageInfo.usage);
	let trailingTokens = 0;
	for (let i = usageInfo.index + 1; i < messages.length; i++) {
		trailingTokens += estimateTokens(messages[i]);
	}
	trailingTokens = Math.round(
		trailingTokens * tokenEstimateFactor((messages[usageInfo.index] as AssistantMessage).model),
	);

	return {
		tokens: usageTokens + trailingTokens,
		usageTokens,
		trailingTokens,
		lastUsageIndex: usageInfo.index,
	};
}

/**
 * Compute a dynamic reserve that scales with context window size.
 * - Small windows (≤200k): 10% of window, or the configured reserve.
 * - Large windows (>200k): the configured reserve, a 20k floor, AND a 2.5%
 *   floor. The percentage floor matters for very large windows: a flat 20k on a
 *   1M window is only 2% (trigger at ~98%, dangerously close to the hard limit
 *   if the token estimate runs low); 2.5% keeps ~25k headroom (~97.5%), leaving
 *   slack for estimation error before the model rejects on overflow.
 */
export function computeDynamicReserve(contextWindow: number, configuredReserve: number): number {
	if (!Number.isFinite(contextWindow) || contextWindow <= 0) return 0;
	const rawReserve =
		contextWindow > 200_000
			? Math.max(configuredReserve, 20_000, Math.ceil(contextWindow * 0.025))
			: Math.max(configuredReserve, Math.floor(contextWindow * 0.1));
	const maxUsableReserve = Math.max(1, Math.floor(contextWindow * 0.5));
	return Math.min(rawReserve, maxUsableReserve);
}

/**
 * Tokens to reserve for the *next* assistant thinking block before send.
 * Mirrors `@pit/ai` `adjustMaxTokensForThinking` defaults so presend compaction
 * fires before a reasoning-heavy turn overflows. Does NOT inflate
 * `estimateWireTokens` (UI % stays message/wire-only).
 *
 * Returns 0 when thinking is off or the model has no reasoning capability.
 */
export function resolveThinkingHeadroom(
	model: { reasoning?: boolean } | undefined,
	thinkingLevel: ThinkingLevel | "off" | undefined,
	customBudgets?: { minimal?: number; low?: number; medium?: number; high?: number },
): number {
	if (!model?.reasoning) return 0;
	if (!thinkingLevel || thinkingLevel === "off") return 0;
	const defaults = { minimal: 1024, low: 2048, medium: 8192, high: 16384 };
	const budgets = { ...defaults, ...customBudgets };
	// Effort-only levels (xhigh/max/ultra) have no token budget of their own;
	// reserve the high budget so presend compaction still leaves headroom.
	if (thinkingLevel === "xhigh" || thinkingLevel === "max" || thinkingLevel === "ultra") {
		return budgets.high;
	}
	return budgets[thinkingLevel] ?? budgets.medium;
}

/**
 * Effective verbatim-retention budget for findCutPoint.
 *
 * The configured `keepRecentTokens` (default 20k) is a flat floor. On a large
 * window the trigger scales (computeDynamicReserve) but a flat 20k retention
 * would discard ~950k of raw recent messages in favor of a lossy summary. Scale
 * retention to 10% of the window above 200k (same threshold/percentage as the
 * reserve), keeping the configured value as a floor. Windows ≤200k are byte-
 * identical (10% of 200k == the 20k default floor).
 */
export function effectiveKeepRecentTokens(configured: number, contextWindow?: number): number {
	if (!contextWindow || contextWindow <= 200_000) {
		return configured;
	}
	return Math.max(configured, Math.floor(contextWindow * 0.1));
}

/**
 * Fraction of the LIVE context a manual `/compact` keeps verbatim.
 *
 * {@link effectiveKeepRecentTokens} scales the keep-recent budget with the
 * WINDOW (10% of it above 200k), which is right for auto-compaction: that fires
 * near the hard threshold, so on a 1M window it keeps ~100k out of ~900k — a 90%
 * fold. But the floor is FLAT, so the same 100k against a session that is merely
 * 111k reclaims 8%, and against 194k reclaims 48% (measured). A manual compaction
 * is an explicit "reclaim now" issued at whatever pressure the user happens to be
 * at, so its budget has to scale with CURRENT USAGE instead — 25% keeps the fold
 * at ~75% across every session size. Never exceeds the window-scaled value (a
 * manual compaction is never gentler than the automatic one) and never drops
 * below {@link ADAPTIVE_KEEP_MIN_FLOOR}.
 */
export const MANUAL_COMPACT_KEEP_FRACTION = 0.25;

/**
 * Keep-recent budget for a MANUAL compaction. See
 * {@link MANUAL_COMPACT_KEEP_FRACTION}. Falls back to the window-scaled value
 * when the live size is unknown or non-positive, so a caller that cannot measure
 * gets exactly today's behaviour.
 */
export function manualKeepRecentTokens(configured: number, contextWindow?: number, liveTokens?: number): number {
	const windowScaled = effectiveKeepRecentTokens(configured, contextWindow);
	if (!liveTokens || liveTokens <= 0) return windowScaled;
	const usageScaled = Math.floor(liveTokens * MANUAL_COMPACT_KEEP_FRACTION);
	return Math.min(windowScaled, Math.max(ADAPTIVE_KEEP_MIN_FLOOR, usageScaled));
}

/** Legacy flat floor for the assumed summary + structural frame a compaction inserts. */
const COMPACTION_SUMMARY_TOKEN_BUDGET_FLOOR = 8_000;
/** Never retain less verbatim recent context than this, whatever the pressure. */
const ADAPTIVE_KEEP_MIN_FLOOR = 8_000;

/**
 * Tokens to budget for the summary + structural frame a compaction inserts (M8).
 *
 * The flat 8k systematically UNDER-estimated the real insertion: generateSummary
 * caps output at 0.8×reserveTokens (see summarizationMaxTokens), and observed
 * summaries reach ~13k once the structural frame + file digests ride along — so
 * the post-compaction context landed back above the re-check threshold on small
 * windows and the "rare" second LLM pass became structural. Derive the budget
 * from the summarizer's REAL ceiling (0.8×reserve, floored at the legacy 8k so
 * tiny configured reserves keep the old behaviour) and add the estimated
 * structural frame when the caller knows it (the frame merges forward across
 * compactions, so the previous compaction's persisted details predict it).
 */
export function compactionSummaryTokenBudget(settings: CompactionSettings, frameTokensEstimate?: number): number {
	const summaryCeiling = Math.max(COMPACTION_SUMMARY_TOKEN_BUDGET_FLOOR, Math.ceil(settings.reserveTokens * 0.8));
	const frame = Number.isFinite(frameTokensEstimate) ? Math.max(0, Math.floor(frameTokensEstimate as number)) : 0;
	return summaryCeiling + frame;
}

/**
 * Estimate the tokens of the structural frame (operation lists + file digests)
 * the NEXT compaction will append, from a previous compaction entry's persisted
 * `details`. The lists merge forward across compactions, so the previous frame
 * is the best available predictor. Returns undefined when there is no usable
 * signal (no previous compaction, empty/legacy details).
 */
export function estimateCompactionFrameTokens(details: unknown): number | undefined {
	if (typeof details !== "object" || details === null) return undefined;
	const d = details as CompactionDetails;
	let chars = 0;
	const addList = (arr: unknown): void => {
		if (!Array.isArray(arr)) return;
		for (const item of arr) {
			if (typeof item === "string") chars += item.length + 1;
		}
	};
	addList(d.readFiles);
	addList(d.modifiedFiles);
	addList(d.searches);
	addList(d.shellCmds);
	addList(d.mcpCalls);
	if (typeof d.fileDigests === "object" && d.fileDigests !== null) {
		for (const [path, digest] of Object.entries(d.fileDigests)) {
			if (typeof digest === "string") chars += path.length + digest.length + 8;
		}
	}
	if (chars === 0) return undefined;
	// The frame is XML tags + paths/commands — dense by construction.
	return Math.ceil(chars / CHARS_PER_TOKEN_DENSE);
}

/**
 * Adaptive verbatim-retention budget for a SINGLE compaction pass.
 *
 * The post-compaction context is ≈ kept-recent + summary. When that lands back
 * above the re-check threshold (the soft threshold, or the hard one on windows
 * too small for a positive soft band), runAutoCompaction used to run a SECOND
 * full pipeline — 1-2 extra LLM calls. On small windows the default keep alone
 * exceeds the target, so the second pass was structural, not incidental. This
 * shrinks the keep so one pass suffices: keep ≤ target − summary budget (M8:
 * derived from the real summarizer ceiling + previous frame estimate, no longer
 * a flat 8k), floored at max(8k, keepRecentTokens/2) so quality never collapses
 * (the second pass remains as fallback when the floor wins). Returns undefined
 * when no shrink is needed — normal windows are byte-identical to the legacy
 * path.
 */
export function adaptiveKeepRecentTokens(
	contextWindow: number,
	settings: CompactionSettings,
	frameTokensEstimate?: number,
): number | undefined {
	if (!Number.isFinite(contextWindow) || contextWindow <= 0) return undefined;
	const reserve = computeDynamicReserve(contextWindow, settings.reserveTokens);
	const effectiveKeep = effectiveKeepRecentTokens(settings.keepRecentTokens, contextWindow);
	const hardThreshold = contextWindow - reserve;
	const softThreshold = hardThreshold - effectiveKeep;
	// Mirror the post-compaction re-check: shouldCompactSoft only fires with a
	// positive soft threshold; otherwise the hard threshold is the bar.
	const target = softThreshold > 0 ? softThreshold : hardThreshold;
	const keepMax = target - compactionSummaryTokenBudget(settings, frameTokensEstimate);
	if (keepMax >= effectiveKeep) return undefined;
	const floor = Math.max(ADAPTIVE_KEEP_MIN_FLOOR, Math.floor(settings.keepRecentTokens / 2));
	const adapted = Math.min(effectiveKeep, Math.max(floor, keepMax));
	return adapted < effectiveKeep ? adapted : undefined;
}

/** Absolute minimum floor for the proactive prune; below this the cache cost is not worth it. */
const PROACTIVE_PRUNE_MIN_FLOOR = 64_000;

/**
 * Context size (tokens) below which the proactive stale-tool-output prune is NOT
 * worth running. The prune rewrites old messages, which busts the provider
 * prompt cache — only pay that when there is real pressure.
 *
 * A flat floor over-prunes on very large windows: at 64k a 1M-window session is
 * ~6% full, so pruning there churns the cache while ~94% of room remains. Scale
 * the floor to 25% of the window, keeping 64k as an absolute minimum (windows up
 * to 256k stay at 64k, byte-identical to the old behaviour). A positive explicit
 * `override` (PIT_PROACTIVE_PRUNE_FLOOR) always wins.
 */
export function proactivePruneFloor(contextWindow: number, override?: number): number {
	if (override !== undefined && Number.isFinite(override) && override > 0) return override;
	const scaled = Number.isFinite(contextWindow) && contextWindow > 0 ? Math.floor(contextWindow * 0.25) : 0;
	return Math.max(PROACTIVE_PRUNE_MIN_FLOOR, scaled);
}

/** Hysteresis threshold: only re-compact if deficit grew by this many tokens since last compaction. */
const COALESCING_THRESHOLD_TOKENS = 8192;

/**
 * Check if compaction should trigger based on context usage.
 * Uses adaptive reserve scaling and hysteresis to avoid compaction churn.
 *
 * @param lastCompactionDeficit - deficit at last compaction trigger (0 if none). Callers
 *   should persist this value and pass it back on subsequent checks.
 */
export function shouldCompact(
	contextTokens: number,
	contextWindow: number,
	settings: CompactionSettings,
	lastCompactionDeficit = 0,
): boolean {
	if (!settings.enabled) return false;
	if (!Number.isFinite(contextWindow) || contextWindow <= 0) return false;
	const reserve = computeDynamicReserve(contextWindow, settings.reserveTokens);
	const threshold = contextWindow - reserve;
	if (contextTokens <= threshold) return false;
	const deficit = contextTokens - threshold;
	if (lastCompactionDeficit === 0) return true;
	return deficit > lastCompactionDeficit + COALESCING_THRESHOLD_TOKENS;
}

/**
 * Soft (predictive) trigger: fire compaction ~one `keepRecentTokens` window
 * BEFORE the hard threshold. Run in the background while the user reads the
 * just-finished turn, so the summary is ready before they send the next prompt
 * (no visible compaction wait). The hard `shouldCompact` stays as the
 * synchronous fallback for turns that jump straight past it.
 *
 * Returns false once at/over the hard threshold — there the caller must compact
 * synchronously, not defer.
 */
export function shouldCompactSoft(contextTokens: number, contextWindow: number, settings: CompactionSettings): boolean {
	if (!settings.enabled) return false;
	if (!Number.isFinite(contextWindow) || contextWindow <= 0) return false;
	const reserve = computeDynamicReserve(contextWindow, settings.reserveTokens);
	const hardThreshold = contextWindow - reserve;
	if (contextTokens > hardThreshold) return false; // hard path owns this
	// Scale the predictive band with the window (same 10%-above-200k rule as retention) so a
	// large window gets a real head-start instead of a flat 20k sliver below the hard threshold
	// that a single big turn would jump straight past into the synchronous path. Windows ≤200k
	// are byte-identical (effectiveKeepRecentTokens returns the raw keepRecentTokens).
	const softThreshold = hardThreshold - effectiveKeepRecentTokens(settings.keepRecentTokens, contextWindow);
	return softThreshold > 0 && contextTokens > softThreshold;
}

// ============================================================================
// Cut point detection
// ============================================================================

/**
 * Find valid cut points: indices of user, assistant, custom, or bashExecution messages.
 * Never cut at tool results (they must follow their tool call).
 * When we cut at an assistant message with tool calls, its tool results follow it
 * and will be kept.
 * BashExecutionMessage is treated like a user message (user-initiated context).
 */
function findValidCutPoints(entries: SessionEntry[], startIndex: number, endIndex: number): number[] {
	const cutPoints: number[] = [];
	for (let i = startIndex; i < endIndex; i++) {
		const entry = entries[i];
		switch (entry.type) {
			case "message": {
				const role = entry.message.role;
				switch (role) {
					case "bashExecution":
					case "custom":
					case "branchSummary":
					case "compactionSummary":
					case "user":
					case "assistant":
						cutPoints.push(i);
						break;
					case "toolResult":
						break;
				}
				break;
			}
			// branch_summary and custom_message are user-role messages, valid cut points
			case "branch_summary":
			case "custom_message":
				cutPoints.push(i);
				break;
			case "thinking_level_change":
			case "model_change":
			case "compaction":
			case "custom":
			case "label":
			case "session_info":
				break;
		}
	}
	return cutPoints;
}

/**
 * Find the user message (or bashExecution) that starts the turn containing the given entry index.
 * Returns -1 if no turn start found before the index.
 * BashExecutionMessage is treated like a user message for turn boundaries.
 */
export function findTurnStartIndex(entries: SessionEntry[], entryIndex: number, startIndex: number): number {
	for (let i = entryIndex; i >= startIndex; i--) {
		const entry = entries[i];
		// branch_summary and custom_message are user-role messages, can start a turn
		if (entry.type === "branch_summary" || entry.type === "custom_message") {
			return i;
		}
		if (entry.type === "message") {
			const role = entry.message.role;
			if (role === "user" || role === "bashExecution") {
				return i;
			}
		}
	}
	return -1;
}

export interface CutPointResult {
	/** Index of first entry to keep */
	firstKeptEntryIndex: number;
	/** Index of user message that starts the turn being split, or -1 if not splitting */
	turnStartIndex: number;
	/** Whether this cut splits a turn (cut point is not a user message) */
	isSplitTurn: boolean;
}

/**
 * Find the cut point in session entries that keeps approximately `keepRecentTokens`.
 *
 * Algorithm: Walk backwards from newest, accumulating estimated message sizes.
 * Stop when we've accumulated >= keepRecentTokens. Cut at that point.
 *
 * Can cut at user OR assistant messages (never tool results). When cutting at an
 * assistant message with tool calls, its tool results come after and will be kept.
 *
 * Returns CutPointResult with:
 * - firstKeptEntryIndex: the entry index to start keeping from
 * - turnStartIndex: if cutting mid-turn, the user message that started that turn
 * - isSplitTurn: whether we're cutting in the middle of a turn
 *
 * Only considers entries between `startIndex` and `endIndex` (exclusive).
 */
export function findCutPoint(
	entries: SessionEntry[],
	startIndex: number,
	endIndex: number,
	keepRecentTokens: number,
): CutPointResult {
	const cutPoints = findValidCutPoints(entries, startIndex, endIndex);

	if (cutPoints.length === 0) {
		return { firstKeptEntryIndex: startIndex, turnStartIndex: -1, isSplitTurn: false };
	}

	// Walk backwards from newest, accumulating estimated message sizes
	let accumulatedTokens = 0;
	let cutIndex = cutPoints[0]; // Default: keep from first message (not header)

	for (let i = endIndex - 1; i >= startIndex; i--) {
		const entry = entries[i];
		if (entry.type !== "message") continue;

		// Estimate this message's size
		const messageTokens = estimateTokens(entry.message);
		accumulatedTokens += messageTokens;

		// Check if we've exceeded the budget
		if (accumulatedTokens >= keepRecentTokens) {
			// Find the closest valid cut point at or after this entry
			for (let c = 0; c < cutPoints.length; c++) {
				if (cutPoints[c] >= i) {
					cutIndex = cutPoints[c];
					break;
				}
			}
			break;
		}
	}

	// Scan backwards from cutIndex to include any non-message entries (bash, settings, etc.)
	while (cutIndex > startIndex) {
		const prevEntry = entries[cutIndex - 1];
		// Stop at session header or compaction boundaries
		if (prevEntry.type === "compaction") {
			break;
		}
		if (prevEntry.type === "message") {
			// Stop if we hit any message
			break;
		}
		// Include this non-message entry (bash, settings change, etc.)
		cutIndex--;
	}

	// Determine if this is a split turn
	const cutEntry = entries[cutIndex];
	const isUserMessage = cutEntry.type === "message" && cutEntry.message.role === "user";
	const turnStartIndex = isUserMessage ? -1 : findTurnStartIndex(entries, cutIndex, startIndex);

	return {
		firstKeptEntryIndex: cutIndex,
		turnStartIndex,
		isSplitTurn: !isUserMessage && turnStartIndex !== -1,
	};
}

// ============================================================================
// Compaction Preparation (for extensions)
// ============================================================================

export interface CompactionPreparation {
	/** UUID of first entry to keep */
	firstKeptEntryId: string;
	/** Messages that will be summarized and discarded */
	messagesToSummarize: AgentMessage[];
	/** Messages that will be turned into turn prefix summary (if splitting) */
	turnPrefixMessages: AgentMessage[];
	/** Whether this is a split turn (cut point in middle of turn) */
	isSplitTurn: boolean;
	tokensBefore: number;
	/** Summary from previous compaction, for iterative update */
	previousSummary?: string;
	/** File operations extracted from messagesToSummarize */
	fileOps: FileOperations;
	/** Compaction settions from settings.jsonl	*/
	settings: CompactionSettings;
	/** Working directory — used to strip path prefixes in summaries, saving tokens. */
	cwd?: string;
}

export function prepareCompaction(
	pathEntries: SessionEntry[],
	settings: CompactionSettings,
	contextWindow?: number,
	allowLatestCompaction = false,
	knownContextTokens?: number,
	keepRecentTokensOverride?: number,
): CompactionPreparation | undefined {
	if (!allowLatestCompaction && pathEntries.length > 0 && pathEntries[pathEntries.length - 1].type === "compaction") {
		return undefined;
	}

	let prevCompactionIndex = -1;
	for (let i = pathEntries.length - 1; i >= 0; i--) {
		if (pathEntries[i].type === "compaction") {
			prevCompactionIndex = i;
			break;
		}
	}

	let previousSummary: string | undefined;
	let boundaryStart = 0;
	if (prevCompactionIndex >= 0) {
		const prevCompaction = pathEntries[prevCompactionIndex] as CompactionEntry;
		previousSummary = prevCompaction.summary;
		const firstKeptEntryIndex = pathEntries.findIndex((entry) => entry.id === prevCompaction.firstKeptEntryId);
		boundaryStart = firstKeptEntryIndex >= 0 ? firstKeptEntryIndex : prevCompactionIndex + 1;
	}
	const boundaryEnd = pathEntries.length;

	// tokensBefore is telemetry (CompactionEntry/compaction summary metadata).
	// When the caller already holds a live-context estimate, reuse it instead of
	// rebuilding the whole session context (an O(n) message materialization) just
	// to re-derive the same number. The live estimate can run slightly lower than
	// a rebuild when live pruning already elided old outputs — that is the more
	// accurate wire-side figure anyway.
	const tokensBefore = knownContextTokens ?? estimateContextTokens(buildSessionContext(pathEntries).messages).tokens;

	// An explicit override (adaptiveKeepRecentTokens under pressure) wins over the
	// window-scaled default so a single pass can cut deep enough on small windows.
	const keepRecentTokens =
		keepRecentTokensOverride ?? effectiveKeepRecentTokens(settings.keepRecentTokens, contextWindow);
	const cutPoint = findCutPoint(pathEntries, boundaryStart, boundaryEnd, keepRecentTokens);

	// Get UUID of first kept entry
	const firstKeptEntry = pathEntries[cutPoint.firstKeptEntryIndex];
	if (!firstKeptEntry?.id) {
		return undefined; // Session needs migration
	}
	const firstKeptEntryId = firstKeptEntry.id;

	const historyEnd = cutPoint.isSplitTurn ? cutPoint.turnStartIndex : cutPoint.firstKeptEntryIndex;

	// Messages to summarize (will be discarded after summary)
	const messagesToSummarize: AgentMessage[] = [];
	for (let i = boundaryStart; i < historyEnd; i++) {
		const msg = getMessageFromEntryForCompaction(pathEntries[i]);
		if (msg) messagesToSummarize.push(msg);
	}

	// Messages for turn prefix summary (if splitting a turn)
	const turnPrefixMessages: AgentMessage[] = [];
	if (cutPoint.isSplitTurn) {
		for (let i = cutPoint.turnStartIndex; i < cutPoint.firstKeptEntryIndex; i++) {
			const msg = getMessageFromEntryForCompaction(pathEntries[i]);
			if (msg) turnPrefixMessages.push(msg);
		}
	}

	// Extract file operations from messages and previous compaction
	const fileOps = extractFileOperations(messagesToSummarize, pathEntries, prevCompactionIndex);

	// Also extract file ops from turn prefix if splitting
	if (cutPoint.isSplitTurn) {
		for (const msg of turnPrefixMessages) {
			extractFileOpsFromMessage(msg, fileOps);
		}
	}

	return {
		firstKeptEntryId,
		messagesToSummarize,
		turnPrefixMessages,
		isSplitTurn: cutPoint.isSplitTurn,
		tokensBefore,
		previousSummary,
		fileOps,
		settings,
	};
}

// ============================================================================
// Main compaction function
// ============================================================================

const TURN_PREFIX_SUMMARIZATION_PROMPT = `This is the PREFIX of a turn that was too large to keep. The SUFFIX (recent work) is retained.

Summarize the prefix to provide context for the retained suffix:

## Original Request
[What did the user ask for in this turn?]

## Early Progress
- [Key decisions and work done in the prefix]

## Context for Suffix
- [Information needed to understand the retained recent work]

Be concise. Focus on what's needed to understand the kept suffix.`;

/**
 * Below this many chars of explanatory prose in the compacted window, skip the
 * summarization LLM entirely and emit only the deterministic structural frame
 * (file operations + digests). A window that is a pure burst of tool I/O —
 * back-to-back reads/greps/edits with no assistant narration and no user prose —
 * has nothing for the summarizer to add over the structural lists, so the LLM
 * call (and its self-correction pass) is wasted latency and tokens. The bar is
 * deliberately small: ANY non-trivial prose tips the window back to the LLM path
 * so context quality is never degraded. Forced always-LLM via
 * PIT_NO_STRUCTURAL_COMPACTION=1.
 */
const STRUCTURAL_ONLY_PROSE_THRESHOLD = 200;

/**
 * Count chars of explanatory prose in the compacted window: assistant `text`
 * blocks, user free-text, and non-relay `custom` (extension-injected) text —
 * each as string content or `text`-type content blocks. Custom text IS counted
 * because convertToLlm relays it to the summarizer as a user message (a relay
 * custom — customType === MESSAGE_RELAY_CUSTOM_TYPE — is excluded, since
 * convertToLlm drops it, so it never reaches the model). Deliberately EXCLUDES
 * tool calls, tool results, thinking, bash output and the structured fields of
 * system/branch/compaction messages — those are mechanical and already captured
 * deterministically by the structural frame. This measures only what a
 * summarizer could add over the structural lists.
 */
function measureProseChars(messages: AgentMessage[]): number {
	let prose = 0;
	for (const message of messages) {
		if (message.role === "assistant") {
			for (const block of message.content) {
				if (block.type === "text") prose += block.text.length;
			}
			continue;
		}
		if (message.role === "user") {
			const content = (message as { content: string | Array<{ type: string; text?: string }> }).content;
			if (typeof content === "string") {
				prose += content.length;
			} else if (Array.isArray(content)) {
				for (const block of content) {
					if (block.type === "text" && block.text) prose += block.text.length;
				}
			}
			continue;
		}
		if (message.role === "custom") {
			// Relay custom messages are display-only — convertToLlm drops them, so
			// they carry no prose the summarizer would ever see.
			if (message.customType === MESSAGE_RELAY_CUSTOM_TYPE) continue;
			const content = message.content;
			if (typeof content === "string") {
				prose += content.length;
			} else if (Array.isArray(content)) {
				for (const block of content) {
					if (block.type === "text" && block.text) prose += block.text.length;
				}
			}
		}
	}
	return prose;
}

/**
 * True when the window has so little explanatory prose that the structural frame
 * already captures everything a summary could. Gated off by
 * PIT_NO_STRUCTURAL_COMPACTION=1 (forces the always-LLM path). A previousSummary
 * present means this is an INCREMENTAL compaction whose prose lives in the prior
 * summary, not the window — never collapse to structural-only there, or that
 * prose would be silently dropped.
 */
function shouldUseStructuralOnly(
	messagesToSummarize: AgentMessage[],
	turnPrefixMessages: AgentMessage[],
	previousSummary: string | undefined,
): boolean {
	if (isTruthyEnvFlag(process.env.PIT_NO_STRUCTURAL_COMPACTION)) return false;
	if (previousSummary) return false;
	const prose = measureProseChars(messagesToSummarize) + measureProseChars(turnPrefixMessages);
	return prose < STRUCTURAL_ONLY_PROSE_THRESHOLD;
}

/** Deterministic header emitted in place of an LLM summary for tool-only windows. */
const STRUCTURAL_ONLY_HEADER = `## Goal
(No explanatory prose in this window — mechanical tool activity only. See operations below.)

## Progress
- Tool operations on the listed files/searches/commands were applied. The retained recent context continues the work.`;

/**
 * Living-repo-map preseed + buildFileDigests over the touched files. Never
 * called with an empty `digestPaths`. Extracted from compact() so the digest
 * I/O (disk reads + symbol parse) can run CONCURRENTLY with the summarization
 * LLM calls — the inputs depend only on the preparation's fileOps, not on the
 * summary text.
 */
async function collectFileDigests(
	digestPaths: string[],
	cwd: string | undefined,
	signal: AbortSignal | undefined,
): Promise<Record<string, string>> {
	// Living repo map: a git-anchored incremental symbol index. Project it onto the
	// touched files and pass as a pre-seed so anything it already indexed is NOT
	// re-read/re-parsed here — the digest becomes a cache READ. Fail-open: any
	// failure leaves preSeed undefined and buildFileDigests rebuilds from disk
	// (output is identical; only the cost differs).
	let preSeed: Record<string, string> | undefined;
	try {
		const { map } = await getLivingRepoMap(cwd ?? ".");
		const seed: Record<string, string> = {};
		const relKeys = digestPaths.map((p) =>
			relative(cwd ?? ".", isAbsolute(p) ? p : resolve(cwd ?? ".", p))
				.split("\\")
				.join("/"),
		);
		// Filter the living-repo-map projection to just the touched files so we don't
		// materialize a digest string for every indexed file in the repo. The lookup
		// keys (and resulting seed) are identical; only the intermediate dict shrinks.
		const mapDigests = livingRepoMapToDigests(map, relKeys);
		for (let i = 0; i < digestPaths.length; i++) {
			const symbols = mapDigests[relKeys[i]];
			if (symbols !== undefined) seed[digestPaths[i]] = symbols;
		}
		preSeed = seed;
	} catch {
		preSeed = undefined;
	}
	return buildFileDigests(
		digestPaths,
		async (p) => {
			try {
				const fullPath = isAbsolute(p) ? p : resolve(cwd ?? ".", p);
				const st = await stat(fullPath);
				if (st.size > MAX_DIGEST_BYTES) return null;
				return await readFile(fullPath, { encoding: "utf8", signal });
			} catch {
				return null;
			}
		},
		signal,
		preSeed,
	);
}

/**
 * Generate summaries for compaction using prepared data.
 * Returns CompactionResult - SessionManager adds uuid/parentUuid when saving.
 *
 * @param preparation - Pre-calculated preparation from prepareCompaction()
 * @param customInstructions - Optional custom focus for the summary
 */
export async function compact(
	preparation: CompactionPreparation,
	model: Model<any>,
	apiKey: string | undefined,
	headers?: Record<string, string>,
	customInstructions?: string,
	signal?: AbortSignal,
	thinkingLevel?: ThinkingLevel,
	streamFn?: StreamFn,
	cacheAware?: CacheAwareGeneration,
): Promise<CompactionResult> {
	const {
		firstKeptEntryId,
		messagesToSummarize: messagesToSummarizeRaw,
		turnPrefixMessages: turnPrefixMessagesRaw,
		isSplitTurn,
		tokensBefore,
		previousSummary,
		fileOps,
		settings,
		cwd,
	} = preparation;

	// Clone toolResult messages BEFORE pruning. getMessageFromEntry returns
	// entry.message by reference for 'message' entries, so without this the prune
	// would elide tool results inside the LIVE session context; an aborted
	// summarization would then leave them elided with no restore. Cloning makes the
	// prune operate on throw-away copies — happy-path output is unchanged.
	const messagesToSummarize = cloneToolResultMessagesForPrune(messagesToSummarizeRaw);
	const turnPrefixMessages = isSplitTurn
		? cloneToolResultMessagesForPrune(turnPrefixMessagesRaw)
		: turnPrefixMessagesRaw;

	// Pre-prune large tool outputs before sending to summarizer. Scale the
	// threshold to the window: tighter windows prune more aggressively (capped at
	// the default so large windows are unchanged).
	const pruneThreshold = Math.min(
		PRUNE_TOKEN_THRESHOLD,
		Math.max(4_000, Math.floor((model.contextWindow || 200_000) * 0.1)),
	);
	pruneOldToolOutputs(messagesToSummarize, pruneThreshold);
	if (isSplitTurn) {
		pruneOldToolOutputs(turnPrefixMessages, pruneThreshold);
	}

	// Serialized views shared by the summarizer and the verification pass.
	// Created AFTER the prune above — the prune rewrites block.text in place, and
	// the memo must capture the pruned (final) window. One window per message
	// list; never share across main/prefix.
	const mainWindow = createSerializedWindow(messagesToSummarize);
	const prefixWindow = isSplitTurn ? createSerializedWindow(turnPrefixMessages) : undefined;

	// File digests kick off NOW so the disk reads + symbol parsing overlap the
	// summarization LLM calls below; the result is awaited only after the verify
	// pass. Reading at compaction start instead of after the LLM round-trips is
	// equivalent: the session is disconnected/idle during compaction, so no tool
	// writes land in between.
	const lists = computeOperationLists(fileOps, cwd);
	// Modified files are the artifact trail that summary prose silently drops, so
	// they get digests by default; read-only files stay behind PIT_FILE_DIGESTS to
	// bound prefix growth. The lists are disjoint (read AND modified surfaces only
	// in modifiedFiles), so concatenating needs no dedup.
	const digestPaths = isTruthyEnvFlag(process.env.PIT_FILE_DIGESTS)
		? [...lists.modifiedFiles, ...lists.readFiles]
		: lists.modifiedFiles;
	const digestsPromise = digestPaths.length > 0 ? collectFileDigests(digestPaths, cwd, signal) : undefined;

	// Generate summaries (can be parallel if both needed) and merge into one
	let summary: string;
	let structuralOnly: boolean;

	try {
		// Structural-only fast path: when the compacted window is a pure burst of tool
		// I/O with no explanatory prose, the deterministic operation lists + digests
		// (appended below) already capture everything a summary could. Skip the
		// summarizer LLM and its self-correction pass. Disabled by
		// PIT_NO_STRUCTURAL_COMPACTION=1 and never taken for incremental compactions
		// (see shouldUseStructuralOnly).
		structuralOnly = shouldUseStructuralOnly(messagesToSummarize, turnPrefixMessages, previousSummary);
		if (structuralOnly) {
			summary = STRUCTURAL_ONLY_HEADER;
		} else if (isSplitTurn && turnPrefixMessages.length > 0) {
			const [historyResult, turnPrefixResult] = await Promise.all([
				messagesToSummarize.length > 0
					? generateSummary(
							messagesToSummarize,
							model,
							settings.reserveTokens,
							apiKey,
							headers,
							signal,
							customInstructions,
							previousSummary,
							thinkingLevel,
							streamFn,
							mainWindow,
							cacheAware,
						)
					: Promise.resolve("No prior history."),
				generateTurnPrefixSummary(
					turnPrefixMessages,
					model,
					settings.reserveTokens,
					apiKey,
					headers,
					signal,
					thinkingLevel,
					streamFn,
					prefixWindow,
				),
			]);
			summary = `${historyResult}\n\n---\n\n**Turn Context (split turn):**\n\n${turnPrefixResult}`;
		} else {
			summary = await generateSummary(
				messagesToSummarize,
				model,
				settings.reserveTokens,
				apiKey,
				headers,
				signal,
				customInstructions,
				previousSummary,
				thinkingLevel,
				streamFn,
				mainWindow,
				cacheAware,
			);
		}

		// Self-correction: verify summary for omitted details. Gated by input size —
		// small/incremental compactions skip the second LLM call (low omission risk).
		const verifyInputTokens =
			sumMessageTokens(messagesToSummarize) + (isSplitTurn ? sumMessageTokens(turnPrefixMessages) : 0);
		if (!structuralOnly && settings.selfCorrection !== false && verifyInputTokens >= VERIFY_MIN_INPUT_TOKENS) {
			const maxTokens = summarizationMaxTokens(model, settings.reserveTokens, 0.8);
			const verifySource = buildVerificationSource(
				messagesToSummarize,
				isSplitTurn ? turnPrefixMessages : [],
				mainWindow,
				isSplitTurn ? prefixWindow : undefined,
			);
			summary = await verifySummary(
				summary,
				verifySource,
				model,
				maxTokens,
				apiKey,
				headers,
				signal,
				thinkingLevel,
				streamFn,
			);
		}

		if (!structuralOnly && !isTruthyEnvFlag(process.env.PIT_NO_COMPACT_SUMMARY_OUTPUT)) {
			summary = trimSummaryProseAgainstOperations(summary, lists);
		}
		// Deterministic grounding: annotate path tokens in the prose that are neither
		// in the operation lists nor on disk with `(unverified)`. Runs before the
		// structural frame (correct by construction) is appended, and is skipped for
		// the structural-only header (no prose to ground). Zero-LLM, every provider.
		if (!structuralOnly && !isTruthyEnvFlag(process.env.PIT_NO_SUMMARY_GROUNDING)) {
			summary = groundSummaryPaths(summary, lists, cwd).summary;
		}
		summary += formatFileOperations(lists);
	} catch (err) {
		// Summarization failed before digests were awaited — attach a no-op so the
		// in-flight digests don't surface an unhandled rejection. Digest errors still
		// propagate via the await below when summarization succeeds.
		digestsPromise?.catch(() => {});
		throw err;
	}

	if (!firstKeptEntryId) {
		throw new Error("First kept entry has no UUID - session may need migration");
	}

	const details: CompactionDetails = {
		readFiles: lists.readFiles,
		modifiedFiles: lists.modifiedFiles,
	};
	if (lists.searches.length > 0) details.searches = lists.searches;
	if (lists.shellCmds.length > 0) details.shellCmds = lists.shellCmds;
	if (lists.mcpCalls.length > 0) details.mcpCalls = lists.mcpCalls;

	// File digests: a symbol outline of touched files at compaction time, so the
	// post-compaction model recalls the CURRENT shape of what it worked on without a
	// re-read. The collection was kicked off before the summarization LLM calls
	// (see digestsPromise above); only the await lands here.
	if (digestsPromise) {
		const digests = await digestsPromise;
		if (Object.keys(digests).length > 0) {
			details.fileDigests = digests;
			summary += `\n${formatFileDigests(digests)}`;
		}
	}

	// recall_history footer: announce that the summarized window is recoverable
	// on demand. The tool answers gracefully when there is no compacted history,
	// so the footer is unconditional (per default-native policy). Skipped for the
	// structural-only header (no prose window was summarized) and on opt-out.
	if (!structuralOnly && !isTruthyEnvFlag(process.env.PIT_NO_RECALL_HISTORY)) {
		summary += "\n[Details from the summarized window are retrievable via recall_history({ query }).]";
	}

	return {
		summary,
		firstKeptEntryId,
		tokensBefore,
		details,
	};
}

/**
 * Generate a summary for a turn prefix (when splitting a turn).
 */
async function generateTurnPrefixSummary(
	messages: AgentMessage[],
	model: Model<any>,
	reserveTokens: number,
	apiKey: string | undefined,
	headers?: Record<string, string>,
	signal?: AbortSignal,
	thinkingLevel?: ThinkingLevel,
	streamFn?: StreamFn,
	serialized?: SerializedWindow,
): Promise<string> {
	const maxTokens = summarizationMaxTokens(model, reserveTokens, 0.5); // Smaller budget for turn prefix
	const llmMessages = serialized?.llm ?? convertToLlm(messages);
	const conversationText = serializeConversation(llmMessages);
	const promptText = `<conversation>\n${conversationText}\n</conversation>\n\n${TURN_PREFIX_SUMMARIZATION_PROMPT}`;

	return runSummarization(
		model,
		promptText,
		maxTokens,
		apiKey,
		headers,
		signal,
		thinkingLevel,
		streamFn,
		"Turn prefix summarization failed",
	);
}
