import { type AgentMessage, uuidv7 } from "@pit/agent-core";
import type { ImageContent, Message, TextContent } from "@pit/ai";
import { recordDiagnostic } from "@pit/ai";
import { randomUUID } from "crypto";
import {
	appendFileSync,
	closeSync,
	existsSync,
	mkdirSync,
	openSync,
	readdirSync,
	readFileSync,
	readSync,
	renameSync,
	statSync,
	unlinkSync,
	writeFileSync,
} from "fs";
import { appendFile, readdir, stat } from "fs/promises";
import { join, resolve } from "path";
import { getAgentDir as getDefaultAgentDir, getSessionsDir } from "../config.ts";
import {
	type BashExecutionMessage,
	type CustomMessage,
	createBranchSummaryMessage,
	createCompactionSummaryMessage,
	createCustomMessage,
} from "./messages.ts";
import { redactForDisk } from "./secret-redactor.ts";

export const CURRENT_SESSION_VERSION = 3;

export interface SessionHeader {
	type: "session";
	version?: number; // v1 sessions don't have this
	id: string;
	timestamp: string;
	cwd: string;
	parentSession?: string;
}

export interface NewSessionOptions {
	id?: string;
	parentSession?: string;
}

export interface SessionEntryBase {
	type: string;
	id: string;
	parentId: string | null;
	timestamp: string;
}

export interface SessionMessageEntry extends SessionEntryBase {
	type: "message";
	message: AgentMessage;
}

export interface ThinkingLevelChangeEntry extends SessionEntryBase {
	type: "thinking_level_change";
	thinkingLevel: string;
}

export interface ModelChangeEntry extends SessionEntryBase {
	type: "model_change";
	provider: string;
	modelId: string;
}

export interface CompactionEntry<T = unknown> extends SessionEntryBase {
	type: "compaction";
	summary: string;
	firstKeptEntryId: string;
	tokensBefore: number;
	/** Extension-specific data (e.g., ArtifactIndex, version markers for structured compaction) */
	details?: T;
	/** True if generated by an extension, undefined/false if pi-generated (backward compatible) */
	fromHook?: boolean;
}

export interface BranchSummaryEntry<T = unknown> extends SessionEntryBase {
	type: "branch_summary";
	fromId: string;
	summary: string;
	/** Extension-specific data (not sent to LLM) */
	details?: T;
	/** True if generated by an extension, false if pi-generated */
	fromHook?: boolean;
}

/**
 * Custom entry for extensions to store extension-specific data in the session.
 * Use customType to identify your extension's entries.
 *
 * Purpose: Persist extension state across session reloads. On reload, extensions can
 * scan entries for their customType and reconstruct internal state.
 *
 * Does NOT participate in LLM context (ignored by buildSessionContext).
 * For injecting content into context, see CustomMessageEntry.
 */
export interface CustomEntry<T = unknown> extends SessionEntryBase {
	type: "custom";
	customType: string;
	data?: T;
}

/** Label entry for user-defined bookmarks/markers on entries. */
export interface LabelEntry extends SessionEntryBase {
	type: "label";
	targetId: string;
	label: string | undefined;
}

/** Session metadata entry (e.g., user-defined display name). */
export interface SessionInfoEntry extends SessionEntryBase {
	type: "session_info";
	name?: string;
}

/**
 * Custom message entry for extensions to inject messages into LLM context.
 * Use customType to identify your extension's entries.
 *
 * Unlike CustomEntry, this DOES participate in LLM context.
 * The content is converted to a user message in buildSessionContext().
 * Use details for extension-specific metadata (not sent to LLM).
 *
 * display controls TUI rendering:
 * - false: hidden entirely
 * - true: rendered with distinct styling (different from user messages)
 */
export interface CustomMessageEntry<T = unknown> extends SessionEntryBase {
	type: "custom_message";
	customType: string;
	content: string | (TextContent | ImageContent)[];
	details?: T;
	display: boolean;
}

/** Session entry - has id/parentId for tree structure (returned by "read" methods in SessionManager) */
export type SessionEntry =
	| SessionMessageEntry
	| ThinkingLevelChangeEntry
	| ModelChangeEntry
	| CompactionEntry
	| BranchSummaryEntry
	| CustomEntry
	| CustomMessageEntry
	| LabelEntry
	| SessionInfoEntry;

/** Raw file entry (includes header) */
export type FileEntry = SessionHeader | SessionEntry;

/** Tree node for getTree() - defensive copy of session structure */
export interface SessionTreeNode {
	entry: SessionEntry;
	children: SessionTreeNode[];
	/** Resolved label for this entry, if any */
	label?: string;
	/** Timestamp of the latest label change for this entry, if any */
	labelTimestamp?: string;
}

export interface SessionContext {
	messages: AgentMessage[];
	thinkingLevel: string;
	model: { provider: string; modelId: string } | null;
}

export interface SessionInfo {
	path: string;
	id: string;
	/** Working directory where the session was started. Empty string for old sessions. */
	cwd: string;
	/** User-defined display name from session_info entries. */
	name?: string;
	/** Path to the parent session (if this session was forked). */
	parentSessionPath?: string;
	created: Date;
	modified: Date;
	messageCount: number;
	firstMessage: string;
	allMessagesText: string;
}

export type ReadonlySessionManager = Pick<
	SessionManager,
	| "getCwd"
	| "getSessionDir"
	| "getSessionId"
	| "getSessionFile"
	| "getLeafId"
	| "getLeafEntry"
	| "getEntry"
	| "getLabel"
	| "getBranch"
	| "getHeader"
	| "getEntries"
	| "getTree"
	| "getSessionName"
>;

function createSessionId(): string {
	return uuidv7();
}

/** Generate a unique short ID (8 hex chars, collision-checked) */
function generateId(byId: { has(id: string): boolean }): string {
	for (let i = 0; i < 100; i++) {
		const id = randomUUID().slice(0, 8);
		if (!byId.has(id)) return id;
	}
	// Fallback to full UUID if somehow we have collisions
	return randomUUID();
}

/** Migrate v1 → v2: add id/parentId tree structure. Mutates in place. */
function migrateV1ToV2(entries: FileEntry[]): void {
	const ids = new Set<string>();
	let prevId: string | null = null;

	for (const entry of entries) {
		if (entry.type === "session") {
			entry.version = 2;
			continue;
		}

		entry.id = generateId(ids);
		entry.parentId = prevId;
		prevId = entry.id;

		// Convert firstKeptEntryIndex to firstKeptEntryId for compaction
		if (entry.type === "compaction") {
			const comp = entry as CompactionEntry & { firstKeptEntryIndex?: number };
			if (typeof comp.firstKeptEntryIndex === "number") {
				const targetEntry = entries[comp.firstKeptEntryIndex];
				if (targetEntry && targetEntry.type !== "session") {
					comp.firstKeptEntryId = targetEntry.id;
				}
				delete comp.firstKeptEntryIndex;
			}
		}
	}
}

/** Migrate v2 → v3: rename hookMessage role to custom. Mutates in place. */
function migrateV2ToV3(entries: FileEntry[]): void {
	for (const entry of entries) {
		if (entry.type === "session") {
			entry.version = 3;
			continue;
		}

		// Update message entries with hookMessage role
		if (entry.type === "message") {
			const msgEntry = entry as SessionMessageEntry;
			if (msgEntry.message && (msgEntry.message as { role: string }).role === "hookMessage") {
				(msgEntry.message as { role: string }).role = "custom";
			}
		}
	}
}

/**
 * Run all necessary migrations to bring entries to current version.
 * Mutates entries in place. Returns true if any migration was applied.
 */
function migrateToCurrentVersion(entries: FileEntry[]): boolean {
	const header = entries.find((e) => e.type === "session") as SessionHeader | undefined;
	const version = header?.version ?? 1;

	if (version >= CURRENT_SESSION_VERSION) return false;

	if (version < 2) migrateV1ToV2(entries);
	if (version < 3) migrateV2ToV3(entries);

	return true;
}

/** Exported for testing */
export function migrateSessionEntries(entries: FileEntry[]): void {
	migrateToCurrentVersion(entries);
}

/** Exported for compaction.test.ts */
export function parseSessionEntries(content: string): FileEntry[] {
	const entries: FileEntry[] = [];
	const lines = content.trim().split("\n");

	for (const line of lines) {
		if (!line.trim()) continue;
		try {
			const entry = JSON.parse(line) as FileEntry;
			entries.push(entry);
		} catch {
			// Skip malformed lines
		}
	}

	return entries;
}

export function getLatestCompactionEntry(entries: SessionEntry[]): CompactionEntry | null {
	for (let i = entries.length - 1; i >= 0; i--) {
		if (entries[i].type === "compaction") {
			return entries[i] as CompactionEntry;
		}
	}
	return null;
}

// Derived LLM messages (custom / branch-summary / compaction-summary) are
// rebuilt from immutable entry fields on every buildSessionContext call.
// Memoize per source entry so the SAME object is returned across turns —
// otherwise convertToLlm's identity-keyed WeakMap (agent harness) misses on
// these every turn and re-serializes every summary text. Keyed by entry
// identity, so it GCs with the entries (rebuilt on session reload).
const derivedMessageCache = new WeakMap<SessionEntry, AgentMessage>();

function deriveCachedMessage(entry: SessionEntry, make: () => AgentMessage): AgentMessage {
	let cached = derivedMessageCache.get(entry);
	if (cached === undefined) {
		cached = make();
		derivedMessageCache.set(entry, cached);
	}
	return cached;
}

/**
 * Build the session context from entries using tree traversal.
 * If leafId is provided, walks from that entry to root.
 * Handles compaction and branch summaries along the path.
 */
export function buildSessionContext(
	entries: SessionEntry[],
	leafId?: string | null,
	byId?: Map<string, SessionEntry>,
): SessionContext {
	// Build uuid index if not available
	if (!byId) {
		byId = new Map<string, SessionEntry>();
		for (const entry of entries) {
			byId.set(entry.id, entry);
		}
	}

	// Find leaf
	let leaf: SessionEntry | undefined;
	if (leafId === null) {
		// Explicitly null - return no messages (navigated to before first entry)
		return { messages: [], thinkingLevel: "off", model: null };
	}
	if (leafId) {
		leaf = byId.get(leafId);
	}
	if (!leaf) {
		// Fallback to last entry (when leafId is undefined)
		leaf = entries[entries.length - 1];
	}

	if (!leaf) {
		return { messages: [], thinkingLevel: "off", model: null };
	}

	// Walk from leaf to root, collecting path. Push+reverse avoids the O(n²)
	// cost of unshift on long sessions.
	const path: SessionEntry[] = [];
	let current: SessionEntry | undefined = leaf;
	while (current) {
		path.push(current);
		current = current.parentId ? byId.get(current.parentId) : undefined;
	}
	path.reverse();

	// Extract settings and find compaction. Record the compaction index here so
	// the later message build can skip a second O(n) findIndex scan.
	let thinkingLevel = "off";
	let model: { provider: string; modelId: string } | null = null;
	let compaction: CompactionEntry | null = null;
	let compactionIdx = -1;

	for (let i = 0; i < path.length; i++) {
		const entry = path[i];
		if (entry.type === "thinking_level_change") {
			thinkingLevel = entry.thinkingLevel;
		} else if (entry.type === "model_change") {
			model = { provider: entry.provider, modelId: entry.modelId };
		} else if (entry.type === "message" && entry.message.role === "assistant") {
			model = { provider: entry.message.provider, modelId: entry.message.model };
		} else if (entry.type === "compaction") {
			compaction = entry;
			compactionIdx = i;
		}
	}

	// Build messages and collect corresponding entries
	// When there's a compaction, we need to:
	// 1. Emit summary first (entry = compaction)
	// 2. Emit kept messages (from firstKeptEntryId up to compaction)
	// 3. Emit messages after compaction
	const messages: AgentMessage[] = [];

	const appendMessage = (entry: SessionEntry) => {
		if (entry.type === "message") {
			const msg = entry.message;
			// Compat: unmigrated JSONL may still carry role "hookMessage" (pre-v3).
			if (msg && typeof msg === "object" && (msg as { role?: string }).role === "hookMessage") {
				messages.push({ ...(msg as object), role: "custom" } as AgentMessage);
			} else {
				messages.push(msg);
			}
		} else if (entry.type === "custom_message") {
			messages.push(
				deriveCachedMessage(entry, () =>
					createCustomMessage(entry.customType, entry.content, entry.display, entry.details, entry.timestamp),
				),
			);
		} else if (entry.type === "branch_summary" && entry.summary) {
			messages.push(
				deriveCachedMessage(entry, () => createBranchSummaryMessage(entry.summary, entry.fromId, entry.timestamp)),
			);
		}
	};

	if (compaction) {
		// Emit summary first
		messages.push(
			deriveCachedMessage(compaction, () =>
				createCompactionSummaryMessage(compaction.summary, compaction.tokensBefore, compaction.timestamp),
			),
		);

		// Emit kept messages (before compaction, starting from firstKeptEntryId)
		let foundFirstKept = false;
		for (let i = 0; i < compactionIdx; i++) {
			const entry = path[i];
			if (entry.id === compaction.firstKeptEntryId) {
				foundFirstKept = true;
			}
			if (foundFirstKept) {
				appendMessage(entry);
			}
		}

		// Emit messages after compaction
		for (let i = compactionIdx + 1; i < path.length; i++) {
			const entry = path[i];
			appendMessage(entry);
		}
	} else {
		// No compaction - emit all messages, handle branch summaries and custom messages
		for (const entry of path) {
			appendMessage(entry);
		}
	}

	return { messages, thinkingLevel, model };
}

/**
 * Encode a cwd into the on-disk session-bucket directory name under
 * `~/.pit/agent/sessions/`. Exported for tests and for read-side probes that
 * must not mkdir.
 */
export function encodeSessionDirName(cwd: string): string {
	return `--${cwd.replace(/^[/\\]/, "").replace(/[/\\:]/g, "-")}--`;
}

/**
 * Session-bucket path for a cwd without creating the directory.
 */
export function sessionDirForCwd(cwd: string, agentDir: string = getDefaultAgentDir()): string {
	return join(agentDir, "sessions", encodeSessionDirName(cwd));
}

/**
 * Stable key for comparing session cwds. Resolves to absolute form; on Windows
 * lowercases so `C:\Work` and `c:\work` count as the same project folder.
 */
export function normalizeCwdKey(cwd: string): string {
	const resolved = resolve(cwd);
	return process.platform === "win32" ? resolved.toLowerCase() : resolved;
}

/** True when a session header cwd belongs to the execution folder. */
export function sessionMatchesCwd(sessionCwd: string | undefined, targetCwd: string): boolean {
	if (!sessionCwd) return true; // legacy / missing header cwd — keep in the bucket
	return normalizeCwdKey(sessionCwd) === normalizeCwdKey(targetCwd);
}

/**
 * Temp / ephemeral session buckets (PIT_TMP_DIR, OS temp, mkdtemp under .pit/tmp).
 * Excluded from listAll so the resume picker doesn't scan tens of thousands of
 * throwaway dirs created by short-lived agent runs.
 */
export function isEphemeralSessionDirName(name: string): boolean {
	const n = name.toLowerCase();
	return (
		n.includes(".pit-tmp-") ||
		n.includes("-pit-tmp-") ||
		n.includes("-tmp-pi-") ||
		n.includes("-appdata-local-temp-") ||
		n.includes("-appdata-local-tmp-")
	);
}

/**
 * Compute the default session directory for a cwd.
 * Encodes cwd into a safe directory name under ~/.pit/agent/sessions/.
 */
export function getDefaultSessionDir(cwd: string, agentDir: string = getDefaultAgentDir()): string {
	const sessionDir = sessionDirForCwd(cwd, agentDir);
	if (!existsSync(sessionDir)) {
		mkdirSync(sessionDir, { recursive: true });
	}
	return sessionDir;
}

// Sessions that ran for hours can reach hundreds of MB on disk. buildSessionInfo
// (for the /resume picker) always uses a bounded head-read so listing never
// materializes the full .jsonl or allMessagesText. Lazy search text still refuses
// to full-read above this size (see resolveSessionSearchText).
const SESSION_INFO_FULL_READ_MAX_BYTES = 8 * 1024 * 1024;
// How much of an oversized file to read for the header + first user message.
const SESSION_INFO_HEAD_READ_BYTES = 64 * 1024;

const SESSION_LOAD_CHUNK_BYTES = 256 * 1024;

function pushEntryFromLine(line: string, entries: FileEntry[]): void {
	if (!line.trim()) return;
	const start = line.charCodeAt(0) <= 32 ? line.indexOf("{") : 0;
	if (start < 0 || start >= line.length) return;
	try {
		entries.push(JSON.parse(line.slice(start)) as FileEntry);
	} catch {
		// Skip malformed lines
	}
}

function validateSessionEntries(entries: FileEntry[]): FileEntry[] {
	if (entries.length === 0) return entries;
	const header = entries[0];
	if (header.type !== "session" || typeof (header as { id?: unknown }).id !== "string") {
		return [];
	}
	return entries;
}

/** Stream-parse oversized session files without materializing the whole file as one string. */
function loadEntriesFromFileStreaming(filePath: string): FileEntry[] {
	const entries: FileEntry[] = [];
	const fd = openSync(filePath, "r");
	try {
		const fileSize = statSync(filePath).size;
		const buffer = Buffer.alloc(SESSION_LOAD_CHUNK_BYTES);
		let filePos = 0;
		let leftover = "";
		while (filePos < fileSize) {
			const bytesRead = readSync(fd, buffer, 0, SESSION_LOAD_CHUNK_BYTES, filePos);
			if (bytesRead <= 0) break;
			filePos += bytesRead;
			leftover += buffer.toString("utf8", 0, bytesRead);
			let eol = leftover.indexOf("\n");
			while (eol !== -1) {
				pushEntryFromLine(leftover.slice(0, eol), entries);
				leftover = leftover.slice(eol + 1);
				eol = leftover.indexOf("\n");
			}
		}
		pushEntryFromLine(leftover, entries);
	} finally {
		closeSync(fd);
	}
	return validateSessionEntries(entries);
}

/** Exported for testing */
export function loadEntriesFromFile(filePath: string): FileEntry[] {
	if (!existsSync(filePath)) return [];

	let fileSize = 0;
	try {
		fileSize = statSync(filePath).size;
	} catch {
		return [];
	}

	if (fileSize > SESSION_INFO_FULL_READ_MAX_BYTES) {
		return loadEntriesFromFileStreaming(filePath);
	}

	const content = readFileSync(filePath, "utf8");
	const entries: FileEntry[] = [];

	let pos = 0;
	const len = content.length;
	while (pos < len) {
		let eol = content.indexOf("\n", pos);
		if (eol === -1) eol = len;
		if (eol > pos) {
			pushEntryFromLine(content.slice(pos, eol), entries);
		}
		pos = eol + 1;
	}

	return validateSessionEntries(entries);
}

function isValidSessionFile(filePath: string): boolean {
	try {
		const fd = openSync(filePath, "r");
		try {
			const buffer = Buffer.alloc(512);
			const bytesRead = readSync(fd, buffer, 0, 512, 0);
			const firstLine = buffer.toString("utf8", 0, bytesRead).split("\n")[0];
			if (!firstLine) return false;
			const header = JSON.parse(firstLine);
			return header.type === "session" && typeof header.id === "string";
		} finally {
			closeSync(fd);
		}
	} catch {
		return false;
	}
}

/**
 * Bounded-read fallback for oversized session files. Reads only the first
 * SESSION_INFO_HEAD_READ_BYTES (reusing the openSync/readSync pattern of
 * isValidSessionFile), parses the header and scans the leading lines for the
 * first user message. allMessagesText is left empty: the card renders from
 * firstMessage, and body search degrades gracefully rather than OOMing.
 */
function buildSessionInfoBounded(filePath: string, stats: { size: number; mtime: Date }): SessionInfo | null {
	let head: string;
	try {
		const fd = openSync(filePath, "r");
		try {
			const buffer = Buffer.alloc(SESSION_INFO_HEAD_READ_BYTES);
			const bytesRead = readSync(fd, buffer, 0, SESSION_INFO_HEAD_READ_BYTES, 0);
			head = buffer.toString("utf8", 0, bytesRead);
		} finally {
			closeSync(fd);
		}
	} catch {
		return null;
	}

	// Drop the last line: a 64KB cut almost always lands mid-line, and a partial
	// JSON object would just be skipped anyway.
	const lines = head.split("\n");
	lines.pop();

	const entries: FileEntry[] = [];
	for (const line of lines) {
		if (!line.trim()) continue;
		try {
			entries.push(JSON.parse(line) as FileEntry);
		} catch {
			// Skip malformed/partial lines
		}
	}

	if (entries.length === 0) return null;
	const header = entries[0];
	if (header.type !== "session") return null;

	let firstMessage = "";
	let name: string | undefined;
	for (const entry of entries) {
		if (entry.type === "session_info") {
			name = (entry as SessionInfoEntry).name?.trim() || undefined;
		}
		if (firstMessage || entry.type !== "message") continue;
		const message = (entry as SessionMessageEntry).message;
		if (!isMessageWithContent(message)) continue;
		if (message.role !== "user") continue;
		const textContent = extractTextContent(message);
		if (textContent) firstMessage = textContent;
	}

	const cwd = typeof (header as SessionHeader).cwd === "string" ? (header as SessionHeader).cwd : "";
	const parentSessionPath = (header as SessionHeader).parentSession;
	const headerTime = (header as SessionHeader).timestamp;

	return {
		path: filePath,
		id: (header as SessionHeader).id,
		cwd,
		name,
		parentSessionPath,
		created: new Date(headerTime),
		// We can't scan the whole file for the last activity timestamp without
		// reading it all, so fall back to the file mtime.
		modified: stats.mtime,
		// messageCount/allMessagesText are intentionally degraded for huge files.
		messageCount: 0,
		firstMessage: firstMessage || "(large session)",
		allMessagesText: "",
	};
}

/** Exported for testing */
export function findMostRecentSession(sessionDir: string): string | null {
	try {
		const files = readdirSync(sessionDir).filter((f) => f.endsWith(".jsonl"));
		if (files.length === 0) return null;
		// Real session filenames begin with an ISO-like timestamp prefix (4-digit
		// year), which means lexicographic descending order matches chronological
		// order without a stat() per file. If any file doesn't match that shape,
		// fall back to mtime-based sorting so arbitrary filenames still resolve
		// to the most recently modified file.
		const isoPrefix = /^\d{4}[-T]/;
		const allIso = files.every((f) => isoPrefix.test(f));
		let ordered: string[];
		if (allIso) {
			ordered = files.slice().sort((a, b) => b.localeCompare(a));
		} else {
			ordered = files
				.map((f) => {
					const path = join(sessionDir, f);
					try {
						return { f, mtime: statSync(path).mtimeMs };
					} catch {
						return { f, mtime: 0 };
					}
				})
				.sort((a, b) => b.mtime - a.mtime)
				.map((x) => x.f);
		}

		for (const f of ordered) {
			const path = join(sessionDir, f);
			if (isValidSessionFile(path)) return path;
		}
		return null;
	} catch {
		return null;
	}
}

function isMessageWithContent(message: AgentMessage): message is Message {
	return typeof (message as Message).role === "string" && "content" in message;
}

function extractTextContent(message: Message): string {
	const content = message.content;
	if (typeof content === "string") {
		return content;
	}
	return content
		.filter((block): block is TextContent => block.type === "text")
		.map((block) => block.text)
		.join(" ");
}

/** Cap lazy search-text materialization (matches session-selector regex cap). */
const SESSION_SEARCH_TEXT_CAP = 50_000;

/**
 * Resolve searchable message text for the session picker. When `allMessagesText`
 * was skipped at list time, load and cache it on first filter.
 */
export function resolveSessionSearchText(session: SessionInfo): string {
	if (session.allMessagesText.length > 0) return session.allMessagesText;
	try {
		const preStats = statSync(session.path);
		if (preStats.size > SESSION_INFO_FULL_READ_MAX_BYTES) {
			return "";
		}
		const content = readFileSync(session.path, "utf8");
		const parts: string[] = [];
		let total = 0;
		for (const line of content.trim().split("\n")) {
			if (!line.trim()) continue;
			let entry: FileEntry;
			try {
				entry = JSON.parse(line) as FileEntry;
			} catch {
				continue;
			}
			if (entry.type !== "message") continue;
			const message = (entry as SessionMessageEntry).message;
			if (!isMessageWithContent(message)) continue;
			if (message.role !== "user" && message.role !== "assistant") continue;
			const text = extractTextContent(message);
			if (!text) continue;
			if (total + text.length > SESSION_SEARCH_TEXT_CAP) break;
			parts.push(text);
			total += text.length;
		}
		const built = parts.join(" ");
		session.allMessagesText = built;
		return built;
	} catch {
		return "";
	}
}

async function buildSessionInfo(filePath: string): Promise<SessionInfo | null> {
	try {
		// Always bounded: listing never full-reads the .jsonl. Search text is
		// deferred to resolveSessionSearchText on first filter.
		const preStats = await stat(filePath);
		return buildSessionInfoBounded(filePath, preStats);
	} catch {
		return null;
	}
}

export type SessionListProgress = (loaded: number, total: number) => void;

const MAX_CONCURRENT_SESSION_INFO_LOADS = 10;
const MAX_CONCURRENT_SESSION_DIR_READS = 10;

async function buildSessionInfosWithConcurrency(
	files: string[],
	onLoaded: () => void,
): Promise<(SessionInfo | null)[]> {
	const results: (SessionInfo | null)[] = new Array(files.length).fill(null);
	const inFlight = new Set<Promise<void>>();
	let nextIndex = 0;

	const startNext = (): void => {
		const index = nextIndex++;
		const file = files[index];
		if (!file) return;

		let task: Promise<void>;
		task = buildSessionInfo(file)
			.then((info) => {
				results[index] = info;
			})
			.catch(() => {
				results[index] = null;
			})
			.finally(() => {
				inFlight.delete(task);
				onLoaded();
			});
		inFlight.add(task);
	};

	while (nextIndex < files.length || inFlight.size > 0) {
		while (nextIndex < files.length && inFlight.size < MAX_CONCURRENT_SESSION_INFO_LOADS) {
			startNext();
		}
		if (inFlight.size > 0) {
			// Snapshot to an array: Promise.race([]) never settles, and mutating the
			// Set while race iterates is undefined territory across engines.
			await Promise.race([...inFlight]);
		}
	}

	return results;
}

async function listSessionFilesFromDirsWithConcurrency(dirs: string[]): Promise<string[][]> {
	const results: string[][] = Array.from({ length: dirs.length }, () => []);
	const inFlight = new Set<Promise<void>>();
	let nextIndex = 0;

	const startNext = (): void => {
		const index = nextIndex++;
		const dir = dirs[index];
		if (!dir) return;

		let task: Promise<void>;
		task = readdir(dir)
			.then((files) => {
				results[index] = files.filter((file) => file.endsWith(".jsonl")).map((file) => join(dir, file));
			})
			.catch(() => {
				results[index] = [];
			})
			.finally(() => {
				inFlight.delete(task);
			});
		inFlight.add(task);
	};

	while (nextIndex < dirs.length || inFlight.size > 0) {
		while (nextIndex < dirs.length && inFlight.size < MAX_CONCURRENT_SESSION_DIR_READS) {
			startNext();
		}
		if (inFlight.size > 0) {
			await Promise.race([...inFlight]);
		}
	}

	return results;
}

async function listSessionsFromDir(
	dir: string,
	onProgress?: SessionListProgress,
	progressOffset = 0,
	progressTotal?: number,
): Promise<SessionInfo[]> {
	const sessions: SessionInfo[] = [];
	if (!existsSync(dir)) {
		return sessions;
	}

	try {
		const dirEntries = await readdir(dir);
		const files = dirEntries.filter((f) => f.endsWith(".jsonl")).map((f) => join(dir, f));
		const total = progressTotal ?? files.length;
		onProgress?.(progressOffset, total);

		let loaded = 0;
		const results = await buildSessionInfosWithConcurrency(files, () => {
			loaded++;
			onProgress?.(progressOffset + loaded, total);
		});
		for (const info of results) {
			if (info) {
				sessions.push(info);
			}
		}
	} catch {
		// Return empty list on error
	}

	return sessions;
}

/**
 * Directories to scan for "current folder" sessions: the explicit sessionDir
 * (if any), the default encoding for cwd, and on Windows the lowercased
 * encoding so casing variants of the same folder still resolve.
 * Only existing dirs are returned (no mkdir).
 */
function collectSessionDirsForCwd(cwd: string, sessionDir?: string): string[] {
	const dirs: string[] = [];
	const seen = new Set<string>();
	const add = (dir: string | undefined) => {
		if (!dir || seen.has(dir) || !existsSync(dir)) return;
		seen.add(dir);
		dirs.push(dir);
	};

	if (sessionDir) {
		add(sessionDir);
	}
	add(sessionDirForCwd(cwd));
	if (process.platform === "win32") {
		add(sessionDirForCwd(resolve(cwd)));
		add(sessionDirForCwd(resolve(cwd).toLowerCase()));
	}
	// If nothing exists yet, fall back to the default creator so a brand-new
	// project still gets a bucket (and an empty list) instead of a hard miss.
	if (dirs.length === 0) {
		add(sessionDir || getDefaultSessionDir(cwd));
	}
	return dirs;
}

// On Windows, AV scanners / indexers hold a transient handle on a just-written
// file, so a write racing them fails with one of these codes. They clear within
// a few ms, so a short bounded retry absorbs them. Hard errors (ENOSPC/ENOENT)
// are NOT here — they must propagate immediately.
const TRANSIENT_FS_CODES = new Set(["EBUSY", "EPERM", "EACCES"]);
const FS_RETRY_BACKOFF_MS = [0, 20, 60];

function isTransientFsError(err: unknown): boolean {
	const code = (err as { code?: string } | null)?.code;
	return typeof code === "string" && TRANSIENT_FS_CODES.has(code);
}

// Synchronous sleep without busy-spinning the CPU: Atomics.wait blocks the
// thread on a throwaway buffer for the given ms. _persist is sync (appendFileSync),
// so we can't await a timer here.
const SLEEP_BUFFER = new Int32Array(new SharedArrayBuffer(4));
function sleepSync(ms: number): void {
	if (ms <= 0) return;
	Atomics.wait(SLEEP_BUFFER, 0, 0, ms);
}

// appendFileSync of a complete batch is a single write() syscall, but a transient
// AV/indexer lock (EBUSY/EPERM/EACCES) can still bounce it. Retry a few times with
// a short backoff; on the final failure the error propagates (the caller's state
// is kept safe for a later retry by the flushed/_writeQueue invariants in _persist).
function recordFsAppendRetry(source: string, file: string, attempt: number, err: unknown): void {
	recordDiagnostic({
		category: "io.retry",
		level: "warn",
		source,
		context: {
			attempt: attempt + 1,
			path: file,
			note: (err as { code?: string } | null)?.code,
		},
	});
}

function shouldRetryFsAppend(err: unknown, attempt: number): boolean {
	const last = attempt === FS_RETRY_BACKOFF_MS.length - 1;
	if (last || !isTransientFsError(err)) {
		return false;
	}
	return true;
}

function appendWithRetry(file: string, data: string): void {
	for (let attempt = 0; attempt < FS_RETRY_BACKOFF_MS.length; attempt++) {
		try {
			appendFileSync(file, data);
			return;
		} catch (err) {
			if (!shouldRetryFsAppend(err, attempt)) throw err;
			recordFsAppendRetry("session-manager.appendWithRetry", file, attempt, err);
			// No Atomics.wait on the sync path — retries are immediate. Sustained
			// contention uses the async drain (setTimeout backoff) after initial flush.
		}
	}
}

async function withFsAppendRetry(
	file: string,
	data: string,
	write: (targetFile: string, payload: string) => Promise<void>,
	source: string,
): Promise<void> {
	for (let attempt = 0; attempt < FS_RETRY_BACKOFF_MS.length; attempt++) {
		try {
			await write(file, data);
			return;
		} catch (err) {
			if (!shouldRetryFsAppend(err, attempt)) throw err;
			recordFsAppendRetry(source, file, attempt, err);
			await new Promise((resolve) => setTimeout(resolve, FS_RETRY_BACKOFF_MS[attempt + 1]));
		}
	}
}

async function appendWithRetryAsync(file: string, data: string): Promise<void> {
	await withFsAppendRetry(file, data, appendFile, "session-manager.appendWithRetryAsync");
}

// Atomic full-file rewrite: write to a sibling temp file, then rename over the
// destination (rename is atomic on the same filesystem). A crash mid-write leaves
// only the temp file, never a truncated session. On Windows rename onto an existing
// file can fail with EEXIST/EPERM, and AV locks can throw transient codes, so we
// retry; if rename still fails we fall back to a direct write (degrades to the old
// non-atomic behavior — no worse than before). The temp file is always cleaned up.
function writeFileAtomic(file: string, data: string): void {
	const tmp = `${file}.tmp-${process.pid}`;
	try {
		writeFileSync(tmp, data);
	} catch (err) {
		tryUnlink(tmp);
		throw err;
	}
	for (let attempt = 0; attempt < FS_RETRY_BACKOFF_MS.length; attempt++) {
		try {
			renameSync(tmp, file);
			return;
		} catch (err) {
			const last = attempt === FS_RETRY_BACKOFF_MS.length - 1;
			if (!last && isTransientFsError(err)) {
				sleepSync(FS_RETRY_BACKOFF_MS[attempt + 1]);
				continue;
			}
			// Final attempt failed (or a non-transient error like EEXIST on some
			// Windows configs): fall back to a direct in-place write so we still
			// persist, then drop the temp file.
			try {
				writeFileSync(file, data);
			} finally {
				tryUnlink(tmp);
			}
			return;
		}
	}
}

function tryUnlink(file: string): void {
	try {
		unlinkSync(file);
	} catch {
		// Best-effort cleanup; a leftover .tmp is harmless and gets overwritten.
	}
}

/**
 * Manages conversation sessions as append-only trees stored in JSONL files.
 *
 * Each session entry has an id and parentId forming a tree structure. The "leaf"
 * pointer tracks the current position. Appending creates a child of the current leaf.
 * Branching moves the leaf to an earlier entry, allowing new branches without
 * modifying history.
 *
 * Use buildSessionContext() to get the resolved message list for the LLM, which
 * handles compaction summaries and follows the path from root to current leaf.
 */
export class SessionManager {
	private sessionId: string = "";
	private sessionFile: string | undefined;
	private sessionDir: string;
	private cwd: string;
	private persist: boolean;
	private flushed: boolean = false;
	private fileEntries: FileEntry[] = [];
	private byId: Map<string, SessionEntry> = new Map();
	private labelsById: Map<string, string> = new Map();
	private labelTimestampsById: Map<string, string> = new Map();
	private leafId: string | null = null;

	private constructor(cwd: string, sessionDir: string, sessionFile: string | undefined, persist: boolean) {
		this.cwd = cwd;
		this.sessionDir = sessionDir;
		this.persist = persist;
		if (persist && sessionDir && !existsSync(sessionDir)) {
			mkdirSync(sessionDir, { recursive: true });
		}

		if (sessionFile) {
			this.setSessionFile(sessionFile);
		} else {
			this.newSession();
		}
	}

	/** Switch to a different session file (used for resume and branching) */
	setSessionFile(sessionFile: string): void {
		this.sessionFile = resolve(sessionFile);
		if (existsSync(this.sessionFile)) {
			this.fileEntries = loadEntriesFromFile(this.sessionFile);

			// If file was empty or corrupted (no valid header), truncate and start fresh
			// to avoid appending messages without a session header (which breaks the session)
			if (this.fileEntries.length === 0) {
				const explicitPath = this.sessionFile;
				this.newSession();
				this.sessionFile = explicitPath;
				this._rewriteFile();
				this.flushed = true;
				return;
			}

			const header = this.fileEntries.find((e) => e.type === "session") as SessionHeader | undefined;
			this.sessionId = header?.id ?? createSessionId();

			if (migrateToCurrentVersion(this.fileEntries)) {
				this._rewriteFile();
			}

			this._buildIndex();
			this.flushed = true;
			this._hasAssistantMessage = this.fileEntries.some(
				(e) => e.type === "message" && e.message.role === "assistant",
			);
		} else {
			const explicitPath = this.sessionFile;
			this.newSession();
			this.sessionFile = explicitPath; // preserve explicit path from --session flag
		}
	}

	newSession(options?: NewSessionOptions): string | undefined {
		this.sessionId = options?.id ?? createSessionId();
		const timestamp = new Date().toISOString();
		const header: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: this.sessionId,
			timestamp,
			cwd: this.cwd,
			parentSession: options?.parentSession,
		};
		this.fileEntries = [header];
		this.byId.clear();
		this.labelsById.clear();
		this.leafId = null;
		this.flushed = false;
		this._hasAssistantMessage = false;
		this._entriesOnlyCache = null;
		this._ctxCache = null;
		this.latestSessionName = undefined;

		if (this.persist) {
			const fileTimestamp = timestamp.replace(/[:.]/g, "-");
			this.sessionFile = join(this.getSessionDir(), `${fileTimestamp}_${this.sessionId}.jsonl`);
		}
		return this.sessionFile;
	}

	private _buildIndex(): void {
		this.byId.clear();
		this.labelsById.clear();
		this.labelTimestampsById.clear();
		this.leafId = null;
		this._entriesOnlyCache = null;
		this._ctxCache = null;
		this.latestSessionName = undefined;
		for (const entry of this.fileEntries) {
			if (entry.type === "session") continue;
			this.byId.set(entry.id, entry);
			this.leafId = entry.id;
			if (entry.type === "label") {
				if (entry.label) {
					this.labelsById.set(entry.targetId, entry.label);
					this.labelTimestampsById.set(entry.targetId, entry.timestamp);
				} else {
					this.labelsById.delete(entry.targetId);
					this.labelTimestampsById.delete(entry.targetId);
				}
			} else if (entry.type === "session_info") {
				this.latestSessionName = entry.name?.trim() || undefined;
			}
		}
	}

	private _rewriteFile(): void {
		if (!this.persist || !this.sessionFile) return;
		// Redact credentials on the way to disk only: each [REDACTED:x] token has no
		// JSON metacharacters, so the serialized lines stay parseable. The in-memory
		// fileEntries keep the verbatim value for the live turn.
		//
		// Redact PER PHYSICAL LINE, never on the joined multi-line buffer: the
		// private-key pattern's `[\s\S]*?` body matches across literal `\n`, so a
		// BEGIN armor in one entry plus an END armor in a later entry would collapse
		// the whole span — including the JSONL line separators and any entries
		// between them — into a single token, destroying valid history. Inside a
		// single serialized line all real newlines are escaped to `\\n`, so the
		// documented single-line JSON-safety guarantee holds only when each line is
		// scrubbed in isolation.
		const safe = `${this.fileEntries.map((e) => redactForDisk(JSON.stringify(e))).join("\n")}\n`;
		// Atomic rewrite (temp + rename) so a crash mid-write never truncates the
		// session file. Falls back to a direct write if rename is unavailable.
		writeFileAtomic(this.sessionFile, safe);
	}

	isPersisted(): boolean {
		return this.persist;
	}

	getCwd(): string {
		return this.cwd;
	}

	getSessionDir(): string {
		return this.sessionDir;
	}

	getSessionId(): string {
		return this.sessionId;
	}

	getSessionFile(): string | undefined {
		return this.sessionFile;
	}

	private _hasAssistantMessage = false;
	private _writeQueue: string[] = [];
	private _draining: Promise<void> | null = null;
	private _entriesOnlyCache: SessionEntry[] | null = null;
	// Cache the built context per leaf. buildSessionContext() is called from
	// ~7 sites per turn (runtime, agent-session, interactive, sdk, main); the
	// session is append-only so leafId fully keys the path. Invalidated only
	// when fileEntries is replaced (newSession / _buildIndex). Returned arrays
	// are sliced so callers that mutate state.messages can't poison the cache.
	private _ctxCache: { leafId: string | null; ctx: SessionContext } | null = null;
	// Latest session_info display name (trimmed; undefined when none or cleared).
	// Tracked incrementally so getSessionName() is O(1) instead of a reverse
	// scan over all entries on every UI refresh. Mirrors getEntries() ordering:
	// updated on append, rebuilt in _buildIndex, reset in newSession.
	private latestSessionName: string | undefined = undefined;

	_persist(entry: SessionEntry): void {
		if (!this.persist || !this.sessionFile) return;

		if (!this._hasAssistantMessage) {
			if (entry.type === "message" && entry.message.role === "assistant") {
				this._hasAssistantMessage = true;
			} else {
				this.flushed = false;
				return;
			}
		}

		// Build the batch up front. The first durable write stays synchronous —
		// callers may list/re-open the session immediately after the first
		// assistant message lands. Subsequent deltas drain asynchronously via
		// _drainQueue (flushWrites() at turn/dispose boundaries restores durability).
		// Redact credentials on the disk-egress boundary only, PER PHYSICAL LINE.
		// The private-key pattern's `[\s\S]*?` body matches across literal `\n`, so
		// scrubbing the joined multi-line batch would let a BEGIN armor in one entry
		// pair with an END armor in a later entry and collapse the span — including
		// the JSONL separators and any entries between — into a single token,
		// corrupting the file. Inside one serialized line all real newlines are
		// escaped to `\\n`, so the documented single-line JSON-safety guarantee
		// holds only when each line is redacted in isolation. [REDACTED:x] carries
		// no JSON metacharacters, so the written lines stay valid JSON. The live
		// in-memory entries are left verbatim for the active turn.
		const isInitialFlush = !this.flushed;
		if (isInitialFlush) {
			let batch = this.fileEntries.map((e) => `${redactForDisk(JSON.stringify(e))}\n`).join("");
			// First durable write must stay synchronous — callers may list/re-open
			// the session immediately after the first assistant message lands.
			if (this._writeQueue.length > 0) {
				batch = this._writeQueue.join("") + batch;
			}
			appendWithRetry(this.sessionFile, batch);
			this.flushed = true;
			this._writeQueue.length = 0;
			return;
		}

		const line = `${redactForDisk(JSON.stringify(entry))}\n`;
		this._writeQueue.push(line);
		void this._drainQueue().catch((err) => {
			recordDiagnostic({
				category: "io.retry",
				level: "warn",
				source: "session-manager._persist.drain",
				context: {
					path: this.sessionFile,
					note: err instanceof Error ? err.message : String(err),
				},
			});
		});
	}

	private async _drainQueue(): Promise<void> {
		// Serialize concurrent drains: appendFile on the same path is not atomic
		// across overlapping handles. Without this, a manual flushWrites racing a
		// timer-triggered drain can interleave bytes mid-JSONL line.
		if (this._draining) {
			await this._draining;
			if (this._writeQueue.length === 0) return;
		}
		const drainPromise = (async () => {
			while (this._writeQueue.length > 0 && this.sessionFile) {
				const pending = this._writeQueue.length;
				const batch = this._writeQueue.join("");
				await appendWithRetryAsync(this.sessionFile, batch);
				this._writeQueue.splice(0, pending);
			}
		})();
		this._draining = drainPromise;
		try {
			await drainPromise;
		} finally {
			if (this._draining === drainPromise) {
				this._draining = null;
			}
		}
	}

	async flushWrites(): Promise<void> {
		await this._drainQueue();
	}

	private _appendEntry(entry: SessionEntry): void {
		this.fileEntries.push(entry);
		this.byId.set(entry.id, entry);
		this.leafId = entry.id;
		if (entry.type === "session_info") {
			this.latestSessionName = entry.name?.trim() || undefined;
		}
		if (this._entriesOnlyCache) {
			this._entriesOnlyCache.push(entry);
		}
		this._persist(entry);
	}

	/** Append a message as child of current leaf, then advance leaf. Returns entry id.
	 * Does not allow writing CompactionSummaryMessage and BranchSummaryMessage directly.
	 * Reason: we want these to be top-level entries in the session, not message session entries,
	 * so it is easier to find them.
	 * These need to be appended via appendCompaction() and appendBranchSummary() methods.
	 */
	appendMessage(message: Message | CustomMessage | BashExecutionMessage): string {
		const entry: SessionMessageEntry = {
			type: "message",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			message,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a thinking level change as child of current leaf, then advance leaf. Returns entry id. */
	appendThinkingLevelChange(thinkingLevel: string): string {
		const entry: ThinkingLevelChangeEntry = {
			type: "thinking_level_change",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			thinkingLevel,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a model change as child of current leaf, then advance leaf. Returns entry id. */
	appendModelChange(provider: string, modelId: string): string {
		const entry: ModelChangeEntry = {
			type: "model_change",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			provider,
			modelId,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a compaction summary as child of current leaf, then advance leaf. Returns entry id. */
	appendCompaction<T = unknown>(
		summary: string,
		firstKeptEntryId: string,
		tokensBefore: number,
		details?: T,
		fromHook?: boolean,
	): string {
		const entry: CompactionEntry<T> = {
			type: "compaction",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			summary,
			firstKeptEntryId,
			tokensBefore,
			details,
			fromHook,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a custom entry (for extensions) as child of current leaf, then advance leaf. Returns entry id. */
	appendCustomEntry(customType: string, data?: unknown): string {
		const entry: CustomEntry = {
			type: "custom",
			customType,
			data,
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a session info entry (e.g., display name). Returns entry id. */
	appendSessionInfo(name: string): string {
		const entry: SessionInfoEntry = {
			type: "session_info",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			name: name.trim(),
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Get the current session name from the latest session_info entry, if any. */
	getSessionName(): string | undefined {
		// O(1): maintained incrementally in _appendEntry/_buildIndex (mirrors the
		// old reverse scan over getEntries() — latest session_info wins, empty
		// name clears the title).
		return this.latestSessionName;
	}

	/**
	 * Append a custom message entry (for extensions) that participates in LLM context.
	 * @param customType Extension identifier for filtering on reload
	 * @param content Message content (string or TextContent/ImageContent array)
	 * @param display Whether to show in TUI (true = styled display, false = hidden)
	 * @param details Optional extension-specific metadata (not sent to LLM)
	 * @returns Entry id
	 */
	appendCustomMessageEntry<T = unknown>(
		customType: string,
		content: string | (TextContent | ImageContent)[],
		display: boolean,
		details?: T,
	): string {
		const entry: CustomMessageEntry<T> = {
			type: "custom_message",
			customType,
			content,
			display,
			details,
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
		};
		this._appendEntry(entry);
		return entry.id;
	}

	// =========================================================================
	// Tree Traversal
	// =========================================================================

	getLeafId(): string | null {
		return this.leafId;
	}

	getLeafEntry(): SessionEntry | undefined {
		return this.leafId ? this.byId.get(this.leafId) : undefined;
	}

	getEntry(id: string): SessionEntry | undefined {
		return this.byId.get(id);
	}

	/**
	 * Get all direct children of an entry.
	 */
	getChildren(parentId: string): SessionEntry[] {
		const children: SessionEntry[] = [];
		for (const entry of this.byId.values()) {
			if (entry.parentId === parentId) {
				children.push(entry);
			}
		}
		return children;
	}

	/**
	 * Get the label for an entry, if any.
	 */
	getLabel(id: string): string | undefined {
		return this.labelsById.get(id);
	}

	/**
	 * Set or clear a label on an entry.
	 * Labels are user-defined markers for bookmarking/navigation.
	 * Pass undefined or empty string to clear the label.
	 */
	appendLabelChange(targetId: string, label: string | undefined): string {
		if (!this.byId.has(targetId)) {
			throw new Error(`Entry ${targetId} not found`);
		}
		const entry: LabelEntry = {
			type: "label",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			targetId,
			label,
		};
		this._appendEntry(entry);
		if (label) {
			this.labelsById.set(targetId, label);
			this.labelTimestampsById.set(targetId, entry.timestamp);
		} else {
			this.labelsById.delete(targetId);
			this.labelTimestampsById.delete(targetId);
		}
		return entry.id;
	}

	/**
	 * Walk from entry to root, returning all entries in path order.
	 * Includes all entry types (messages, compaction, model changes, etc.).
	 * Use buildSessionContext() to get the resolved messages for the LLM.
	 */
	getBranch(fromId?: string): SessionEntry[] {
		const path: SessionEntry[] = [];
		const startId = fromId ?? this.leafId;
		let current = startId ? this.byId.get(startId) : undefined;
		// Collect leaf→root with push() then reverse() once: O(n). The previous
		// unshift()-in-loop was O(n²) (each unshift shifts all prior elements),
		// and this runs per TUI frame via footer → getContextUsage on long sessions.
		while (current) {
			path.push(current);
			current = current.parentId ? this.byId.get(current.parentId) : undefined;
		}
		path.reverse();
		return path;
	}

	/**
	 * Build the session context (what gets sent to the LLM).
	 * Uses tree traversal from current leaf.
	 */
	buildSessionContext(): SessionContext {
		const cached = this._ctxCache;
		if (cached && cached.leafId === this.leafId) {
			const ctx = cached.ctx;
			// Defensive copy: callers assign this to agent.state.messages and the
			// agent loop push()es into it. Element identity is preserved, so
			// convertToLlm's per-message cache still hits.
			return { messages: ctx.messages.slice(), thinkingLevel: ctx.thinkingLevel, model: ctx.model };
		}
		const ctx = buildSessionContext(this.getEntries(), this.leafId, this.byId);
		this._ctxCache = { leafId: this.leafId, ctx };
		return { messages: ctx.messages.slice(), thinkingLevel: ctx.thinkingLevel, model: ctx.model };
	}

	/**
	 * Get session header.
	 */
	getHeader(): SessionHeader | null {
		// The header is always the first entry; index directly (O(1)) and fall
		// back to a scan only for malformed/legacy ordering.
		const first = this.fileEntries[0];
		if (first?.type === "session") return first as SessionHeader;
		const h = this.fileEntries.find((e) => e.type === "session");
		return h ? (h as SessionHeader) : null;
	}

	/**
	 * Get all session entries (excludes header). Returns a cached reference —
	 * do NOT mutate; treat as read-only. The session is append-only: use
	 * appendXXX() to add entries (cache is extended in place), branch() to
	 * change the leaf pointer. Entries cannot be modified or deleted.
	 *
	 * Cache is invalidated on fileEntries replacement (newSession,
	 * setSessionFile, _buildIndex).
	 */
	getEntries(): SessionEntry[] {
		if (this._entriesOnlyCache) return this._entriesOnlyCache;
		const filtered = this.fileEntries.filter((e): e is SessionEntry => e.type !== "session");
		this._entriesOnlyCache = filtered;
		return filtered;
	}

	/**
	 * Get the session as a tree structure. Returns a shallow defensive copy of all entries.
	 * A well-formed session has exactly one root (first entry with parentId === null).
	 * Orphaned entries (broken parent chain) are also returned as roots.
	 */
	getTree(): SessionTreeNode[] {
		const entries = this.getEntries();
		const nodeMap = new Map<string, SessionTreeNode>();
		const roots: SessionTreeNode[] = [];

		// Create nodes with resolved labels
		for (const entry of entries) {
			const label = this.labelsById.get(entry.id);
			const labelTimestamp = this.labelTimestampsById.get(entry.id);
			nodeMap.set(entry.id, { entry, children: [], label, labelTimestamp });
		}

		// Build tree
		for (const entry of entries) {
			const node = nodeMap.get(entry.id)!;
			if (entry.parentId === null || entry.parentId === entry.id) {
				roots.push(node);
			} else {
				const parent = nodeMap.get(entry.parentId);
				if (parent) {
					parent.children.push(node);
				} else {
					// Orphan - treat as root
					roots.push(node);
				}
			}
		}

		// Sort children by timestamp (oldest first, newest at bottom)
		// Use iterative approach to avoid stack overflow on deep trees
		const stack: SessionTreeNode[] = [...roots];
		while (stack.length > 0) {
			const node = stack.pop()!;
			node.children.sort((a, b) => new Date(a.entry.timestamp).getTime() - new Date(b.entry.timestamp).getTime());
			stack.push(...node.children);
		}

		return roots;
	}

	// =========================================================================
	// Branching
	// =========================================================================

	/**
	 * Start a new branch from an earlier entry.
	 * Moves the leaf pointer to the specified entry. The next appendXXX() call
	 * will create a child of that entry, forming a new branch. Existing entries
	 * are not modified or deleted.
	 */
	branch(branchFromId: string): void {
		if (!this.byId.has(branchFromId)) {
			throw new Error(`Entry ${branchFromId} not found`);
		}
		this.leafId = branchFromId;
	}

	/**
	 * Reset the leaf pointer to null (before any entries).
	 * The next appendXXX() call will create a new root entry (parentId = null).
	 * Use this when navigating to re-edit the first user message.
	 */
	resetLeaf(): void {
		this.leafId = null;
	}

	/**
	 * Start a new branch with a summary of the abandoned path.
	 * Same as branch(), but also appends a branch_summary entry that captures
	 * context from the abandoned conversation path.
	 */
	branchWithSummary(branchFromId: string | null, summary: string, details?: unknown, fromHook?: boolean): string {
		if (branchFromId !== null && !this.byId.has(branchFromId)) {
			throw new Error(`Entry ${branchFromId} not found`);
		}
		this.leafId = branchFromId;
		const entry: BranchSummaryEntry = {
			type: "branch_summary",
			id: generateId(this.byId),
			parentId: branchFromId,
			timestamp: new Date().toISOString(),
			fromId: branchFromId ?? "root",
			summary,
			details,
			fromHook,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/**
	 * Create a new session file containing only the path from root to the specified leaf.
	 * Useful for extracting a single conversation path from a branched session.
	 * Returns the new session file path, or undefined if not persisting.
	 */
	createBranchedSession(leafId: string): string | undefined {
		const previousSessionFile = this.sessionFile;
		const path = this.getBranch(leafId);
		if (path.length === 0) {
			throw new Error(`Entry ${leafId} not found`);
		}

		// Filter out LabelEntry from path - we'll recreate them from the resolved map
		const pathWithoutLabels = path.filter((e) => e.type !== "label");

		const newSessionId = createSessionId();
		const timestamp = new Date().toISOString();
		const fileTimestamp = timestamp.replace(/[:.]/g, "-");
		const newSessionFile = join(this.getSessionDir(), `${fileTimestamp}_${newSessionId}.jsonl`);

		const header: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: newSessionId,
			timestamp,
			cwd: this.cwd,
			parentSession: this.persist ? previousSessionFile : undefined,
		};

		// Collect labels for entries in the path
		const pathEntryIds = new Set(pathWithoutLabels.map((e) => e.id));
		const labelsToWrite: Array<{ targetId: string; label: string; timestamp: string }> = [];
		for (const [targetId, label] of this.labelsById) {
			if (pathEntryIds.has(targetId)) {
				labelsToWrite.push({ targetId, label, timestamp: this.labelTimestampsById.get(targetId)! });
			}
		}

		if (this.persist) {
			// Build label entries
			const lastEntryId = pathWithoutLabels[pathWithoutLabels.length - 1]?.id || null;
			let parentId = lastEntryId;
			const labelEntries: LabelEntry[] = [];
			for (const { targetId, label, timestamp: labelTimestamp } of labelsToWrite) {
				const labelEntry: LabelEntry = {
					type: "label",
					id: generateId(new Set(pathEntryIds)),
					parentId,
					timestamp: labelTimestamp,
					targetId,
					label,
				};
				pathEntryIds.add(labelEntry.id);
				labelEntries.push(labelEntry);
				parentId = labelEntry.id;
			}

			this.fileEntries = [header, ...pathWithoutLabels, ...labelEntries];
			this.sessionId = newSessionId;
			this.sessionFile = newSessionFile;
			this._buildIndex();

			this._hasAssistantMessage = this.fileEntries.some(
				(e) => e.type === "message" && e.message.role === "assistant",
			);
			if (this._hasAssistantMessage) {
				this._rewriteFile();
				this.flushed = true;
			} else {
				this.flushed = false;
			}

			return newSessionFile;
		}

		// In-memory mode: replace current session with the path + labels
		const labelEntries: LabelEntry[] = [];
		let parentId = pathWithoutLabels[pathWithoutLabels.length - 1]?.id || null;
		for (const { targetId, label, timestamp: labelTimestamp } of labelsToWrite) {
			const labelEntry: LabelEntry = {
				type: "label",
				id: generateId(new Set([...pathEntryIds, ...labelEntries.map((e) => e.id)])),
				parentId,
				timestamp: labelTimestamp,
				targetId,
				label,
			};
			labelEntries.push(labelEntry);
			parentId = labelEntry.id;
		}
		this.fileEntries = [header, ...pathWithoutLabels, ...labelEntries];
		this.sessionId = newSessionId;
		this._buildIndex();
		return undefined;
	}

	/**
	 * Create a new session.
	 * @param cwd Working directory (stored in session header)
	 * @param sessionDir Optional session directory. If omitted, uses default (~/.pit/agent/sessions/<encoded-cwd>/).
	 */
	static create(cwd: string, sessionDir?: string): SessionManager {
		const dir = sessionDir ?? getDefaultSessionDir(cwd);
		return new SessionManager(cwd, dir, undefined, true);
	}

	/**
	 * Open a specific session file.
	 * @param path Path to session file
	 * @param sessionDir Optional session directory for /new or /branch. If omitted, derives from file's parent.
	 * @param cwdOverride Optional cwd override instead of the session header cwd.
	 */
	static open(path: string, sessionDir?: string, cwdOverride?: string): SessionManager {
		// Extract cwd from session header if possible, otherwise use process.cwd()
		const entries = loadEntriesFromFile(path);
		const header = entries.find((e) => e.type === "session") as SessionHeader | undefined;
		const cwd = cwdOverride ?? header?.cwd ?? process.cwd();
		// If no sessionDir provided, derive from file's parent directory
		const dir = sessionDir ?? resolve(path, "..");
		return new SessionManager(cwd, dir, path, true);
	}

	/**
	 * Continue the most recent session, or create new if none.
	 * @param cwd Working directory
	 * @param sessionDir Optional session directory. If omitted, uses default (~/.pit/agent/sessions/<encoded-cwd>/).
	 */
	static continueRecent(cwd: string, sessionDir?: string): SessionManager {
		const dir = sessionDir ?? getDefaultSessionDir(cwd);
		const mostRecent = findMostRecentSession(dir);
		if (mostRecent) {
			return new SessionManager(cwd, dir, mostRecent, true);
		}
		return new SessionManager(cwd, dir, undefined, true);
	}

	/** Create an in-memory session (no file persistence) */
	static inMemory(cwd: string = process.cwd()): SessionManager {
		return new SessionManager(cwd, "", undefined, false);
	}

	/**
	 * Fork a session from another project directory into the current project.
	 * Creates a new session in the target cwd with the full history from the source session.
	 * @param sourcePath Path to the source session file
	 * @param targetCwd Target working directory (where the new session will be stored)
	 * @param sessionDir Optional session directory. If omitted, uses default for targetCwd.
	 */
	static forkFrom(sourcePath: string, targetCwd: string, sessionDir?: string): SessionManager {
		const sourceEntries = loadEntriesFromFile(sourcePath);
		if (sourceEntries.length === 0) {
			throw new Error(`Cannot fork: source session file is empty or invalid: ${sourcePath}`);
		}

		const sourceHeader = sourceEntries.find((e) => e.type === "session") as SessionHeader | undefined;
		if (!sourceHeader) {
			throw new Error(`Cannot fork: source session has no header: ${sourcePath}`);
		}

		const dir = sessionDir ?? getDefaultSessionDir(targetCwd);
		if (!existsSync(dir)) {
			mkdirSync(dir, { recursive: true });
		}

		// Create new session file with new ID but forked content
		const newSessionId = createSessionId();
		const timestamp = new Date().toISOString();
		const fileTimestamp = timestamp.replace(/[:.]/g, "-");
		const newSessionFile = join(dir, `${fileTimestamp}_${newSessionId}.jsonl`);

		// Write new header pointing to source as parent, with updated cwd
		const newHeader: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: newSessionId,
			timestamp,
			cwd: targetCwd,
			parentSession: sourcePath,
		};
		// Serialize the header and all non-header entries into a single buffer and
		// write once, instead of N+1 synchronous appendFileSync syscalls (one per
		// entry) that block the event loop and could leave a partial file on a
		// crash mid-loop.
		const lines = [`${JSON.stringify(newHeader)}\n`];
		for (const entry of sourceEntries) {
			if (entry.type !== "session") {
				lines.push(`${JSON.stringify(entry)}\n`);
			}
		}
		// Atomic write (temp + rename): a crash mid-fork never leaves a truncated
		// forked session on disk.
		writeFileAtomic(newSessionFile, lines.join(""));

		return new SessionManager(targetCwd, dir, newSessionFile, true);
	}

	/**
	 * List sessions for the execution folder (`cwd`).
	 *
	 * Scans the project session bucket (and Windows casing variants of that
	 * bucket), then keeps only sessions whose header `cwd` matches the folder
	 * where the agent is running. That way a shared `--session-dir` or a
	 * differently-cased path still surfaces the right project sessions.
	 *
	 * @param cwd Working directory (used to compute default session directory + filter)
	 * @param sessionDir Optional session directory. If omitted, uses default (~/.pit/agent/sessions/<encoded-cwd>/).
	 * @param onProgress Optional callback for progress updates (loaded, total)
	 */
	static async list(cwd: string, sessionDir?: string, onProgress?: SessionListProgress): Promise<SessionInfo[]> {
		const dirs = collectSessionDirsForCwd(cwd, sessionDir);
		const byPath = new Map<string, SessionInfo>();

		for (const dir of dirs) {
			const batch = await listSessionsFromDir(dir, onProgress);
			for (const session of batch) {
				if (!sessionMatchesCwd(session.cwd, cwd)) continue;
				byPath.set(session.path, session);
			}
		}

		const sessions = [...byPath.values()];
		sessions.sort((a, b) => b.modified.getTime() - a.modified.getTime());
		return sessions;
	}

	/**
	 * List all sessions across all project directories.
	 * Skips ephemeral/temp session buckets (see {@link isEphemeralSessionDirName}).
	 * @param onProgress Optional callback for progress updates (loaded, total)
	 */
	static async listAll(onProgress?: SessionListProgress): Promise<SessionInfo[]> {
		const sessionsDir = getSessionsDir();

		try {
			if (!existsSync(sessionsDir)) {
				return [];
			}
			const entries = await readdir(sessionsDir, { withFileTypes: true });
			const dirs = entries
				.filter((e) => e.isDirectory() && !isEphemeralSessionDirName(e.name))
				.map((e) => join(sessionsDir, e.name));

			// Directory scan can dominate on large corpora (tens of thousands of
			// project dirs). Surface indeterminate progress so the picker isn't
			// stuck on a blank "Loading …" with no counters.
			onProgress?.(0, Math.max(1, dirs.length));

			// Count total files first for accurate progress.
			const dirFiles = await listSessionFilesFromDirsWithConcurrency(dirs);
			const totalFiles = dirFiles.reduce((sum, files) => sum + files.length, 0);
			onProgress?.(0, totalFiles);

			// Process all files with progress tracking
			let loaded = 0;
			const sessions: SessionInfo[] = [];
			const allFiles = dirFiles.flat();

			const results = await buildSessionInfosWithConcurrency(allFiles, () => {
				loaded++;
				onProgress?.(loaded, totalFiles);
			});

			for (const info of results) {
				if (info) {
					sessions.push(info);
				}
			}

			sessions.sort((a, b) => b.modified.getTime() - a.modified.getTime());
			return sessions;
		} catch {
			return [];
		}
	}
}
